MPM transfer P2G
yiminlin-tri/drake pull request #11
Opened 2022-05-27 01:33 UTC by yiminlin-tri

2022-05-27 01:40 UTC, yiminlin-tri reviewed
@xuchenhan-tri I couldn't find a good test case for transferring particle stress to grid force. For other ones I tested the conservation of velocity and momentum. We can discuss next week. Thanks! And have a great holiday! (By the way, I mistakenly make a PR to the master branch of upstream and closed it, is there any way I can delete this PR?)

> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/11#-:-N3298JnB_UoUADKSOvW:b-9xke3u)* status: 0 of 6 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-05-27 01:41 UTC, yiminlin-tri reviewed
^ conservation of mass

> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/11#-:-N32A8Up9RIjcLZFcBOX:bg28gwx)* status: 0 of 6 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-05-27 02:14 UTC, yiminlin-tri reviewed
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/11)* status: 0 of 6 files reviewed, 1 unresolved discussion

___
*[`multibody/fem/mpm-dev/MPMTransfer.cc` line 17 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/11#-N32HfZM-mK21IRZZ9zr:-N32HfZN0UoooNUNaxW1:b-bnxzql) ([raw file](https://github.com/yiminlin-tri/drake/blob/37010210ef44bb4dfbe4d3d227460841c0935aa6/multibody/fem/mpm-dev/MPMTransfer.cc#L17)):*
> ```cpp
>     double mass_p, ref_volume_p;
> 
>     // Clear particles states
> ```

TODO: incorrect comment


<!-- Sent from Reviewable.io -->

2022-05-27 02:33 UTC, xuchenhan-tri commented
+@xuchenhan-tri 





<!-- Sent from Reviewable.io -->

2022-05-27 02:50 UTC, xuchenhan-tri requested changes
I made a pass over the implementation. Mostly nits, with one important question: are we not collecting particle information to 3x3x3 scratch pads and then writing to the global grid?

> Reviewed 4 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/11#-:-N32PZ4y2TF8V0QAoGM3:bm48i3v)* status: 4 of 6 files reviewed, 3 unresolved discussions (waiting on @xuchenhan-tri and @yiminlin-tri)

___
*[`multibody/fem/mpm-dev/Grid.h` line 77 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/11#-N32MayX2v5ye9a0JVrS:-N32MayY0KysqKRfGSFi:bsbisj4) ([raw file](https://github.com/yiminlin-tri/drake/blob/37010210ef44bb4dfbe4d3d227460841c0935aa6/multibody/fem/mpm-dev/Grid.h#L77)):*
> ```objc
> 
>     // Set masses, velocities and forces to be 0
>     void ClearStates();
> ```

Consider "ResetStates()"
___
*[`multibody/fem/mpm-dev/MPMTransfer.h` line 82 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/11#-N32NS9b8KFK_sI7Icc4:-N32NS9b8KFK_sI7Icc5:b-yj8xdl) ([raw file](https://github.com/yiminlin-tri/drake/blob/37010210ef44bb4dfbe4d3d227460841c0935aa6/multibody/fem/mpm-dev/MPMTransfer.h#L82)):*
> ```objc
>     // store the momentum into particles' velocities, in TransferParticlesToGrid
>     // we will scale the momentum with the updated mass to get the velocities.
>     void AccumulateGridStatesOnBatch(int p, double mass_p, double V0_p,
> ```

V0_p->reference_volume_p

Using V is slightly confusing because sometimes it also denotes velocities.
___
*[`multibody/fem/mpm-dev/MPMTransfer.cc` line 149 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/11#-N32OAt7AOJ00G6hKnhG:-N32OAt7AOJ00G6hKnhH:b9fxhsb) ([raw file](https://github.com/yiminlin-tri/drake/blob/37010210ef44bb4dfbe4d3d227460841c0935aa6/multibody/fem/mpm-dev/MPMTransfer.cc#L149)):*
> ```cpp
>     int idx_local;
>     double Ni_p;
>     for (int k = bk - 1; k <= bk + 1; ++k) {
> ```

BTW the following is slightly more readable IMO
```
for (int a = -1; a <= 1; ++a) {
for (int b = -1; b <= 1; ++b) {
for (int c = -1; c <= 1; ++c) {
const Vector3<int> grid_index(bi+a, bj+b,bj+c);
...
}
}
}
```
optional
___
*[`multibody/fem/mpm-dev/MPMTransfer.cc` line 158 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/11#-N32Npeo1tiGVGOWKSis:-N32Npeo1tiGVGOWKSit:b69ipqg) ([raw file](https://github.com/yiminlin-tri/drake/blob/37010210ef44bb4dfbe4d3d227460841c0935aa6/multibody/fem/mpm-dev/MPMTransfer.cc#L158)):*
> ```cpp
>         // For each particle in the batch (Assume particles are sorted with
>         // respect to the batch index), update basis evaluations
>         grid->AccumulateMass(i, j, k, m_p*Ni_p);
> ```

Are we not accumulating to a local pad(batch) and then writing to the global grid?


<!-- Sent from Reviewable.io -->

2022-05-27 02:58 UTC, xuchenhan-tri requested changes
Re:testing strategy. I don't have a good test for stress splatting of the top of my head. When you have the constitutive model in place, we can test that forces are (negative) derivatives of the elastic energy. But that would be a tricky test to set up too.

> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/11#-:-N32Q5NG9EWHHkwA36Gx:b-ly634w)* status: 4 of 6 files reviewed, 3 unresolved discussions (waiting on @xuchenhan-tri and @yiminlin-tri)



<!-- Sent from Reviewable.io -->

2022-05-27 03:36 UTC, yiminlin-tri reviewed
Re: 3x3x3 scratch pad - Yes, the issue becomes evident to me when I am implementing G2P, I will make a local pad as we loop through the batches when I am back next week. 
Re: Testing - Thanks for letting me know! I think at the very least I will hard code some values to check.

> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/11#-:-N32ZYXv23-G754MwRGt:b-g8y41)* status: 4 of 6 files reviewed, 3 unresolved discussions (waiting on @xuchenhan-tri and @yiminlin-tri)



<!-- Sent from Reviewable.io -->

2022-05-31 16:16 UTC, yiminlin-tri reviewed
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/11)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @xuchenhan-tri)

___
*[`multibody/fem/mpm-dev/Grid.h` line 77 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/11#-N32MayX2v5ye9a0JVrS:-N3Pk-4x8D5vDjtj2u6I:bb6un1j) ([raw file](https://github.com/yiminlin-tri/drake/blob/37010210ef44bb4dfbe4d3d227460841c0935aa6/multibody/fem/mpm-dev/Grid.h#L77)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Consider "ResetStates()"
</blockquote></details>

Done
___
*[`multibody/fem/mpm-dev/MPMTransfer.h` line 82 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/11#-N32NS9b8KFK_sI7Icc4:-N3PknUu-8es9kN7Km-Q:bb6un1j) ([raw file](https://github.com/yiminlin-tri/drake/blob/37010210ef44bb4dfbe4d3d227460841c0935aa6/multibody/fem/mpm-dev/MPMTransfer.h#L82)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

V0_p->reference_volume_p

Using V is slightly confusing because sometimes it also denotes velocities.
</blockquote></details>

Done
___
*[`multibody/fem/mpm-dev/MPMTransfer.cc` line 17 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/11#-N32HfZM-mK21IRZZ9zr:-N3Pjlkh6Ru2jQtYW8nX:bb6un1j) ([raw file](https://github.com/yiminlin-tri/drake/blob/37010210ef44bb4dfbe4d3d227460841c0935aa6/multibody/fem/mpm-dev/MPMTransfer.cc#L17)):*
<details><summary><i>Previously, yiminlin-tri wrote…</i></summary><blockquote>

TODO: incorrect comment
</blockquote></details>

Done
___
*[`multibody/fem/mpm-dev/MPMTransfer.cc` line 149 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/11#-N32OAt7AOJ00G6hKnhG:-N3Pp_bh5nW_OrbFaMPk:b-cvl7q3) ([raw file](https://github.com/yiminlin-tri/drake/blob/37010210ef44bb4dfbe4d3d227460841c0935aa6/multibody/fem/mpm-dev/MPMTransfer.cc#L149)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW the following is slightly more readable IMO
```
for (int a = -1; a <= 1; ++a) {
for (int b = -1; b <= 1; ++b) {
for (int c = -1; c <= 1; ++c) {
const Vector3<int> grid_index(bi+a, bj+b,bj+c);
...
}
}
}
```
optional
</blockquote></details>

Done, looks great with thanks.
___
*[`multibody/fem/mpm-dev/MPMTransfer.cc` line 158 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/11#-N32Npeo1tiGVGOWKSis:-N3PkpcQ2evEgIssrzLZ:b-f3fm84) ([raw file](https://github.com/yiminlin-tri/drake/blob/37010210ef44bb4dfbe4d3d227460841c0935aa6/multibody/fem/mpm-dev/MPMTransfer.cc#L158)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Are we not accumulating to a local pad(batch) and then writing to the global grid?
</blockquote></details>

Fixed, can you take a look?


<!-- Sent from Reviewable.io -->

2022-05-31 16:17 UTC, yiminlin-tri reviewed
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/11)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @xuchenhan-tri)

___
*[`multibody/fem/mpm-dev/test/MPMTransfer_test.cc` line 495 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/11#-N3Ptwls0KOY0cWNqKvl:-N3Ptwls0KOY0cWNqKvm:b7uwd6p) ([raw file](https://github.com/yiminlin-tri/drake/blob/cdfb6bd38489f06f6743ee6dff4f48a336c77d55/multibody/fem/mpm-dev/test/MPMTransfer_test.cc#L495)):*
> ```cpp
>     }
> 
>     Particles* particles_;
> ```

I allocate these on the heap because I want to reuse them in the G2P test.


<!-- Sent from Reviewable.io -->

2022-05-31 16:19 UTC, yiminlin-tri reviewed
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/11)* status: 0 of 6 files reviewed, 4 unresolved discussions (waiting on @xuchenhan-tri)

___
*[`multibody/fem/mpm-dev/test/MPMTransfer_test.cc` line 487 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/11#-N3PuSSS5afo6bXtzgvu:-N3PuSSTDOk9SzMSuUrs:bgwy9yi) ([raw file](https://github.com/yiminlin-tri/drake/blob/cdfb6bd38489f06f6743ee6dff4f48a336c77d55/multibody/fem/mpm-dev/test/MPMTransfer_test.cc#L487)):*
> ```cpp
>         }
>         }
> ```

Just realized I need to add a test on the forces. Working on it now.


<!-- Sent from Reviewable.io -->

2022-05-31 17:12 UTC, xuchenhan-tri requested changes
Just reviewed the header and the implementations.  Looks great! I have a few follow-up comments. PTAL.

Looking at the tests now.

> Reviewed 4 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/11#-:-N3Q5TDB6vONo74qg0yU:b-wtitpf)* status: 4 of 6 files reviewed, 6 unresolved discussions (waiting on @xuchenhan-tri and @yiminlin-tri)

___
*[`multibody/fem/mpm-dev/MPMTransfer.h` line 94 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/11#-N3Q3O4978X83mGIwQqO:-N3Q3O4978X83mGIwQqP:b4zbcwd) ([raw file](https://github.com/yiminlin-tri/drake/blob/cdfb6bd38489f06f6743ee6dff4f48a336c77d55/multibody/fem/mpm-dev/MPMTransfer.h#L94)):*
> ```objc
>                                              Vector3<double>>, 27>* sum_local);
> 
>     void UpdateGridStatesOnBatch(const Vector3<int>& batch_index_3d,
> ```

I'm not sure "on" is the correct preposition. How about `WriteBatchStateToGrid()` or `WriteScratchPadStateToGrid()`? This makes it clear that the information is going from the pad to the grid.
___
*[`multibody/fem/mpm-dev/MPMTransfer.cc` line 18 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/11#-N3Q1rLA30sGr2qBrWQz:-N3Q1rLA30sGr2qBrWR-:by0scrf) ([raw file](https://github.com/yiminlin-tri/drake/blob/cdfb6bd38489f06f6743ee6dff4f48a336c77d55/multibody/fem/mpm-dev/MPMTransfer.cc#L18)):*
> ```cpp
>     // Local sum of states m_i v_i f_i on the grid points
>     std::array<std::tuple<double,
>                           Vector3<double>,
> ```

nit This would be a whole lot more readable if we make a local struct instead of using std::tuple. For one, we eliminate the need to remember which one of these vector3's is the velocity and which is the force.
___
*[`multibody/fem/mpm-dev/MPMTransfer.cc` line 31 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/11#-N3Q2IhX1HYPQQb0tHO3:-N3Q2IhX1HYPQQb0tHO4:b-coy2c1) ([raw file](https://github.com/yiminlin-tri/drake/blob/cdfb6bd38489f06f6743ee6dff4f48a336c77d55/multibody/fem/mpm-dev/MPMTransfer.cc#L31)):*
> ```cpp
>         // Clear local scratch pad
>         for (auto& s : sum_local) {
>             std::get<0>(s) = 0.0;
> ```

nit, with a local data structure for the scratch pad, this can simply be a clear(), or reset().
___
*[`multibody/fem/mpm-dev/MPMTransfer.cc` line 223 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/11#-N3Q4KLb8i3JgqmHahtN:-N3Q4KLb8i3JgqmHahtO:b-q673cl) ([raw file](https://github.com/yiminlin-tri/drake/blob/cdfb6bd38489f06f6743ee6dff4f48a336c77d55/multibody/fem/mpm-dev/MPMTransfer.cc#L223)):*
> ```cpp
>     grid_index(1) = bj+b;
>     grid_index(2) = bk+c;
>     if (grid->in_index_range(grid_index)) {
> ```

We only need to perform this check once in a single P2G transfer. Perhaps we could isolate this out into a separate method performed at the beginning of the transfer?


<!-- Sent from Reviewable.io -->

2022-05-31 17:25 UTC, yiminlin-tri reviewed
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/11)* status: 4 of 6 files reviewed, 5 unresolved discussions (waiting on @xuchenhan-tri and @yiminlin-tri)

___
*[`multibody/fem/mpm-dev/test/MPMTransfer_test.cc` line 487 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/11#-N3PuSSS5afo6bXtzgvu:-N3Q8bqQEt73evetpokK:be321mj) ([raw file](https://github.com/yiminlin-tri/drake/blob/cdfb6bd38489f06f6743ee6dff4f48a336c77d55/multibody/fem/mpm-dev/test/MPMTransfer_test.cc#L487)):*
<details><summary><i>Previously, yiminlin-tri wrote…</i></summary><blockquote>

Just realized I need to add a test on the forces. Working on it now.
</blockquote></details>

Done. In the next commit.


<!-- Sent from Reviewable.io -->

2022-05-31 18:10 UTC, xuchenhan-tri requested changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> with a few nits in the tests.

> Reviewed 2 of 6 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/11#-:-N3QJ1a7DBjB9tAInyMz:b-ok4l7h)* status: all files reviewed, 9 unresolved discussions (waiting on @yiminlin-tri)

___
*[`multibody/fem/mpm-dev/test/Grid_test.cc` line 160 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/11#-N3Q7EcZ4C0dN5UFtDN0:-N3Q7EcZ4C0dN5UFtDN1:b-ttplv8) ([raw file](https://github.com/yiminlin-tri/drake/blob/cdfb6bd38489f06f6743ee6dff4f48a336c77d55/multibody/fem/mpm-dev/test/Grid_test.cc#L160)):*
> ```cpp
>     EXPECT_EQ(grid.get_num_gridpt(), 72);
>     EXPECT_TRUE(CompareMatrices(grid.get_num_gridpt_1D(), Vector3<int>(6, 3, 4),
>                                 kEps));
> ```

FYI, the tolerance is an optional argument that's set to zero by default. Thus it can be omitted if you know that equality is exact.
___
*[`multibody/fem/mpm-dev/test/MPMTransfer_test.cc` line 296 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/11#-N3Q8_mW0PmpiWlNDaW-:-N3Q8_mX4sWUISdPy4s3:b-py0uu) ([raw file](https://github.com/yiminlin-tri/drake/blob/cdfb6bd38489f06f6743ee6dff4f48a336c77d55/multibody/fem/mpm-dev/test/MPMTransfer_test.cc#L296)):*
> ```cpp
>     }
> 
>     void checkP2G_1() {
> ```

nit, it'd be nice to put in a comment on what each P2G test does. `_1` and `_2` aren't too helpful.
___
*[`multibody/fem/mpm-dev/test/MPMTransfer_test.cc` line 495 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/11#-N3Ptwls0KOY0cWNqKvl:-N3Q9FIjB3yIUwYhumMD:bh507vl) ([raw file](https://github.com/yiminlin-tri/drake/blob/cdfb6bd38489f06f6743ee6dff4f48a336c77d55/multibody/fem/mpm-dev/test/MPMTransfer_test.cc#L495)):*
<details><summary><i>Previously, yiminlin-tri wrote…</i></summary><blockquote>

I allocate these on the heap because I want to reuse them in the G2P test.
</blockquote></details>

With modern C++, prefer using smart pointers to handle to (de)allocation for you. i.e. use `std::unique_ptr<Particles> particles_;` here.

With that, you can remove all the `delete` lines (smart pointers releases the memory for you), and change all the `new` lines (e.g. ` particles_ = new Particles(num_particles);`) to `particles_ = std::make_unique<Particles>(num_particles);`.

You need to `#include<memory>` for std::unique_ptr and `#include <utility>` for std::make_unique.
___
*[`multibody/fem/mpm-dev/test/MPMTransfer_test.cc` line 353 at r3](https://reviewable.io/reviews/yiminlin-tri/drake/11#-N3QH8B11hArb-MGpB0k:-N3QH8B27rR4oOQzDJHi:b-ad7m7j) ([raw file](https://github.com/yiminlin-tri/drake/blob/271f4e953a419c06fa4bb78cbdc22313477a59b3/multibody/fem/mpm-dev/test/MPMTransfer_test.cc#L353)):*
> ```cpp
> 
>         // Verify the conservation of mass and momentum
>         EXPECT_TRUE(std::abs(mass_p-sum_mass_grid) < TOLERANCE);
> ```

Nice!!

Btw, you could do 

`EXPECT_NEAR(mass_p, sum_mass_grid, TOLERANCE)` and 
`CompareMatrices(momentum_p, sum_momentum_grid, TOLERANCE);`
___
*[`multibody/fem/mpm-dev/test/MPMTransfer_test.cc` line 418 at r3](https://reviewable.io/reviews/yiminlin-tri/drake/11#-N3QIisE5neAsadn1eaY:-N3QIisE5neAsadn1eaZ:b-ig0pb2) ([raw file](https://github.com/yiminlin-tri/drake/blob/271f4e953a419c06fa4bb78cbdc22313477a59b3/multibody/fem/mpm-dev/test/MPMTransfer_test.cc#L418)):*
> ```cpp
> 
>         // Set particles' positions to be on grid points
>         sum_mass1 = 0.0;
> ```

nit, using particle vs. grid instead of 1 vs. 2 would help with readability.
___
*[`multibody/fem/mpm-dev/test/MPMTransfer_test.cc` line 429 at r3](https://reviewable.io/reviews/yiminlin-tri/drake/11#-N3QIYSH9qR8QMBBZfKH:-N3QIYSH9qR8QMBBZfKI:b-2m77ej) ([raw file](https://github.com/yiminlin-tri/drake/blob/271f4e953a419c06fa4bb78cbdc22313477a59b3/multibody/fem/mpm-dev/test/MPMTransfer_test.cc#L429)):*
> ```cpp
>             --pc;
>             particles_->set_position(pc, grid_->get_position(i, j, k));
>             particles_->set_mass(pc, pc+0.1);
> ```

nit, making a local variable `dummy_mass = pc+0.1;` would help with readability.


<!-- Sent from Reviewable.io -->

2022-05-31 21:26 UTC, yiminlin-tri reviewed
Thanks! Fixed. With one question replied.

> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/11#-:-N3Qste80CmSsXU-3cmO:b-kxhnws)* status: 2 of 6 files reviewed, 3 unresolved discussions (waiting on @xuchenhan-tri)

___
*[`multibody/fem/mpm-dev/MPMTransfer.h` line 94 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/11#-N3Q3O4978X83mGIwQqO:-N3Q9IgdDUT3AGuh0K_J:bb6un1j) ([raw file](https://github.com/yiminlin-tri/drake/blob/cdfb6bd38489f06f6743ee6dff4f48a336c77d55/multibody/fem/mpm-dev/MPMTransfer.h#L94)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I'm not sure "on" is the correct preposition. How about `WriteBatchStateToGrid()` or `WriteScratchPadStateToGrid()`? This makes it clear that the information is going from the pad to the grid.
</blockquote></details>

Done
___
*[`multibody/fem/mpm-dev/MPMTransfer.cc` line 18 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/11#-N3Q1rLA30sGr2qBrWQz:-N3QLVThD8aPo-ucabKZ:bb6un1j) ([raw file](https://github.com/yiminlin-tri/drake/blob/cdfb6bd38489f06f6743ee6dff4f48a336c77d55/multibody/fem/mpm-dev/MPMTransfer.cc#L18)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit This would be a whole lot more readable if we make a local struct instead of using std::tuple. For one, we eliminate the need to remember which one of these vector3's is the velocity and which is the force.
</blockquote></details>

Done
___
*[`multibody/fem/mpm-dev/MPMTransfer.cc` line 31 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/11#-N3Q2IhX1HYPQQb0tHO3:-N3QK2rj9o2VGt2r2IZ0:b-sivnsp) ([raw file](https://github.com/yiminlin-tri/drake/blob/cdfb6bd38489f06f6743ee6dff4f48a336c77d55/multibody/fem/mpm-dev/MPMTransfer.cc#L31)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, with a local data structure for the scratch pad, this can simply be a clear(), or reset().
</blockquote></details>

Done. Thanks! Looks very neat.
___
*[`multibody/fem/mpm-dev/MPMTransfer.cc` line 223 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/11#-N3Q4KLb8i3JgqmHahtN:-N3Qt3R125EkuC9OqD77:bfdhj12) ([raw file](https://github.com/yiminlin-tri/drake/blob/cdfb6bd38489f06f6743ee6dff4f48a336c77d55/multibody/fem/mpm-dev/MPMTransfer.cc#L223)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

We only need to perform this check once in a single P2G transfer. Perhaps we could isolate this out into a separate method performed at the beginning of the transfer?
</blockquote></details>

Seems like we need this check to skip grid points not in the domain? Otherwise we will do the accumulation: mass, mv_p, reference_volume_p += val on invalid grid points. (I currently only reserve the memory for bases_val_particles_ and bases_grad_particles_, so values at invalid grid points are undefined.)
___
*[`multibody/fem/mpm-dev/test/Grid_test.cc` line 160 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/11#-N3Q7EcZ4C0dN5UFtDN0:-N3QKI1S6tJkX_8n3t5T:bb6un1j) ([raw file](https://github.com/yiminlin-tri/drake/blob/cdfb6bd38489f06f6743ee6dff4f48a336c77d55/multibody/fem/mpm-dev/test/Grid_test.cc#L160)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

FYI, the tolerance is an optional argument that's set to zero by default. Thus it can be omitted if you know that equality is exact.
</blockquote></details>

Done
___
*[`multibody/fem/mpm-dev/test/MPMTransfer_test.cc` line 296 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/11#-N3Q8_mW0PmpiWlNDaW-:-N3QP9lZBsJWPr04uXcP:bb6un1j) ([raw file](https://github.com/yiminlin-tri/drake/blob/cdfb6bd38489f06f6743ee6dff4f48a336c77d55/multibody/fem/mpm-dev/test/MPMTransfer_test.cc#L296)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, it'd be nice to put in a comment on what each P2G test does. `_1` and `_2` aren't too helpful.
</blockquote></details>

Done
___
*[`multibody/fem/mpm-dev/test/MPMTransfer_test.cc` line 495 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/11#-N3Ptwls0KOY0cWNqKvl:-N3R-Se97SfPVuxbs-YZ:bt4ox15) ([raw file](https://github.com/yiminlin-tri/drake/blob/cdfb6bd38489f06f6743ee6dff4f48a336c77d55/multibody/fem/mpm-dev/test/MPMTransfer_test.cc#L495)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

With modern C++, prefer using smart pointers to handle to (de)allocation for you. i.e. use `std::unique_ptr<Particles> particles_;` here.

With that, you can remove all the `delete` lines (smart pointers releases the memory for you), and change all the `new` lines (e.g. ` particles_ = new Particles(num_particles);`) to `particles_ = std::make_unique<Particles>(num_particles);`.

You need to `#include<memory>` for std::unique_ptr and `#include <utility>` for std::make_unique.


</blockquote></details>

Done. Thanks for the suggestion!
___
*[`multibody/fem/mpm-dev/test/MPMTransfer_test.cc` line 353 at r3](https://reviewable.io/reviews/yiminlin-tri/drake/11#-N3QH8B11hArb-MGpB0k:-N3QNU207zKb0pOrb-Hj:bb6un1j) ([raw file](https://github.com/yiminlin-tri/drake/blob/271f4e953a419c06fa4bb78cbdc22313477a59b3/multibody/fem/mpm-dev/test/MPMTransfer_test.cc#L353)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Nice!!

Btw, you could do 

`EXPECT_NEAR(mass_p, sum_mass_grid, TOLERANCE)` and 
`CompareMatrices(momentum_p, sum_momentum_grid, TOLERANCE);`
</blockquote></details>

Done
___
*[`multibody/fem/mpm-dev/test/MPMTransfer_test.cc` line 418 at r3](https://reviewable.io/reviews/yiminlin-tri/drake/11#-N3QIisE5neAsadn1eaY:-N3QVdR46xwRe2wQ8KhL:bb6un1j) ([raw file](https://github.com/yiminlin-tri/drake/blob/271f4e953a419c06fa4bb78cbdc22313477a59b3/multibody/fem/mpm-dev/test/MPMTransfer_test.cc#L418)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, using particle vs. grid instead of 1 vs. 2 would help with readability.
</blockquote></details>

Done
___
*[`multibody/fem/mpm-dev/test/MPMTransfer_test.cc` line 429 at r3](https://reviewable.io/reviews/yiminlin-tri/drake/11#-N3QIYSH9qR8QMBBZfKH:-N3QX1NNCpgYCUjygNKB:bb6un1j) ([raw file](https://github.com/yiminlin-tri/drake/blob/271f4e953a419c06fa4bb78cbdc22313477a59b3/multibody/fem/mpm-dev/test/MPMTransfer_test.cc#L429)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, making a local variable `dummy_mass = pc+0.1;` would help with readability.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2022-05-31 22:21 UTC, xuchenhan-tri requested changes
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/11)* status: all files reviewed, 6 unresolved discussions (waiting on @yiminlin-tri)

___
*[`multibody/fem/mpm-dev/MPMTransfer.h` line 30 at r4](https://reviewable.io/reviews/yiminlin-tri/drake/11#-N3RAC2e4EV5LwVbPoDX:-N3RAC2e4EV5LwVbPoDY:b-8lv9b5) ([raw file](https://github.com/yiminlin-tri/drake/blob/f487dbe8823e4a2aa7b7eb19bf16b76a5ab98b39/multibody/fem/mpm-dev/MPMTransfer.h#L30)):*
> ```objc
>     // otherwise the results will be incorrect.
>     void SetUpTransfer(const Grid& grid,
>                        const std::unique_ptr<Particles>& particles);
> ```

This should still be `Particles*` to indicate that the particles is being modified.
___
*[`multibody/fem/mpm-dev/MPMTransfer.h` line 35 at r4](https://reviewable.io/reviews/yiminlin-tri/drake/11#-N3RAIs49qRb9u0Mrpue:-N3RAIs49qRb9u0Mrpuf:b-yzsmkd) ([raw file](https://github.com/yiminlin-tri/drake/blob/f487dbe8823e4a2aa7b7eb19bf16b76a5ab98b39/multibody/fem/mpm-dev/MPMTransfer.h#L35)):*
> ```objc
>     // to masses, velocities, and forces on the grid
>     void TransferParticlesToGrid(const Particles& particles,
>                                  const std::unique_ptr<Grid>& grid);
> ```

ditto here.
___
*[`multibody/fem/mpm-dev/MPMTransfer.h` line 83 at r4](https://reviewable.io/reviews/yiminlin-tri/drake/11#-N3RATuYCGkkbD4vqvjz:-N3RATuYCGkkbD4vqvk-:b-yzsmkd) ([raw file](https://github.com/yiminlin-tri/drake/blob/f487dbe8823e4a2aa7b7eb19bf16b76a5ab98b39/multibody/fem/mpm-dev/MPMTransfer.h#L83)):*
> ```objc
>     // points.
>     void SortParticles(const Grid& grid,
>                        const std::unique_ptr<Particles>& particles);
> ```

ditto here.
___
*[`multibody/fem/mpm-dev/MPMTransfer.h` line 110 at r4](https://reviewable.io/reviews/yiminlin-tri/drake/11#-N3RAUkX2SeHhzGxzDja:-N3RAUkX2SeHhzGxzDjb:b-yzsmkd) ([raw file](https://github.com/yiminlin-tri/drake/blob/f487dbe8823e4a2aa7b7eb19bf16b76a5ab98b39/multibody/fem/mpm-dev/MPMTransfer.h#L110)):*
> ```objc
>     void WriteBatchStateToGrid(const Vector3<int>& batch_index_3d,
>                                const std::array<GridState, 27>& sum_local,
>                                const std::unique_ptr<Grid>& grid);
> ```

ditto here.
___
*[`multibody/fem/mpm-dev/MPMTransfer.cc` line 223 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/11#-N3Q4KLb8i3JgqmHahtN:-N3RBP5G1s5zlGxJ57fe:bpfz3am) ([raw file](https://github.com/yiminlin-tri/drake/blob/cdfb6bd38489f06f6743ee6dff4f48a336c77d55/multibody/fem/mpm-dev/MPMTransfer.cc#L223)):*
<details><summary><i>Previously, yiminlin-tri wrote…</i></summary><blockquote>

Seems like we need this check to skip grid points not in the domain? Otherwise we will do the accumulation: mass, mv_p, reference_volume_p += val on invalid grid points. (I currently only reserve the memory for bases_val_particles_ and bases_grad_particles_, so values at invalid grid points are undefined.)
</blockquote></details>

The premise is that if there's ever a invalid grid point, we'd catch it in the first pass. More concretely, I'm suggesting with in `SetupTransfer()` do this:

```
void MPMTransfer::SetUpTransfer(const Grid& grid,
                                const std::unique_ptr<Particles>& particles) {
    SortParticles(grid, particles);
    // Verify that all grid nodes touched by any particle is valid.
    ThrowIfParticlesOutOfBound(grid, particles);
    // From this point on, we will assume all grid node positions are valid.
    UpdateBasisAndGradientParticles(grid, *particles);
}
```
___
*[`multibody/fem/mpm-dev/test/MPMTransfer_test.cc` line 276 at r3](https://reviewable.io/reviews/yiminlin-tri/drake/11#-N3RB-sE2rXv_g2nMY1A:-N3RB-sE2rXv_g2nMY1B:b-20noo8) ([raw file](https://github.com/yiminlin-tri/drake/blob/271f4e953a419c06fa4bb78cbdc22313477a59b3/multibody/fem/mpm-dev/test/MPMTransfer_test.cc#L276)):*
> ```cpp
>         // Sort the particles and set up the batches and preallocate basis
>         // evaluations
>         mpm_transfer.SetUpTransfer(grid, &particles);
> ```

Use `particles.get()` to get the raw pointer behind the smart pointer.


<!-- Sent from Reviewable.io -->

2022-05-31 22:48 UTC, yiminlin-tri reviewed
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/11)* status: 3 of 6 files reviewed, 6 unresolved discussions (waiting on @xuchenhan-tri)

___
*[`multibody/fem/mpm-dev/MPMTransfer.h` line 30 at r4](https://reviewable.io/reviews/yiminlin-tri/drake/11#-N3RAC2e4EV5LwVbPoDX:-N3RDmWa01ba3yxn8nQV:bb6un1j) ([raw file](https://github.com/yiminlin-tri/drake/blob/f487dbe8823e4a2aa7b7eb19bf16b76a5ab98b39/multibody/fem/mpm-dev/MPMTransfer.h#L30)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

This should still be `Particles*` to indicate that the particles is being modified.
</blockquote></details>

Done
___
*[`multibody/fem/mpm-dev/MPMTransfer.h` line 35 at r4](https://reviewable.io/reviews/yiminlin-tri/drake/11#-N3RAIs49qRb9u0Mrpue:-N3RDnC01qkLEtpE2hGl:bb6un1j) ([raw file](https://github.com/yiminlin-tri/drake/blob/f487dbe8823e4a2aa7b7eb19bf16b76a5ab98b39/multibody/fem/mpm-dev/MPMTransfer.h#L35)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

ditto here.
</blockquote></details>

Done
___
*[`multibody/fem/mpm-dev/MPMTransfer.h` line 83 at r4](https://reviewable.io/reviews/yiminlin-tri/drake/11#-N3RATuYCGkkbD4vqvjz:-N3RDnoTAz2kX_yPqRhe:bb6un1j) ([raw file](https://github.com/yiminlin-tri/drake/blob/f487dbe8823e4a2aa7b7eb19bf16b76a5ab98b39/multibody/fem/mpm-dev/MPMTransfer.h#L83)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

ditto here.
</blockquote></details>

Done
___
*[`multibody/fem/mpm-dev/MPMTransfer.h` line 110 at r4](https://reviewable.io/reviews/yiminlin-tri/drake/11#-N3RAUkX2SeHhzGxzDja:-N3RDoWk960UjqNZB6Cc:bb6un1j) ([raw file](https://github.com/yiminlin-tri/drake/blob/f487dbe8823e4a2aa7b7eb19bf16b76a5ab98b39/multibody/fem/mpm-dev/MPMTransfer.h#L110)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

ditto here.
</blockquote></details>

Done
___
*[`multibody/fem/mpm-dev/MPMTransfer.cc` line 223 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/11#-N3Q4KLb8i3JgqmHahtN:-N3RHxmBDxrDGrjCggDU:b-wsvasg) ([raw file](https://github.com/yiminlin-tri/drake/blob/cdfb6bd38489f06f6743ee6dff4f48a336c77d55/multibody/fem/mpm-dev/MPMTransfer.cc#L223)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

The premise is that if there's ever a invalid grid point, we'd catch it in the first pass. More concretely, I'm suggesting with in `SetupTransfer()` do this:

```
void MPMTransfer::SetUpTransfer(const Grid& grid,
                                const std::unique_ptr<Particles>& particles) {
    SortParticles(grid, particles);
    // Verify that all grid nodes touched by any particle is valid.
    ThrowIfParticlesOutOfBound(grid, particles);
    // From this point on, we will assume all grid node positions are valid.
    UpdateBasisAndGradientParticles(grid, *particles);
}
```
</blockquote></details>

Thanks for the explanation!
___
*[`multibody/fem/mpm-dev/test/MPMTransfer_test.cc` line 276 at r3](https://reviewable.io/reviews/yiminlin-tri/drake/11#-N3RB-sE2rXv_g2nMY1A:-N3RDl6Q4gYnuUG_r6ss:bb6un1j) ([raw file](https://github.com/yiminlin-tri/drake/blob/271f4e953a419c06fa4bb78cbdc22313477a59b3/multibody/fem/mpm-dev/test/MPMTransfer_test.cc#L276)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Use `particles.get()` to get the raw pointer behind the smart pointer.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2022-05-31 23:20 UTC, xuchenhan-tri requested changes
> Reviewed 1 of 3 files at r5, 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/11)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @xuchenhan-tri and @yiminlin-tri)

___
*[`multibody/fem/mpm-dev/MPMTransfer.cc` line 68 at r6](https://reviewable.io/reviews/yiminlin-tri/drake/11#-N3RP8p43EYbD8KyjAHY:-N3RP8p5Cp8p0suAPXgT:boklolj) ([raw file](https://github.com/yiminlin-tri/drake/blob/4c0c3e9a46118acdf2815d81df299387a5cdd881/multibody/fem/mpm-dev/MPMTransfer.cc#L68)):*
> ```cpp
>     // Preallocate the indices of batches
>     for (int p = 0; p < num_particles; ++p) {
>         batch_idx_3D = CalcBatchIndex(particles->get_position(p), grid.get_h());
> ```

My previous comment is potentially misleading. It now appears to me that the the out of bound checking should happen before we sort the particles. Otherwise, this `batch_idx_3D` may be out of bound and subsequently `batch_indices[p]` could be negative in the next line, and we'd segfault in the following line.

We should be a bit more careful with the bound checking here to ensure we perform it exactly once before potentially reaching out of bound.


<!-- Sent from Reviewable.io -->

2022-05-31 23:20 UTC, xuchenhan-tri reviewed
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/11)* status: all files reviewed, 1 unresolved discussion (waiting on @yiminlin-tri)



<!-- Sent from Reviewable.io -->

2022-06-01 00:17 UTC, yiminlin-tri reviewed
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/11)* status: 3 of 6 files reviewed, 1 unresolved discussion (waiting on @xuchenhan-tri)

___
*[`multibody/fem/mpm-dev/MPMTransfer.cc` line 68 at r6](https://reviewable.io/reviews/yiminlin-tri/drake/11#-N3RP8p43EYbD8KyjAHY:-N3RQqLT0nh3rL9oiXsw:bq6yc6n) ([raw file](https://github.com/yiminlin-tri/drake/blob/4c0c3e9a46118acdf2815d81df299387a5cdd881/multibody/fem/mpm-dev/MPMTransfer.cc#L68)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

My previous comment is potentially misleading. It now appears to me that the the out of bound checking should happen before we sort the particles. Otherwise, this `batch_idx_3D` may be out of bound and subsequently `batch_indices[p]` could be negative in the next line, and we'd segfault in the following line.

We should be a bit more careful with the bound checking here to ensure we perform it exactly once before potentially reaching out of bound.
</blockquote></details>

@xuchenhan-tri I agree, thanks for pointing this out! I refactor bound checking into SortParticles() to avoid recalculation. And I rewrite the test.


<!-- Sent from Reviewable.io -->

2022-06-01 00:33 UTC, xuchenhan-tri approved these changes
Two closing thoughts:

1. Now that many of the transfer methods rely on the assumption that all particles are within bound, we should document them as such. I.e. Document that SortParticles() throws an exception if any particle is out of bound (and define what exactly we mean by out of bound and document that particles must be in bound for functions that do the splat without bound checking.
2. The new unit tests look fine to me, but IMO, it would be easier to keep the old tests as they are and simply add a new test where the throw condition is triggered and verify that with "EXPECT_THROW" or "DRAKE_EXPECT_THROWS_MESSAGE". 

> Reviewed 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/11#-:-N3RePYjB_8W-SgI948m:b-cmy9sn)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yiminlin-tri)



<!-- Sent from Reviewable.io -->

2022-06-01 00:36 UTC, yiminlin-tri reviewed
Sounds good, thanks for the suggestions! I will go on and merge and will put these into my next PR.

> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/11#-:-N3RgA1Y0mOkT6_wxay9:be0fwr2)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yiminlin-tri)



<!-- Sent from Reviewable.io -->

2022-06-01 00:36 UTC, merged