MPM Wall Boundary Condition
yiminlin-tri/drake pull request #14
Opened 2022-06-01 23:58 UTC by yiminlin-tri

2022-06-01 23:59 UTC, yiminlin-tri reviewed
+@xuchenhan-tri Thanks!

> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/14#-:-N3WhKfQ8PZWmQk8JOV2:b6w1hxi)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @xuchenhan-tri)



<!-- Sent from Reviewable.io -->

2022-06-02 00:30 UTC, xuchenhan-tri requested changes
I reviewed the non-test files. PTAL.

> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/14#-:-N3WoXKE4VXs5gtTkWvB:b-gcstdk)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @xuchenhan-tri and @yiminlin-tri)

___
*[`multibody/fem/mpm-dev/Grid.h` line 111 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/14#-N3Wm6WK9WNDDGb0M6gT:-N3Wm6WK9WNDDGb0M6gU:bmhr7br) ([raw file](https://github.com/yiminlin-tri/drake/blob/8e8399db112678eed6606d8ee4acb45b75ff0303/multibody/fem/mpm-dev/Grid.h#L111)):*
> ```objc
>     // condition.
>     void EnforceSlipBoundaryCondition();
>     void EnforceNoSlipBoundaryCondition();
> ```

Could we make the bc slightly more general? 

As in this PR, we can only specify bc on sides of the dense grids just when we are about to go out of bound.
It seems like it would be easy to extend this to allow boundary condition specified by a PosedHalfSpace (https://github.com/RobotLocomotion/drake/blob/master/geometry/proximity/posed_half_space.h) or even more to a generic level set. 

I'm worried that the simplified bc proposed in this PR won't be able to suit our needs for Hongkai's application.
___
*[`multibody/fem/mpm-dev/Grid.cc` line 183 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/14#-N3Wn_WIE6QcEzCYowJr:-N3Wn_WIE6QcEzCYowJs:b2l2uta) ([raw file](https://github.com/yiminlin-tri/drake/blob/8e8399db112678eed6606d8ee4acb45b75ff0303/multibody/fem/mpm-dev/Grid.cc#L183)):*
> ```cpp
>         for (int d = 0; d < 3; ++d) {
>             // If it is a wall, enforce slip BC
>             if ((index_3d(d) < bottom_corner_(d)+3)
> ```

This appears to be a recurring theme -- avoid magic constants. It makes the code harder to read. For example, someone may mistakenly take this 3 to mean the dimension of the world space.

I think I might know why you added the 3 here -- to leave a little cushion so that the particles don't fly out of bound. But I can only infer. It's so much better if you put it down in writing, whether through documentation or expressive variable names.
___
*[`multibody/fem/mpm-dev/Grid.cc` line 186 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/14#-N3WoKYJBxrIVyaHiVnT:-N3WoKYJBxrIVyaHiVnU:b-6olvdz) ([raw file](https://github.com/yiminlin-tri/drake/blob/8e8399db112678eed6606d8ee4acb45b75ff0303/multibody/fem/mpm-dev/Grid.cc#L186)):*
> ```cpp
>              || (index_3d(d) >=
>                             bottom_corner_(d)+num_gridpt_1D_(d)-3)) {
>                 velocities_[index_flat](d) = 0.0;
> ```

We'd probably want some sort of friction behavior at the boundary. As it stands right now, all bc are frictionless.


<!-- Sent from Reviewable.io -->

2022-06-02 02:42 UTC, yiminlin-tri reviewed
Thanks! Just updated with some comments.

> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/14#-:-N3XHZHK-2w3LS_36AWw:bn3j2t8)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @xuchenhan-tri)

___
*[`multibody/fem/mpm-dev/Grid.h` line 111 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/14#-N3Wm6WK9WNDDGb0M6gT:-N3XGp0_0MKzVMev4H8E:b77fxq6) ([raw file](https://github.com/yiminlin-tri/drake/blob/8e8399db112678eed6606d8ee4acb45b75ff0303/multibody/fem/mpm-dev/Grid.h#L111)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Could we make the bc slightly more general? 

As in this PR, we can only specify bc on sides of the dense grids just when we are about to go out of bound.
It seems like it would be easy to extend this to allow boundary condition specified by a PosedHalfSpace (https://github.com/RobotLocomotion/drake/blob/master/geometry/proximity/posed_half_space.h) or even more to a generic level set. 

I'm worried that the simplified bc proposed in this PR won't be able to suit our needs for Hongkai's application.
</blockquote></details>

Sure, I just modified by taking a posed half space as argument. Then I imagine in the driver, or a separate geometry class, we can maintain an list of posed half space to indicate the boundary. 
___
*[`multibody/fem/mpm-dev/Grid.cc` line 183 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/14#-N3Wn_WIE6QcEzCYowJr:-N3WqmEu6Z-xOL_fAoqu:bb6un1j) ([raw file](https://github.com/yiminlin-tri/drake/blob/8e8399db112678eed6606d8ee4acb45b75ff0303/multibody/fem/mpm-dev/Grid.cc#L183)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

This appears to be a recurring theme -- avoid magic constants. It makes the code harder to read. For example, someone may mistakenly take this 3 to mean the dimension of the world space.

I think I might know why you added the 3 here -- to leave a little cushion so that the particles don't fly out of bound. But I can only infer. It's so much better if you put it down in writing, whether through documentation or expressive variable names.
</blockquote></details>

Done
___
*[`multibody/fem/mpm-dev/Grid.cc` line 186 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/14#-N3WoKYJBxrIVyaHiVnT:-N3WrAQCCn-7IUnykT_O:b-jgk39r) ([raw file](https://github.com/yiminlin-tri/drake/blob/8e8399db112678eed6606d8ee4acb45b75ff0303/multibody/fem/mpm-dev/Grid.cc#L186)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

We'd probably want some sort of friction behavior at the boundary. As it stands right now, all bc are frictionless.
</blockquote></details>

Sure, sounds good. What is the usual way to define friction? I saw v = v_t + μ v_n v_t/‖v_t‖ in the course note, and this is what I updated. Correct me if I am wrong, I also imagine the no-slip BC is the most friction we can get?


<!-- Sent from Reviewable.io -->

2022-06-02 02:45 UTC, yiminlin-tri reviewed
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/14)* status: 0 of 4 files reviewed, 6 unresolved discussions (waiting on @xuchenhan-tri)

___
*[`multibody/fem/mpm-dev/Grid.cc` line 186 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/14#-N3XI1Al8q-ARJX2c6K2:-N3XI1Al8q-ARJX2c6K3:b-2vbn0u) ([raw file](https://github.com/yiminlin-tri/drake/blob/3199f980af515e41cb6602b73138813a2fb2412b/multibody/fem/mpm-dev/Grid.cc#L186)):*
> ```cpp
>         // boundary space
>         if (boundary_space.CalcSignedDistance(positions_[index_flat])
>                                                                 >= -2.0*h_) {
> ```

This 2.0*h is pretty arbitrary. 1.5h should still work (particles would not go out of bound). Shall we pass in an additional int thickness argument to control the thickness of boundary? Or this parameter should really be fixed.
___
*[`multibody/fem/mpm-dev/Grid.cc` line 192 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/14#-N3XIK2W3dpGqSxSjH6D:-N3XIK2W3dpGqSxSjH6E:b-m0heyv) ([raw file](https://github.com/yiminlin-tri/drake/blob/3199f980af515e41cb6602b73138813a2fb2412b/multibody/fem/mpm-dev/Grid.cc#L192)):*
> ```cpp
>             Vector3<double> vt = v_i - vn*normal;  // Tangential velocity
>             velocities_[index_flat] = vt
>                                     + friction_coefficient*vn*vt.normalized();
> ```

I didn't find a good reference for the boundary enforcement with friction, maybe you can point me to one? Thanks!
___
*[`multibody/fem/mpm-dev/test/Grid_test.cc` line 286 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/14#-N3XHlQNCk0tbqOSSQw6:-N3XHlQNCk0tbqOSSQw7:b-ryry3l) ([raw file](https://github.com/yiminlin-tri/drake/blob/3199f980af515e41cb6602b73138813a2fb2412b/multibody/fem/mpm-dev/test/Grid_test.cc#L286)):*
> ```cpp
> }
> 
> GTEST_TEST(GridClassTest, TestWallBoundaryCondition) {
> ```

I will work on a more general case (a hyperplane not parallel to xyz plane) tomorrow


<!-- Sent from Reviewable.io -->

2022-06-04 17:32 UTC, xuchenhan-tri requested changes
I added a reference for frictional BC, PTAL.

> Reviewed 3 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/14#-:-N3jlR-g8qSVGQezKQzU:bbqi9i)* status: 3 of 4 files reviewed, 5 unresolved discussions (waiting on @xuchenhan-tri and @yiminlin-tri)

___
*[`multibody/fem/mpm-dev/Grid.h` line 112 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/14#-N3jiCn_CxJHKsHLr8uX:-N3jiCn_CxJHKsHLr8uY:b-4qp94b) ([raw file](https://github.com/yiminlin-tri/drake/blob/3199f980af515e41cb6602b73138813a2fb2412b/multibody/fem/mpm-dev/Grid.h#L112)):*
> ```objc
>     // is the tangential velocity, v_n = v \dot n, n the outward normal of the
>     // halfplane, and \mu the friction_coefficient
>     void EnforceWallBoundaryCondition(double friction_coefficient,
> ```

It seems like it would be very natural to wrap the friction coefficient and the posed half space into a data structure that encapsulates "boundary condition". Then grid class can simply have a "EnforceDirichletBoundaryCondition" function that takes a boundary condition class and enforce whatever BC the "boundary condition" argument  specifies.



_Suggestion:_
```objc
    void EnforceBoundaryCondition(BoundaryCondition bc);
```
___
*[`multibody/fem/mpm-dev/Grid.cc` line 186 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/14#-N3WoKYJBxrIVyaHiVnT:-N3jkksv3hhHIaLw_4Y9:bvu05ji) ([raw file](https://github.com/yiminlin-tri/drake/blob/8e8399db112678eed6606d8ee4acb45b75ff0303/multibody/fem/mpm-dev/Grid.cc#L186)):*
> I saw v = v_t + μ v_n v_t/‖v_t‖ in the course note, ...

No, this is not the right way to do friction. We are trying to mimic the coulomb law of friction -- the friction force is <= the friction coefficient times the normal force. I realized that I haven't provided a good reference for how to implement frictional BC. I added a reference in another thread. PTAL.
___
*[`multibody/fem/mpm-dev/Grid.cc` line 186 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/14#-N3XI1Al8q-ARJX2c6K2:-N3jiUwV10jBxc-5piHs:b-3emo67) ([raw file](https://github.com/yiminlin-tri/drake/blob/3199f980af515e41cb6602b73138813a2fb2412b/multibody/fem/mpm-dev/Grid.cc#L186)):*
<details><summary><i>Previously, yiminlin-tri wrote…</i></summary><blockquote>

This 2.0*h is pretty arbitrary. 1.5h should still work (particles would not go out of bound). Shall we pass in an additional int thickness argument to control the thickness of boundary? Or this parameter should really be fixed.
</blockquote></details>

I don't think there should be any thickness here -- The bc is applied if and only if the grid node falls within the half space.

IMO, we shouldn't be trying to play tricks to help particles not go out of bound for 2 reasons. 

1. We made an effort to throw a useful error message when particles go out of bound, and with BC, users have the tool to add BC to prevent going out of bound if needed. Or they could simply make a bigger grid.
2. We won't be sticking with uniform dense grid forever. To make MPM useful at all, we need to eventually switch to an adaptive grid and this problem goes away.
___
*[`multibody/fem/mpm-dev/Grid.cc` line 192 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/14#-N3XIK2W3dpGqSxSjH6D:-N3jkGn6-CDFFgml19M-:b-gix8p4) ([raw file](https://github.com/yiminlin-tri/drake/blob/3199f980af515e41cb6602b73138813a2fb2412b/multibody/fem/mpm-dev/Grid.cc#L192)):*
<details><summary><i>Previously, yiminlin-tri wrote…</i></summary><blockquote>

I didn't find a good reference for the boundary enforcement with friction, maybe you can point me to one? Thanks!
</blockquote></details>

See section 8: https://www.math.ucla.edu/~jteran/papers/KGPSJT16.pdf


<!-- Sent from Reviewable.io -->

2022-06-07 01:29 UTC, yiminlin-tri reviewed
+@xuchenhan-tri Major changes - Thanks!

> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/14#-:-N3vlqK9-KZhN9LHA8vS:bjocvu7)* status: 0 of 7 files reviewed, 4 unresolved discussions (waiting on @xuchenhan-tri)

___
*[`multibody/fem/mpm-dev/Grid.h` line 112 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/14#-N3jiCn_CxJHKsHLr8uX:-N3vllt06Lk9QZhkXlk2:b-896fix) ([raw file](https://github.com/yiminlin-tri/drake/blob/3199f980af515e41cb6602b73138813a2fb2412b/multibody/fem/mpm-dev/Grid.h#L112)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

It seems like it would be very natural to wrap the friction coefficient and the posed half space into a data structure that encapsulates "boundary condition". Then grid class can simply have a "EnforceDirichletBoundaryCondition" function that takes a boundary condition class and enforce whatever BC the "boundary condition" argument  specifies.
</blockquote></details>

Done.
___
*[`multibody/fem/mpm-dev/Grid.cc` line 186 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/14#-N3WoKYJBxrIVyaHiVnT:-N3vlne25c6rXLh09EhA:b-896fix) ([raw file](https://github.com/yiminlin-tri/drake/blob/8e8399db112678eed6606d8ee4acb45b75ff0303/multibody/fem/mpm-dev/Grid.cc#L186)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

> I saw v = v_t + μ v_n v_t/‖v_t‖ in the course note, ...

No, this is not the right way to do friction. We are trying to mimic the coulomb law of friction -- the friction force is <= the friction coefficient times the normal force. I realized that I haven't provided a good reference for how to implement frictional BC. I added a reference in another thread. PTAL.
</blockquote></details>

Done.
___
*[`multibody/fem/mpm-dev/Grid.cc` line 186 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/14#-N3XI1Al8q-ARJX2c6K2:-N3vlpcp3hOXV22Iu1Qi:b-896fix) ([raw file](https://github.com/yiminlin-tri/drake/blob/3199f980af515e41cb6602b73138813a2fb2412b/multibody/fem/mpm-dev/Grid.cc#L186)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I don't think there should be any thickness here -- The bc is applied if and only if the grid node falls within the half space.

IMO, we shouldn't be trying to play tricks to help particles not go out of bound for 2 reasons. 

1. We made an effort to throw a useful error message when particles go out of bound, and with BC, users have the tool to add BC to prevent going out of bound if needed. Or they could simply make a bigger grid.
2. We won't be sticking with uniform dense grid forever. To make MPM useful at all, we need to eventually switch to an adaptive grid and this problem goes away.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-06-07 01:50 UTC, xuchenhan-tri requested changes
Here's a partial review with some superfluous things before I sign off for the day. So far so good! Looks like a big improvement from before to me!

> Reviewed 2 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/14#-:-N3vqQzgAhEe1s0VfAal:b-z4nx03)* status: 2 of 7 files reviewed, 6 unresolved discussions (waiting on @xuchenhan-tri and @yiminlin-tri)

___
*[`multibody/fem/mpm-dev/BoundaryCondition.h` line 18 at r3](https://reviewable.io/reviews/yiminlin-tri/drake/14#-N3voJSF9lNumvLm-nU1:-N3voJSF9lNumvLm-nU2:b-19hr3k) ([raw file](https://github.com/yiminlin-tri/drake/blob/06e38e918236159c4e2c043774ad16e70707ca7c/multibody/fem/mpm-dev/BoundaryCondition.h#L18)):*
> ```objc
> // planes are outside the computational domain. We store the friction
> // coefficients of each boundaries.
> // TODO(yiminlin.tri): Only support frictional wall boundary condition
> ```

nit Looks like this TODO is done?
___
*[`multibody/fem/mpm-dev/BoundaryCondition.h` line 43 at r3](https://reviewable.io/reviews/yiminlin-tri/drake/14#-N3vo6IL5vl22nmYT1WU:-N3vo6IMCZ9YQ3NP06F1:b-5w5awo) ([raw file](https://github.com/yiminlin-tri/drake/blob/06e38e918236159c4e2c043774ad16e70707ca7c/multibody/fem/mpm-dev/BoundaryCondition.h#L43)):*
> ```objc
>     // the wall.
>     // If \|vt\| <= mu \|j\|/m, v_new = 0.0
>     // Otherwise              , v_new = vt - mu\|j\|/m * t, t - tangential
> ```

FYI, https://www.unicodeit.net/ converts latex to unicode for better readabilities. Optional of course.
___
*[`multibody/fem/mpm-dev/BoundaryCondition.h` line 47 at r3](https://reviewable.io/reviews/yiminlin-tri/drake/14#-N3vok1u9-J_BxfixKQc:-N3vok1u9-J_BxfixKQd:b-34mkvn) ([raw file](https://github.com/yiminlin-tri/drake/blob/06e38e918236159c4e2c043774ad16e70707ca7c/multibody/fem/mpm-dev/BoundaryCondition.h#L47)):*
> ```objc
>     // Note that we use \|j\|/m = \|vn\| in the implementation
>     // Then we overwrite the passed in velocity with v_new
>     void UpdateFrictionalWallVelocity(const Vector3<double>& position,
> ```

nit can I propose an alternative function name -- "ApplyBoundaryConditions"?
___
*[`multibody/fem/mpm-dev/BoundaryCondition.cc` line 8 at r3](https://reviewable.io/reviews/yiminlin-tri/drake/14#-N3vp0si95JGsirl__15:-N3vp0si95JGsirl__16:b-vvaemd) ([raw file](https://github.com/yiminlin-tri/drake/blob/06e38e918236159c4e2c043774ad16e70707ca7c/multibody/fem/mpm-dev/BoundaryCondition.cc#L8)):*
> ```cpp
> 
> BoundaryCondition::BoundaryCondition(
>             const std::vector<Boundary>& boundaries) {
> ```

BTW, you could do 

```
BoundaryCondition::BoundaryCondition(
            std::vector<Boundary> boundaries): boundaries_(std::move(boundaries)){}
```

to take advantage of move semantics. If you are interested, here's a reference https://moodle.ufsc.br/pluginfile.php/2377667/mod_resource/content/0/Effective_Modern_C__.pdf. See item 41.
___
*[`multibody/fem/mpm-dev/BoundaryCondition.cc` line 29 at r3](https://reviewable.io/reviews/yiminlin-tri/drake/14#-N3vpGre3BGznW9nvt-k:-N3vpGre3BGznW9nvt-l:b-jp3jq2) ([raw file](https://github.com/yiminlin-tri/drake/blob/06e38e918236159c4e2c043774ad16e70707ca7c/multibody/fem/mpm-dev/BoundaryCondition.cc#L29)):*
> ```cpp
> void BoundaryCondition::AddBoundary(const
>                                     BoundaryCondition::Boundary& boundary) {
>     boundaries_.emplace_back(boundary);
> ```

Btw, here you could do 
```
void BoundaryCondition::AddBoundary(BoundaryCondition::Boundary boundary) {
    boundaries_.emplace_back(std::move(boundary));
}
```

  
 


<!-- Sent from Reviewable.io -->

2022-06-07 04:26 UTC, xuchenhan-tri requested changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> with a few comments. PTAL.

> Reviewed 5 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/14#-:-N3wPWdl8f9xgYrmNygw:b-hw9ek9)* status: all files reviewed, 15 unresolved discussions (waiting on @xuchenhan-tri and @yiminlin-tri)

___
*[`multibody/fem/mpm-dev/BoundaryCondition.h` line 15 at r3](https://reviewable.io/reviews/yiminlin-tri/drake/14#-N3wMOlCAZLc63QM5l3s:-N3wMOlCAZLc63QM5l3t:b-52v5s2) ([raw file](https://github.com/yiminlin-tri/drake/blob/06e38e918236159c4e2c043774ad16e70707ca7c/multibody/fem/mpm-dev/BoundaryCondition.h#L15)):*
> ```objc
> // the domain. The boundaries in the MPM solver are represented as
> // PosedHalfSpace, whose normals point from the interior to the exterior of our
> // computational domain. Points with nonnegative distances to the boundary half
> ```

The normals should have nothing to do with the computation domain.



_Code quote:_
```objc
computational domain.
```
___
*[`multibody/fem/mpm-dev/BoundaryCondition.h` line 29 at r3](https://reviewable.io/reviews/yiminlin-tri/drake/14#-N3wKlT--64AYMksBuMu:-N3wKlT--64AYMksBuMv:b-k0paft) ([raw file](https://github.com/yiminlin-tri/drake/blob/06e38e918236159c4e2c043774ad16e70707ca7c/multibody/fem/mpm-dev/BoundaryCondition.h#L29)):*
> ```objc
>     explicit BoundaryCondition(const std::vector<Boundary>& boundaries);
> 
>     int get_num_boundary() const;
> ```

nit `get_num_boundary`->`get_num_boundaries`
___
*[`multibody/fem/mpm-dev/BoundaryCondition.h` line 42 at r3](https://reviewable.io/reviews/yiminlin-tri/drake/14#-N3wIXvHC4KySgeOElr0:-N3wIXvHC4KySgeOElr1:b-cb4py1) ([raw file](https://github.com/yiminlin-tri/drake/blob/06e38e918236159c4e2c043774ad16e70707ca7c/multibody/fem/mpm-dev/BoundaryCondition.h#L42)):*
> ```objc
>     // imposed is at most \mu \|j\|, where \mu is the friction coefficient of
>     // the wall.
>     // If \|vt\| <= mu \|j\|/m, v_new = 0.0
> ```

nit ‖j‖/m is just ‖vₙ‖
___
*[`multibody/fem/mpm-dev/BoundaryCondition.h` line 46 at r3](https://reviewable.io/reviews/yiminlin-tri/drake/14#-N3wKvFPA-bsRnhyRjaJ:-N3wKvFPA-bsRnhyRjaK:byhdv9t) ([raw file](https://github.com/yiminlin-tri/drake/blob/06e38e918236159c4e2c043774ad16e70707ca7c/multibody/fem/mpm-dev/BoundaryCondition.h#L46)):*
> ```objc
>     //                                                          direction
>     // Note that we use \|j\|/m = \|vn\| in the implementation
>     // Then we overwrite the passed in velocity with v_new
> ```

The documentation should mention how the bc is handled when a single position is under multiple bc. It should probably also come with a TODO for us to revisit it in the future.
___
*[`multibody/fem/mpm-dev/BoundaryCondition.h` line 47 at r3](https://reviewable.io/reviews/yiminlin-tri/drake/14#-N3vok1u9-J_BxfixKQc:-N3wJwIf7KY9zmiDApsM:b5yjf1a) ([raw file](https://github.com/yiminlin-tri/drake/blob/06e38e918236159c4e2c043774ad16e70707ca7c/multibody/fem/mpm-dev/BoundaryCondition.h#L47)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit can I propose an alternative function name -- "ApplyBoundaryConditions"?
</blockquote></details>

Or simply `Apply`? At call sites, this would most often read `boundary_condition.Apply(position, &velocity);`.
___
*[`multibody/fem/mpm-dev/BoundaryCondition.cc` line 39 at r3](https://reviewable.io/reviews/yiminlin-tri/drake/14#-N3wNQB0AHiR4aBTzhEC:-N3wNQB0AHiR4aBTzhED:b-dbx267) ([raw file](https://github.com/yiminlin-tri/drake/blob/06e38e918236159c4e2c043774ad16e70707ca7c/multibody/fem/mpm-dev/BoundaryCondition.cc#L39)):*
> ```cpp
>         // If the grid point is on/in the boundary, enforce the frictional wall
>         // boundary condition
>         if (boundary.boundary_space.CalcSignedDistance(position) >= 0) {
> ```

This doesn't seem right. When the distance is >0, the point is outside of the halfspace, and no BC should be applied.

I think I finally understood what you meant in your slack messages. The convention we use is that if signed distance > 0, then the point is "outside" of the wall.



_Suggestion:_
```cpp
if (boundary.boundary_space.CalcSignedDistance(position) <= 0) {
```
___
*[`multibody/fem/mpm-dev/BoundaryCondition.cc` line 46 at r3](https://reviewable.io/reviews/yiminlin-tri/drake/14#-N3wMpEO3YpiUoOtI2A2:-N3wMpEO3YpiUoOtI2A3:b-kmd1d0) ([raw file](https://github.com/yiminlin-tri/drake/blob/06e38e918236159c4e2c043774ad16e70707ca7c/multibody/fem/mpm-dev/BoundaryCondition.cc#L46)):*
> ```cpp
>             Vector3<double> vt = *velocity - vn;
>             // Normal and tangential speed
>             double v_n = vn.norm();
> ```

nit, using both v_n and vn is quite confusing. Can we call this something like `vn_norm` instead?
___
*[`multibody/fem/mpm-dev/BoundaryCondition.cc` line 54 at r3](https://reviewable.io/reviews/yiminlin-tri/drake/14#-N3wN0mu2dNVnRCQ-Swo:-N3wN0mu2dNVnRCQ-Swp:bsfn2xk) ([raw file](https://github.com/yiminlin-tri/drake/blob/06e38e918236159c4e2c043774ad16e70707ca7c/multibody/fem/mpm-dev/BoundaryCondition.cc#L54)):*
> ```cpp
>                 *velocity = Vector3<double>::Zero();
>             } else {
>                 *velocity = vt - boundary.friction_coefficient*v_n*vt/v_t;
> ```

what if v_t == 0 here? There should be a unit test covering this.
___
*[`multibody/fem/mpm-dev/Grid.h` line 109 at r3](https://reviewable.io/reviews/yiminlin-tri/drake/14#-N3vy-zD2g0PDyF81k1O:-N3vy-zD2g0PDyF81k1P:b-e635yk) ([raw file](https://github.com/yiminlin-tri/drake/blob/06e38e918236159c4e2c043774ad16e70707ca7c/multibody/fem/mpm-dev/Grid.h#L109)):*
> ```objc
>     // Dirichlet boundary conditions given by boundary_condition to all grid
>     // points in the boundary half- spaces.
>     void EnforceBoundaryCondition(BoundaryCondition boundary_condition);
> ```

nit, can we pass in a const reference instead?
___
*[`multibody/fem/mpm-dev/Grid.cc` line 178 at r3](https://reviewable.io/reviews/yiminlin-tri/drake/14#-N3vxvkF4Nt3_hOTsmkj:-N3vxvkF4Nt3_hOTsmkk:b-e635yk) ([raw file](https://github.com/yiminlin-tri/drake/blob/06e38e918236159c4e2c043774ad16e70707ca7c/multibody/fem/mpm-dev/Grid.cc#L178)):*
> ```cpp
> }
> 
> void Grid::EnforceBoundaryCondition(BoundaryCondition boundary_condition) {
> ```

nit, can we pass in a const reference instead?
___
*[`multibody/fem/mpm-dev/Grid.cc` line 179 at r3](https://reviewable.io/reviews/yiminlin-tri/drake/14#-N3wJpnm6y404jlTomCX:-N3wJpnm6y404jlTomCY:b-fbempr) ([raw file](https://github.com/yiminlin-tri/drake/blob/06e38e918236159c4e2c043774ad16e70707ca7c/multibody/fem/mpm-dev/Grid.cc#L179)):*
> ```cpp
> 
> void Grid::EnforceBoundaryCondition(BoundaryCondition boundary_condition) {
>     // For all grid points, enfroce frictional wall boundary condition
> ```

nit enfroce->enforce
___
*[`multibody/fem/mpm-dev/test/BoundaryCondition_test.cc` line 1 at r3](https://reviewable.io/reviews/yiminlin-tri/drake/14#-N3wOsM68vJYavgf9Z54:-N3wOsM7CVXC0UMKQQld:bjzut3a) ([raw file](https://github.com/yiminlin-tri/drake/blob/06e38e918236159c4e2c043774ad16e70707ca7c/multibody/fem/mpm-dev/test/BoundaryCondition_test.cc#L1)):*
> ```cpp
> #include "drake/multibody/fem/mpm-dev/BoundaryCondition.h"
> ```

nit, looks like all the normals in the unit tests need to be flipped.
___
*[`multibody/fem/mpm-dev/test/BoundaryCondition_test.cc` line 97 at r3](https://reviewable.io/reviews/yiminlin-tri/drake/14#-N3wOM_I5cVeIW2aXgIp:-N3wOM_I5cVeIW2aXgIq:brwu0zd) ([raw file](https://github.com/yiminlin-tri/drake/blob/06e38e918236159c4e2c043774ad16e70707ca7c/multibody/fem/mpm-dev/test/BoundaryCondition_test.cc#L97)):*
> ```cpp
> 
>     // Next consider a point on the boundary half plane. The velocity is in not
>     // the normal direction, but the impulse, so friction, is so large that only
> ```

This sentence reads werid. Do you mean "the normal impulse and the consequent frictional force is so large that ..."



_Co [...]

2022-06-07 18:18 UTC, yiminlin-tri reviewed
+@xuchenhan-tri Fixed. Thanks!

> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/14#-:-N3zN3RZ44xCAA488VIh:b-oprljw)* status: all files reviewed, 6 unresolved discussions (waiting on @xuchenhan-tri)

___
*[`multibody/fem/mpm-dev/BoundaryCondition.h` line 15 at r3](https://reviewable.io/reviews/yiminlin-tri/drake/14#-N3wMOlCAZLc63QM5l3s:-N3ysur18PxcHu_GUORh:bb6un1j) ([raw file](https://github.com/yiminlin-tri/drake/blob/06e38e918236159c4e2c043774ad16e70707ca7c/multibody/fem/mpm-dev/BoundaryCondition.h#L15)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

The normals should have nothing to do with the computation domain.
</blockquote></details>

Done
___
*[`multibody/fem/mpm-dev/BoundaryCondition.h` line 18 at r3](https://reviewable.io/reviews/yiminlin-tri/drake/14#-N3voJSF9lNumvLm-nU1:-N3ylYp42H6LvDlOIYpA:b-jnrvs7) ([raw file](https://github.com/yiminlin-tri/drake/blob/06e38e918236159c4e2c043774ad16e70707ca7c/multibody/fem/mpm-dev/BoundaryCondition.h#L18)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit Looks like this TODO is done?
</blockquote></details>

Done and removed. What I mean is maybe we can add additional BC (reflective, inflow/outflow) in this class as needed in the future? But we can revisit when needed.
___
*[`multibody/fem/mpm-dev/BoundaryCondition.h` line 29 at r3](https://reviewable.io/reviews/yiminlin-tri/drake/14#-N3wKlT--64AYMksBuMu:-N3ym0fK8pajzKJYH3gj:bb6un1j) ([raw file](https://github.com/yiminlin-tri/drake/blob/06e38e918236159c4e2c043774ad16e70707ca7c/multibody/fem/mpm-dev/BoundaryCondition.h#L29)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit `get_num_boundary`->`get_num_boundaries`
</blockquote></details>

Done
___
*[`multibody/fem/mpm-dev/BoundaryCondition.h` line 42 at r3](https://reviewable.io/reviews/yiminlin-tri/drake/14#-N3wIXvHC4KySgeOElr0:-N3ymYXlEj4cpEd4NHkI:bb6un1j) ([raw file](https://github.com/yiminlin-tri/drake/blob/06e38e918236159c4e2c043774ad16e70707ca7c/multibody/fem/mpm-dev/BoundaryCondition.h#L42)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit ‖j‖/m is just ‖vₙ‖
</blockquote></details>

Done
___
*[`multibody/fem/mpm-dev/BoundaryCondition.h` line 43 at r3](https://reviewable.io/reviews/yiminlin-tri/drake/14#-N3vo6IL5vl22nmYT1WU:-N3ynXea9QiGXT6cluTX:bb6un1j) ([raw file](https://github.com/yiminlin-tri/drake/blob/06e38e918236159c4e2c043774ad16e70707ca7c/multibody/fem/mpm-dev/BoundaryCondition.h#L43)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

FYI, https://www.unicodeit.net/ converts latex to unicode for better readabilities. Optional of course.
</blockquote></details>

Done
___
*[`multibody/fem/mpm-dev/BoundaryCondition.h` line 46 at r3](https://reviewable.io/reviews/yiminlin-tri/drake/14#-N3wKvFPA-bsRnhyRjaJ:-N3ypBbBD-bwbJ5dicU-:bb6un1j) ([raw file](https://github.com/yiminlin-tri/drake/blob/06e38e918236159c4e2c043774ad16e70707ca7c/multibody/fem/mpm-dev/BoundaryCondition.h#L46)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

The documentation should mention how the bc is handled when a single position is under multiple bc. It should probably also come with a TODO for us to revisit it in the future.
</blockquote></details>

Done
___
*[`multibody/fem/mpm-dev/BoundaryCondition.h` line 47 at r3](https://reviewable.io/reviews/yiminlin-tri/drake/14#-N3vok1u9-J_BxfixKQc:-N3ypKsj4cjAWUwwhsir:bb6un1j) ([raw file](https://github.com/yiminlin-tri/drake/blob/06e38e918236159c4e2c043774ad16e70707ca7c/multibody/fem/mpm-dev/BoundaryCondition.h#L47)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Or simply `Apply`? At call sites, this would most often read `boundary_condition.Apply(position, &velocity);`.
</blockquote></details>

Done
___
*[`multibody/fem/mpm-dev/BoundaryCondition.cc` line 8 at r3](https://reviewable.io/reviews/yiminlin-tri/drake/14#-N3vp0si95JGsirl__15:-N3yqKje8Avs1s4q5yJH:b-ywap4y) ([raw file](https://github.com/yiminlin-tri/drake/blob/06e38e918236159c4e2c043774ad16e70707ca7c/multibody/fem/mpm-dev/BoundaryCondition.cc#L8)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, you could do 

```
BoundaryCondition::BoundaryCondition(
            std::vector<Boundary> boundaries): boundaries_(std::move(boundaries)){}
```

to take advantage of move semantics. If you are interested, here's a reference https://moodle.ufsc.br/pluginfile.php/2377667/mod_resource/content/0/Effective_Modern_C__.pdf. See item 41.

</blockquote></details>

Done. Thanks! I learn something new. And the book also looks neat. Thanks!
___
*[`multibody/fem/mpm-dev/BoundaryCondition.cc` line 29 at r3](https://reviewable.io/reviews/yiminlin-tri/drake/14#-N3vpGre3BGznW9nvt-k:-N3ys0tO8f4AkaP4irCS:bb6un1j) ([raw file](https://github.com/yiminlin-tri/drake/blob/06e38e918236159c4e2c043774ad16e70707ca7c/multibody/fem/mpm-dev/BoundaryCondition.cc#L29)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Btw, here you could do 
```
void BoundaryCondition::AddBoundary(BoundaryCondition::Boundary boundary) {
    boundaries_.emplace_back(std::move(boundary));
}
```

  
 

</blockquote></details>

Done
___
*[`multibody/fem/mpm-dev/BoundaryCondition.cc` line 39 at r3](https://reviewable.io/reviews/yiminlin-tri/drake/14#-N3wNQB0AHiR4aBTzhEC:-N3zMHcK6rd4B6cvyHz3:bt1koky) ([raw file](https://github.com/yiminlin-tri/drake/blob/06e38e918236159c4e2c043774ad16e70707ca7c/multibody/fem/mpm-dev/BoundaryCondition.cc#L39)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

This doesn't seem right. When the distance is >0, the point is outside of the halfspace, and no BC should be applied.

I think I finally understood what you meant in your slack messages. The convention we use is that if signed distance > 0, then the point is "outside" of the wall.
</blockquote></details>

Done. Thanks for the explanation! I finally understand now.
___
*[`multibody/fem/mpm-dev/BoundaryCondition.cc` line 46 at r3](https://reviewable.io/reviews/yiminlin-tri/drake/14#-N3wMpEO3YpiUoOtI2A2:-N3z74yO7Dyhowug7Cch:bb6un1j) ([raw file](https://github.com/yiminlin-tri/drake/blob/06e38e918236159c4e2c043774ad16e70707ca7c/multibody/fem/mpm-dev/BoundaryCondition.cc#L46)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, using both v_n and vn is quite confusing. Can we call this something like `vn_norm` instead?
</blockquote></details>

Done
___
*[`multibody/fem/mpm-dev/BoundaryCondition.cc` line 54 at r3](https://reviewable.io/reviews/yiminlin-tri/drake/14#-N3wN0mu2dNVnRCQ-Swo:-N3z7HiXAcfml7MmThjg:b7w5k54) ([raw file](https://github.com/yiminlin-tri/drake/blob/06e38e918236159c4e2c043774ad16e70707ca7c/multibody/fem/mpm-dev/BoundaryCondition.cc#L54)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

what if v_t == 0 here? There should be a unit test covering this.
</blockquote></details>

if v_t (or vt_norm) == 0, v_t <= friction_coeff*vn_norm, so *velocity = 0. I think line 88-94 of BoundaryCondition_test.cc covers this case?
___
*[`multibody/fem/mpm-dev/Grid.h` line 109 at r3](https://reviewable.io/reviews/yiminlin-tri/drake/14#-N3vy-zD2g0PDyF81k1O:-N3ys776BysjN7C5iiEx:bb6un1j) ([raw file](https://github.com/yiminlin-tri/drake/blob/06e38e918236159c4e2c043774ad16e70707ca7c/multibody/fem/mpm-dev/Grid.h#L109)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, can we pass in a const reference instead?
</blockquote></details>

Done
___
*[`multibody/fem/mpm-dev/Grid.cc` line 178 at r3](https://reviewable.io/reviews/yiminlin-tri/drake/14#-N3vxvkF4Nt3_hOTsmkj:-N3ynpgS3UwUd-gBwzvz:bb6un1j) ([raw file](https://github.com/yiminlin-tri/drake/blob/06e38e918236159c4e2c043774ad16e70707ca7c/multibody/fem/mpm-dev/Grid.cc#L178)):*
 [...]

2022-06-07 18:33 UTC, xuchenhan-tri requested changes
<img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/> 

> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/14#-:-N3zRQ90Aqz9AhQsvlD4:b-uwkowd)* status: all files reviewed, 2 unresolved discussions (waiting on @yiminlin-tri)

___
*[`multibody/fem/mpm-dev/BoundaryCondition.cc` line 54 at r3](https://reviewable.io/reviews/yiminlin-tri/drake/14#-N3wN0mu2dNVnRCQ-Swo:-N3zQneh2Ybml8sBvYiC:bzh79yp) ([raw file](https://github.com/yiminlin-tri/drake/blob/06e38e918236159c4e2c043774ad16e70707ca7c/multibody/fem/mpm-dev/BoundaryCondition.cc#L54)):*
<details><summary><i>Previously, yiminlin-tri wrote…</i></summary><blockquote>

if v_t (or vt_norm) == 0, v_t <= friction_coeff*vn_norm, so *velocity = 0. I think line 88-94 of BoundaryCondition_test.cc covers this case?
</blockquote></details>

You are right! I missed the subtleties. Retracted.

Perhaps a comment here to remind future readers?
___
*[`multibody/fem/mpm-dev/test/Grid_test.cc` line 286 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/14#-N3XHlQNCk0tbqOSSQw6:-N3zRLYe8Z18_qf6arFN:b-u2cjs) ([raw file](https://github.com/yiminlin-tri/drake/blob/3199f980af515e41cb6602b73138813a2fb2412b/multibody/fem/mpm-dev/test/Grid_test.cc#L286)):*
<details><summary><i>Previously, yiminlin-tri wrote…</i></summary><blockquote>

I will work on a more general case (a hyperplane not parallel to xyz plane) tomorrow
</blockquote></details>

Looks like this is done via the test below.


<!-- Sent from Reviewable.io -->

2022-06-07 18:39 UTC, yiminlin-tri reviewed
Thanks!

> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/14#-:-N3zSiJR7GpKqQI3MOYh:b-ucfknh)* status: 6 of 7 files reviewed, all discussions resolved (waiting on @xuchenhan-tri)

___
*[`multibody/fem/mpm-dev/BoundaryCondition.cc` line 54 at r3](https://reviewable.io/reviews/yiminlin-tri/drake/14#-N3wN0mu2dNVnRCQ-Swo:-N3zST1ABl1lUo1bswoj:bb6un1j) ([raw file](https://github.com/yiminlin-tri/drake/blob/06e38e918236159c4e2c043774ad16e70707ca7c/multibody/fem/mpm-dev/BoundaryCondition.cc#L54)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

You are right! I missed the subtleties. Retracted.

Perhaps a comment here to remind future readers?
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2022-06-07 18:40 UTC, xuchenhan-tri approved these changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/14)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yiminlin-tri)



<!-- Sent from Reviewable.io -->

2022-06-07 18:40 UTC, merged