MPM Driver Class
yiminlin-tri/drake pull request #16
Opened 2022-06-08 02:03 UTC by yiminlin-tri

2022-06-08 02:08 UTC, yiminlin-tri reviewed
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/16)* status: 0 of 5 files reviewed, 1 unresolved discussion

___
*[`multibody/fem/mpm-dev/MPMDriver.h` line 31 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/16#-N402WH98KGrBWW9Bccz:-N402WH98KGrBWW9Bcd-:biwyjba) ([raw file](https://github.com/yiminlin-tri/drake/blob/0bc2c47f06dd62dd7e9c3315ae90d2975bd0223f/multibody/fem/mpm-dev/MPMDriver.h#L31)):*
> ```objc
>     typedef double (*DensityField)(const Vector3<double>& position);
>     // Return the initial velocity of the object at position
>     typedef Vector3<double> (*VelocityField)(const Vector3<double>& position);
> ```

These are three user-defined functions used to determine the initial condition. The are defined by users in main.cc, which is an ugly way to deal with it. I bet there is a better way to deal with user defined routines in an OOP way (I can imagine define a InitialCondition class with three member functions and let the user write the implementation?) Do you have any suggestion on handling this part?


<!-- Sent from Reviewable.io -->

2022-06-08 02:11 UTC, yiminlin-tri reviewed
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/16)* status: 0 of 5 files reviewed, 2 unresolved discussions

___
*[`multibody/fem/mpm-dev/MPMDriver.h` line 60 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/16#-N403dJDC--p6xhS3lzB:-N403dJDC--p6xhS3lzC:b8c305l) ([raw file](https://github.com/yiminlin-tri/drake/blob/0bc2c47f06dd62dd7e9c3315ae90d2975bd0223f/multibody/fem/mpm-dev/MPMDriver.h#L60)):*
> ```objc
>         // Gravitational acceleration
>         Vector3<double> g;
>     };
> ```

This struct holds all parameters in MPM, currently I hardcode the value in main.cc. I imagine it will be more convenient to write the parameters in a text file (.param) and parse it using a member function. What do you think?


<!-- Sent from Reviewable.io -->

2022-06-08 02:13 UTC, yiminlin-tri reviewed
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/16)* status: 0 of 5 files reviewed, 3 unresolved discussions

___
*[`multibody/fem/mpm-dev/MPMDriver.cc` line 57 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/16#-N404W4UAzK1m_odVRTO:-N404W4UAzK1m_odVRTP:b3izya7) ([raw file](https://github.com/yiminlin-tri/drake/blob/0bc2c47f06dd62dd7e9c3315ae90d2975bd0223f/multibody/fem/mpm-dev/MPMDriver.cc#L57)):*
> ```cpp
>                                 thinks::PoissonDiskSampling(r, x_min, x_max);
> 
>     // Pick out sampled particles that are in the object
> ```

This is inefficient... Shall we pass in a user defined parameter indicating the bounding box of the object?


<!-- Sent from Reviewable.io -->

2022-06-08 02:16 UTC, yiminlin-tri reviewed
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/16)* status: 0 of 5 files reviewed, 4 unresolved discussions

___
*[`multibody/fem/mpm-dev/MPMDriver.cc` line 62 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/16#-N404mNd2jX1UIFX_rKm:-N404mNd2jX1UIFX_rKn:b3hkcl1) ([raw file](https://github.com/yiminlin-tri/drake/blob/0bc2c47f06dd62dd7e9c3315ae90d2975bd0223f/multibody/fem/mpm-dev/MPMDriver.cc#L62)):*
> ```cpp
>     for (int p = 0; p < num_samples; ++p) {
>         const std::array<float, 3>& pos_p = particles_sample_positions[p];
>         Vector3<double> xp = Vector3<double>(pos_p[0], pos_p[1], pos_p[2]);
> ```

I do the transfer between std::array<float, 3> and Vector3<double> quite a lot. I just realize poisson-disk-sampling has a way to directly output Vector3, I will work on it tomorrow.


<!-- Sent from Reviewable.io -->

2022-06-08 16:57 UTC, yiminlin-tri reviewed
+@xuchenhan-tri  Thanks!

> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/16#-:-N43EuMK7xqArj11BW8u:b-cyeu9i)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @xuchenhan-tri)



<!-- Sent from Reviewable.io -->

2022-06-08 17:04 UTC, yiminlin-tri reviewed
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/16)* status: 0 of 5 files reviewed, 4 unresolved discussions (waiting on @xuchenhan-tri)

___
*[`multibody/fem/mpm-dev/MPMDriver.cc` line 99 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/16#-N43GKur1Bdaav1NgVlJ:-N43GKur1Bdaav1NgVlK:bbobkvt) ([raw file](https://github.com/yiminlin-tri/drake/blob/ca9a556c6fbe7cb840529e7f0fb5bf1e08b10333/multibody/fem/mpm-dev/MPMDriver.cc#L99)):*
> ```cpp
> 
>     // Set up the transfer routines (Preallocations, sort the particles)
>     MPMTransfer mpm_transfer = MPMTransfer();
> ```

I think this should be preallocated. Working on it now.


<!-- Sent from Reviewable.io -->

2022-06-08 18:06 UTC, yiminlin-tri reviewed
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/16)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @xuchenhan-tri)

___
*[`multibody/fem/mpm-dev/MPMDriver.cc` line 99 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/16#-N43GKur1Bdaav1NgVlJ:-N43UhjLEF72X3Mht-Ok:b7rl4if) ([raw file](https://github.com/yiminlin-tri/drake/blob/ca9a556c6fbe7cb840529e7f0fb5bf1e08b10333/multibody/fem/mpm-dev/MPMDriver.cc#L99)):*
<details><summary><i>Previously, yiminlin-tri wrote…</i></summary><blockquote>

I think this should be preallocated. Working on it now.
</blockquote></details>

Done. (With a bug fixed in MPMTransfer.cc)


<!-- Sent from Reviewable.io -->

2022-06-08 18:37 UTC, xuchenhan-tri requested changes
I made a pass, PTAL.
Also, is the video you posted on Monday created by this?

> Reviewed 5 of 5 files at r2, 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/16#-:-N43aeyp87PrVB_dordm:bjc67e6)* status: 3 of 6 files reviewed, 13 unresolved discussions (waiting on @xuchenhan-tri and @yiminlin-tri)

___
*[`multibody/fem/mpm-dev/MPMDriver.h` line 31 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/16#-N402WH98KGrBWW9Bccz:-N43UEwb4dqfjht5U-qK:b5e1vsa) ([raw file](https://github.com/yiminlin-tri/drake/blob/0bc2c47f06dd62dd7e9c3315ae90d2975bd0223f/multibody/fem/mpm-dev/MPMDriver.h#L31)):*
<details><summary><i>Previously, yiminlin-tri wrote…</i></summary><blockquote>

These are three user-defined functions used to determine the initial condition. The are defined by users in main.cc, which is an ugly way to deal with it. I bet there is a better way to deal with user defined routines in an OOP way (I can imagine define a InitialCondition class with three member functions and let the user write the implementation?) Do you have any suggestion on handling this part?
</blockquote></details>

Two thoughts.

1. There's std::function in c++ 11.
2. How useful it is for users to be able to specify the field to such precision? It feels to me like we should probably lean towards giving users less control but more convenience.

For example, we can imagine not providing these functions in the parameter, but instead in the driver provide

`void AddUniformDensityOjbect(const AnalyticLevelSet& level_set, double density, const Vector3<double>& initial velocity);`

I'd imagine this would be enough for our demo.
___
*[`multibody/fem/mpm-dev/MPMDriver.h` line 60 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/16#-N403dJDC--p6xhS3lzB:-N43TfjaBdZboJS5KeMY:bcp2g9h) ([raw file](https://github.com/yiminlin-tri/drake/blob/0bc2c47f06dd62dd7e9c3315ae90d2975bd0223f/multibody/fem/mpm-dev/MPMDriver.h#L60)):*
<details><summary><i>Previously, yiminlin-tri wrote…</i></summary><blockquote>

This struct holds all parameters in MPM, currently I hardcode the value in main.cc. I imagine it will be more convenient to write the parameters in a text file (.param) and parse it using a member function. What do you think?
</blockquote></details>

I think this is fine for now as long as you find it convenient enough to use.

I'd advocate for 
1. Moving this into a separate file, and
2. Docuement more extensively what each member does/controls. For example, I have no idea what `total_volume` and `sample_r` do here.
3. optional, spliting into physical parameters (E, nu, etc), solver parameters (dt, grid specification), and io_parameters.
___
*[`multibody/fem/mpm-dev/MPMDriver.cc` line 8 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/16#-N43VlBV0WjvnG0Uvhhw:-N43VlBV0WjvnG0Uvhhx:b-34v4zn) ([raw file](https://github.com/yiminlin-tri/drake/blob/ca9a556c6fbe7cb840529e7f0fb5bf1e08b10333/multibody/fem/mpm-dev/MPMDriver.cc#L8)):*
> ```cpp
> 
> MPMDriver::MPMDriver(MPMParameters param) {
>     param_ = param;
> ```

BTW you can do params_ = std::move(param);
___
*[`multibody/fem/mpm-dev/MPMDriver.cc` line 13 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/16#-N43VpxM-mFfAsFx-mtu:-N43VpxM-mFfAsFx-mtv:b-ef0rvm) ([raw file](https://github.com/yiminlin-tri/drake/blob/ca9a556c6fbe7cb840529e7f0fb5bf1e08b10333/multibody/fem/mpm-dev/MPMDriver.cc#L13)):*
> ```cpp
> void MPMDriver::InitializeBoundaryConditions(
>                         std::vector<BoundaryCondition::Boundary> boundaries) {
>     boundary_condition_ = BoundaryCondition(boundaries);
> ```

BTW you can do `boundary_condition_ = BoundaryCondition(std::move(boundaries));`
___
*[`multibody/fem/mpm-dev/MPMDriver.cc` line 36 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/16#-N43WO3w4oZdsH0OXeX8:-N43WO3w4oZdsH0OXeX9:bgikxx7) ([raw file](https://github.com/yiminlin-tri/drake/blob/ca9a556c6fbe7cb840529e7f0fb5bf1e08b10333/multibody/fem/mpm-dev/MPMDriver.cc#L36)):*
> ```cpp
>         AdvanceOneTimeStep();
>         step++;
>         if (step % param_.write_interval == 0) {
> ```

nit, I think it'd be more intuitive if write_interval has unit of time instead of number of timesteps.
___
*[`multibody/fem/mpm-dev/MPMDriver.cc` line 54 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/16#-N43XSfFEr3PnK30Amft:-N43XSfFEr3PnK30Amfu:b-9vh0qo) ([raw file](https://github.com/yiminlin-tri/drake/blob/ca9a556c6fbe7cb840529e7f0fb5bf1e08b10333/multibody/fem/mpm-dev/MPMDriver.cc#L54)):*
> ```cpp
>                 (param_.bottom_corner(2)+param_.num_gridpt_1D(2)-1)*h}};
>     std::vector<Vector3<double>> particles_sample_positions =
>         thinks::PoissonDiskSampling<double, 3, Vector3<double>>(param_.sample_r,
> ```

Hmm, this is a little wasteful to say the least. This would also not work if we switch to an adaptive grid.

Nonblocking for now. But if we opt for the alternative way of initializing particles that I propose above, we only need to poisson disk sample particles in the bounding box of the provided level set.
___
*[`multibody/fem/mpm-dev/MPMDriver.cc` line 54 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/16#-N43Y61k2rZwtP_18kAc:-N43Y61k2rZwtP_18kAd:b-uurmis) ([raw file](https://github.com/yiminlin-tri/drake/blob/ca9a556c6fbe7cb840529e7f0fb5bf1e08b10333/multibody/fem/mpm-dev/MPMDriver.cc#L54)):*
> ```cpp
>                 (param_.bottom_corner(2)+param_.num_gridpt_1D(2)-1)*h}};
>     std::vector<Vector3<double>> particles_sample_positions =
>         thinks::PoissonDiskSampling<double, 3, Vector3<double>>(param_.sample_r,
> ```

Ok I see what sample_r does now. This is too obscure and definition shouldn't be a user-specified parameter. User should be able to specify something like particles_per_cell, and we should convert that to this sample_r parameter.
___
*[`multibody/fem/mpm-dev/MPMDriver.cc` line 69 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/16#-N43YNwQ7TNDvtwpspUA:-N43YNwQ7TNDvtwpspUB:bvyy5km) ([raw file](https://github.com/yiminlin-tri/drake/blob/ca9a556c6fbe7cb840529e7f0fb5bf1e08b10333/multibody/fem/mpm-dev/MPMDriver.cc#L69)):*
> ```cpp
>     int num_particles = particles_positions.size();
>     // We assume every particle have the same volume
>     double reference_volume_p = param_.total_volume/num_particles;
> ```

ok, I see what total_volume does too. Again, if we initialize with the level set way, the level set should be able to provide a volume. 
___
*[`multibody/fem/mpm-dev/MPMDriver.cc` line 95 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/16#-N43Yt0e4jXPAYa-yptX:-N43Yt0e4jXPAYa-yptY:bsxv1ay) ([raw file](https://github.com/yiminlin-tri/drake/blob/ca9a556c6fbe7cb840529e7f0fb5bf1e08b10333/multibody/fem/mpm-dev/MPMDriver.cc#L95)):*
> ```cpp
> 
> void MPMDriver::AdvanceOneTimeStep() {
>     CorotatedModel corotated_model = CorotatedModel(param_.E, param_.nu);
> ```

I'm a surprised to see the constitutive model, the transfer, and the gravity field not persist in this class. Could you explain why this choice?
___
*[`multibody/fem/mpm-dev/MPMDriver.cc` line 117 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/16#-N43Zgbf7A9_J8x8Vae-:-N43Zgbf7A9_J8x8Vae0:bfkpxr7) ([raw file](https://github.com/yiminlin-tri/drake/blob/ca9a556c6fbe7cb840529e7f0fb5bf1e08b10333/multibody/fem/mpm-dev/MPMDriver.cc#L117)):*
> ```cpp
> 
>     // Advect and update particles
>     particles_.UpdateKirchhoffStresses(corotated_model);
> ```

This should happen before the transfers right? Consider the case when the particles are initialized with non-identity deformation gradient.
___
*[`multibody/fem/mpm-dev/MPMTransfer.cc` line 100 at r3](https://reviewable.io/reviews/yiminlin-tri/drake/16#-N43_04j5NoYs28UfUfG:-N43_04j5NoYs28UfUfH:btdco25) ([raw file](https://github.com/yiminlin-tri/drake/blob/ea38e79b330483d23f58ba877e62889ede10a3e7/multibody/fem/mpm-dev/MPMTransfer.cc#L100)):*
> ```cpp
>     std::vector<int> batch_indices(num_particles);
>     // Initialize batch_size  [...]

2022-06-08 18:38 UTC, xuchenhan-tri reviewed
> Reviewed 1 of 3 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/16)* status: all files reviewed, 13 unresolved discussions (waiting on @yiminlin-tri)



<!-- Sent from Reviewable.io -->

2022-06-08 18:42 UTC, yiminlin-tri reviewed
Thanks! Monday's video doesn't use the same set of parameter. There is also no friction BC and gravity in Monday's video.

> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/16#-:-N43b5SLAvwr9VM8lpve:bgs0zqg)* status: all files reviewed, 13 unresolved discussions (waiting on @yiminlin-tri)



<!-- Sent from Reviewable.io -->

2022-06-08 22:46 UTC, xuchenhan-tri reviewed
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/16)* status: all files reviewed, 13 unresolved discussions (waiting on @yiminlin-tri)

___
*[`multibody/fem/mpm-dev/poisson_disk_sampling.h` line 563 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/16#-N43LsQF8ICIydXiqqSr:-N44UmRZ28hKzhisnxGK:bj7968e) ([raw file](https://github.com/yiminlin-tri/drake/blob/ca9a556c6fbe7cb840529e7f0fb5bf1e08b10333/multibody/fem/mpm-dev/poisson_disk_sampling.h#L563)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, I don't think we need this template here. We have only one floating type -- double.
</blockquote></details>

This is the diff I had in mind



_Suggestion:_
```objc
// Specialization of vector traits for Vector3
struct VecTraits<drake::Vector3<double>> {
  using ValueType = typename drake::Vector3<double>::Scalar;
  static constexpr auto kSize = 3;

  static constexpr auto Get(const drake::Vector3<double>& vec,
                            const std::size_t i) -> ValueType {
    return vec(i);
  }

  static constexpr void Set(drake::Vector3<double>* vec,
                            const std::size_t i, const ValueType val) {
    (*vec)(i) = val;
  }
};
```


<!-- Sent from Reviewable.io -->

2022-06-08 22:54 UTC, yiminlin-tri reviewed
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/16)* status: all files reviewed, 12 unresolved discussions (waiting on @xuchenhan-tri and @yiminlin-tri)

___
*[`multibody/fem/mpm-dev/MPMDriver.cc` line 95 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/16#-N43Yt0e4jXPAYa-yptX:-N43d4bc3__5icdBTiaC:bxl41h4) ([raw file](https://github.com/yiminlin-tri/drake/blob/ca9a556c6fbe7cb840529e7f0fb5bf1e08b10333/multibody/fem/mpm-dev/MPMDriver.cc#L95)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I'm a surprised to see the constitutive model, the transfer, and the gravity field not persist in this class. Could you explain why this choice?
</blockquote></details>

Done. I agree, I am moving them as member variables now.
___
*[`multibody/fem/mpm-dev/MPMDriver.cc` line 117 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/16#-N43Zgbf7A9_J8x8Vae-:-N43dZ5s0DNebY5_0jvJ:b-pyyx2q) ([raw file](https://github.com/yiminlin-tri/drake/blob/ca9a556c6fbe7cb840529e7f0fb5bf1e08b10333/multibody/fem/mpm-dev/MPMDriver.cc#L117)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

This should happen before the transfers right? Consider the case when the particles are initialized with non-identity deformation gradient.
</blockquote></details>

Done. Yes
___
*[`multibody/fem/mpm-dev/MPMTransfer.cc` line 100 at r3](https://reviewable.io/reviews/yiminlin-tri/drake/16#-N43_04j5NoYs28UfUfG:-N44J1Bn-0sdpC96vopE:bgn2dek) ([raw file](https://github.com/yiminlin-tri/drake/blob/ea38e79b330483d23f58ba877e62889ede10a3e7/multibody/fem/mpm-dev/MPMTransfer.cc#L100)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, I believe you could do 

`batch_sizes_.resize(grid.get_num_gridpt(), 0);`
</blockquote></details>

Just checked. Seems like resize will not rewrite all elements in the vector as 0, it will only populate uninitialized value to 0.
___
*[`multibody/fem/mpm-dev/poisson_disk_sampling.h` line 563 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/16#-N43LsQF8ICIydXiqqSr:-N44NBfo7w08ss_NCNbE:bfc1emk) ([raw file](https://github.com/yiminlin-tri/drake/blob/ca9a556c6fbe7cb840529e7f0fb5bf1e08b10333/multibody/fem/mpm-dev/poisson_disk_sampling.h#L563)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

This is the diff I had in mind
</blockquote></details>

I got " error: call to non-'constexpr' function 'Eigen::DenseCoeffsBase<Derived, 0>::CoeffReturnType Eigen::DenseCoeffsBase<Derived, 0>::operator()(Eigen::Index) const [with Derived = Eigen::Matrix<double, 3, 1>; Eigen::DenseCoeffsBase<Derived, 0>::CoeffReturnType = const double&; Eigen::Index = long int]'
  570 |     return vec(i);
      |                 ^
and
error: call to non-'constexpr' function 'Eigen::DenseCoeffsBase<Derived, 1>::Scalar& Eigen::DenseCoeffsBase<Derived, 1>::operator()(Eigen::Index) [with Derived = Eigen::Matrix<double, 3, 1>; Eigen::DenseCoeffsBase<Derived, 1>::Scalar = double; Eigen::Index = long int]'
  575 |     (*vec)(i) = val;
      |             ^


<!-- Sent from Reviewable.io -->

2022-06-08 23:17 UTC, xuchenhan-tri requested changes
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/16)* status: all files reviewed, 13 unresolved discussions (waiting on @yiminlin-tri)

___
*[`multibody/fem/mpm-dev/BUILD.bazel` line 15 at r4](https://reviewable.io/reviews/yiminlin-tri/drake/16#-N44at3k9FYT2LYc-oGD:-N44at3k9FYT2LYc-oGE:biopoaf) ([raw file](https://github.com/yiminlin-tri/drake/blob/97e49465df294a3169c17fa389cef1241ab517c0/multibody/fem/mpm-dev/BUILD.bazel#L15)):*
> ```Starlark
> load("//tools/lint:lint.bzl", "add_lint_tests")
> 
> drake_cc_library(
> ```

nit, I just realized, why is this not a binary?
___
*[`multibody/fem/mpm-dev/MPMDriver.cc` line 95 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/16#-N43Yt0e4jXPAYa-yptX:-N44aBGTB46mQw78Mvaz:b-40f6x0) ([raw file](https://github.com/yiminlin-tri/drake/blob/ca9a556c6fbe7cb840529e7f0fb5bf1e08b10333/multibody/fem/mpm-dev/MPMDriver.cc#L95)):*
<details><summary><i>Previously, yiminlin-tri wrote…</i></summary><blockquote>

Done. I agree, I am moving them as member variables now.
</blockquote></details>

Looks like the constitutive model and the gravity field are still local.
___
*[`multibody/fem/mpm-dev/MPMDriver.cc` line 117 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/16#-N43Zgbf7A9_J8x8Vae-:-N44axsLBCKGZXxDll7c:b-1wzu1q) ([raw file](https://github.com/yiminlin-tri/drake/blob/ca9a556c6fbe7cb840529e7f0fb5bf1e08b10333/multibody/fem/mpm-dev/MPMDriver.cc#L117)):*
<details><summary><i>Previously, yiminlin-tri wrote…</i></summary><blockquote>

Done. Yes
</blockquote></details>

Seems like this is unchanged as of this revision.
___
*[`multibody/fem/mpm-dev/MPMTransfer.cc` line 100 at r3](https://reviewable.io/reviews/yiminlin-tri/drake/16#-N43_04j5NoYs28UfUfG:-N44aJFv0M5WrCwDzxih:b-kufkx2) ([raw file](https://github.com/yiminlin-tri/drake/blob/ea38e79b330483d23f58ba877e62889ede10a3e7/multibody/fem/mpm-dev/MPMTransfer.cc#L100)):*
<details><summary><i>Previously, yiminlin-tri wrote…</i></summary><blockquote>

Just checked. Seems like resize will not rewrite all elements in the vector as 0, it will only populate uninitialized value to 0.
</blockquote></details>

I see, thanks.
___
*[`multibody/fem/mpm-dev/poisson_disk_sampling.h` line 563 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/16#-N43LsQF8ICIydXiqqSr:-N44_zVHDV9XQq-v7I_t:bjv3egn) ([raw file](https://github.com/yiminlin-tri/drake/blob/ca9a556c6fbe7cb840529e7f0fb5bf1e08b10333/multibody/fem/mpm-dev/poisson_disk_sampling.h#L563)):*
<details><summary><i>Previously, yiminlin-tri wrote…</i></summary><blockquote>

I got " error: call to non-'constexpr' function 'Eigen::DenseCoeffsBase<Derived, 0>::CoeffReturnType Eigen::DenseCoeffsBase<Derived, 0>::operator()(Eigen::Index) const [with Derived = Eigen::Matrix<double, 3, 1>; Eigen::DenseCoeffsBase<Derived, 0>::CoeffReturnType = const double&; Eigen::Index = long int]'
  570 |     return vec(i);
      |                 ^
and
error: call to non-'constexpr' function 'Eigen::DenseCoeffsBase<Derived, 1>::Scalar& Eigen::DenseCoeffsBase<Derived, 1>::operator()(Eigen::Index) [with Derived = Eigen::Matrix<double, 3, 1>; Eigen::DenseCoeffsBase<Derived, 1>::Scalar = double; Eigen::Index = long int]'
  575 |     (*vec)(i) = val;
      |             ^
</blockquote></details>

Could you share the command to trigger these error?


<!-- Sent from Reviewable.io -->

2022-06-08 23:20 UTC, xuchenhan-tri reviewed
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/16)* status: all files reviewed, 13 unresolved discussions (waiting on @yiminlin-tri)

___
*[`multibody/fem/mpm-dev/poisson_disk_sampling.h` line 563 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/16#-N43LsQF8ICIydXiqqSr:-N44bYZ_6Bws2zbZ7R39:bb2zwsx) ([raw file](https://github.com/yiminlin-tri/drake/blob/ca9a556c6fbe7cb840529e7f0fb5bf1e08b10333/multibody/fem/mpm-dev/poisson_disk_sampling.h#L563)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Could you share the command to trigger these error?
</blockquote></details>

Nvm, I just need to run the demo to reproduce...


<!-- Sent from Reviewable.io -->

2022-06-08 23:25 UTC, xuchenhan-tri reviewed
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/16)* status: all files reviewed, 13 unresolved discussions (waiting on @yiminlin-tri)

___
*[`multibody/fem/mpm-dev/poisson_disk_sampling.h` line 563 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/16#-N43LsQF8ICIydXiqqSr:-N44cZ_71waRlUSvojjQ:b-eu4od4) ([raw file](https://github.com/yiminlin-tri/drake/blob/ca9a556c6fbe7cb840529e7f0fb5bf1e08b10333/multibody/fem/mpm-dev/poisson_disk_sampling.h#L563)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Nvm, I just need to run the demo to reproduce...
</blockquote></details>

```
// Specialization of vector traits for Vector3
template <>
struct VecTraits<drake::Vector3<double>> {
  using ValueType = typename drake::Vector3<double>::Scalar;
  static constexpr auto kSize = 3;

  static ValueType Get(const drake::Vector3<double>& vec,
                       const std::size_t i)  {
    return vec(i);
  }

  static void Set(drake::Vector3<double>* vec,
                  const std::size_t i, const ValueType val) {
    (*vec)(i) = val;
  }
};
```
This should do it.


<!-- Sent from Reviewable.io -->

2022-06-08 23:27 UTC, yiminlin-tri reviewed
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/16)* status: all files reviewed, 13 unresolved discussions (waiting on @xuchenhan-tri and @yiminlin-tri)

___
*[`multibody/fem/mpm-dev/poisson_disk_sampling.h` line 563 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/16#-N43LsQF8ICIydXiqqSr:-N44d6Ku9DLo2bS-n1P_:b-l2klwv) ([raw file](https://github.com/yiminlin-tri/drake/blob/ca9a556c6fbe7cb840529e7f0fb5bf1e08b10333/multibody/fem/mpm-dev/poisson_disk_sampling.h#L563)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

```
// Specialization of vector traits for Vector3
template <>
struct VecTraits<drake::Vector3<double>> {
  using ValueType = typename drake::Vector3<double>::Scalar;
  static constexpr auto kSize = 3;

  static ValueType Get(const drake::Vector3<double>& vec,
                       const std::size_t i)  {
    return vec(i);
  }

  static void Set(drake::Vector3<double>* vec,
                  const std::size_t i, const ValueType val) {
    (*vec)(i) = val;
  }
};
```
This should do it.
</blockquote></details>

Aha. Works perfectly. Thanks!


<!-- Sent from Reviewable.io -->

2022-06-10 00:05 UTC, yiminlin-tri reviewed
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/16)* status: all files reviewed, 10 unresolved discussions (waiting on @xuchenhan-tri and @yiminlin-tri)

___
*[`multibody/fem/mpm-dev/poisson_disk_sampling.h` line 1 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/16#-N43LI4d3IXB9Azs7PxF:-N49OSVR1AvLtb6xIaKW:b-896fix) ([raw file](https://github.com/yiminlin-tri/drake/blob/ca9a556c6fbe7cb840529e7f0fb5bf1e08b10333/multibody/fem/mpm-dev/poisson_disk_sampling.h#L1)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

This file probably should be in its own PR. Eventually, we'd need to pull in this as a proper dependency.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-06-14 00:18 UTC, yiminlin-tri reviewed
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/16)* status: 0 of 7 files reviewed, 6 unresolved discussions (waiting on @xuchenhan-tri)

___
*[`multibody/fem/mpm-dev/MPMDriver.cc` line 54 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/16#-N43Y61k2rZwtP_18kAc:-N4UYzRo1mudkc4Vl9ei:b-896fix) ([raw file](https://github.com/yiminlin-tri/drake/blob/ca9a556c6fbe7cb840529e7f0fb5bf1e08b10333/multibody/fem/mpm-dev/MPMDriver.cc#L54)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Ok I see what sample_r does now. This is too obscure and definition shouldn't be a user-specified parameter. User should be able to specify something like particles_per_cell, and we should convert that to this sample_r parameter.
</blockquote></details>

Done.
___
*[`multibody/fem/mpm-dev/MPMDriver.cc` line 69 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/16#-N43YNwQ7TNDvtwpspUA:-N4UZ-5CCXeipPoaeOzD:b-896fix) ([raw file](https://github.com/yiminlin-tri/drake/blob/ca9a556c6fbe7cb840529e7f0fb5bf1e08b10333/multibody/fem/mpm-dev/MPMDriver.cc#L69)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

ok, I see what total_volume does too. Again, if we initialize with the level set way, the level set should be able to provide a volume. 
</blockquote></details>

Done.
___
*[`multibody/fem/mpm-dev/MPMDriver.cc` line 95 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/16#-N43Yt0e4jXPAYa-yptX:-N4UZ2HP3Lf8VC6OT2D7:b-896fix) ([raw file](https://github.com/yiminlin-tri/drake/blob/ca9a556c6fbe7cb840529e7f0fb5bf1e08b10333/multibody/fem/mpm-dev/MPMDriver.cc#L95)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Looks like the constitutive model and the gravity field are still local.
</blockquote></details>

Done.
___
*[`multibody/fem/mpm-dev/MPMDriver.cc` line 117 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/16#-N43Zgbf7A9_J8x8Vae-:-N4Tk85-DNH7G9vTWhnp:b-896fix) ([raw file](https://github.com/yiminlin-tri/drake/blob/ca9a556c6fbe7cb840529e7f0fb5bf1e08b10333/multibody/fem/mpm-dev/MPMDriver.cc#L117)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Seems like this is unchanged as of this revision.
</blockquote></details>

Done.
___
*[`multibody/fem/mpm-dev/main.cpp` line 30 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/16#-N43_uC62K9emgec-QFy:-N4Tk0qE2kPNPaIXzCIC:b-896fix) ([raw file](https://github.com/yiminlin-tri/drake/blob/ca9a556c6fbe7cb840529e7f0fb5bf1e08b10333/multibody/fem/mpm-dev/main.cpp#L30)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Ummm, why not just 1.0?

BTW, this density is 1000 times lower than water... What material do you have in mind here?
</blockquote></details>

Done.
___
*[`multibody/fem/mpm-dev/main.cpp` line 55 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/16#-N43aBd-2oK5H5rs9Wwn:-N4Tk1Q-5GZJydr9JIZN:b-896fix) ([raw file](https://github.com/yiminlin-tri/drake/blob/ca9a556c6fbe7cb840529e7f0fb5bf1e08b10333/multibody/fem/mpm-dev/main.cpp#L55)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

That's an extremely low young's modulus BTW
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-06-14 00:23 UTC, yiminlin-tri reviewed
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/16)* status: 0 of 7 files reviewed, 7 unresolved discussions (waiting on @xuchenhan-tri)

___
*[`multibody/fem/mpm-dev/MPMTransfer.cc` line 245 at r6](https://reviewable.io/reviews/yiminlin-tri/drake/16#-N4U_LLD-jO3X4eHuVsP:-N4U_LLE1TjRX8wRax5c:b-qkd0ki) ([raw file](https://github.com/yiminlin-tri/drake/blob/847eb160943ee44fb2bfa2f580b2f9840110c5fc/multibody/fem/mpm-dev/MPMTransfer.cc#L245)):*
> ```cpp
>         grid_index(1) = bj+b;
>         grid_index(2) = bk+c;
>     if (grid->in_index_range(grid_index)) {
> ```

Otherwise Segfault (grid_index may lie out of range, so Reduce3DIndex will gives index that is out of bound.)


<!-- Sent from Reviewable.io -->

2022-06-14 04:32 UTC, xuchenhan-tri requested changes
I made another pass. 

An overall theme of the comments is that we should spend a little more effort into designing the API and the data structure. Sure this is code for experiments and it doesn't need to be perfect, but well-designed API saves time in the long run and avoid bugs that are time consuming. We should try strike a balance between getting a functional set of code running fast (but potentially spending more time debugging/maintaining in the future) vs polishing the API and data structure in the first place (at the cost of more development time). I had an experience going all-in with the former when I was doing a simulation internship -- choosing the path of least resistance to get every feature in ASAP. But as the project stretches on, there are times when I regretted that decision. I'm hoping that you don't need to go through the late-night debugging sessions that I went through, so please bear with my nags!

> Reviewed 1 of 6 files at r5, 6 of 6 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/16#-:-N4VRS5v5d43evLecq47:bnw98b6)* status: all files reviewed, 8 unresolved discussions (waiting on @yiminlin-tri)

___
*[`multibody/fem/mpm-dev/MPMDriver.h` line 35 at r6](https://reviewable.io/reviews/yiminlin-tri/drake/16#-N4VI5Dh2-KpN2-6uCGg:-N4VI5Dh2-KpN2-6uCGh:b-kp3hn) ([raw file](https://github.com/yiminlin-tri/drake/blob/847eb160943ee44fb2bfa2f580b2f9840110c5fc/multibody/fem/mpm-dev/MPMDriver.h#L35)):*
> ```objc
>     // Run the MPM simulation with the object represented by the given level set
>     // in the reference frame, then transformed into the physical frame by pose.
>     void Run(const AnalyticLevelSet& level_set,
> ```

BTW, this doesn't allow us to simulate more than one object at a time (which maybe ok for now depending what demos you have in mind. But a general rule of thumb in designing API is that you want each function to do one thing (if possible). For example, there should be one function that add a object to the scene (with some prescribed parameters), and another function that kicks off the simulation. 
```
void AddParticles(const AnalyticLevelSet& level_set, 
                  const RigidTransformd& pose, 
                  MaterialParameters param);
void Run();
```
Something like this gives you the flexibility to simulate different materials in the same scene with natural coupling via the grid. (This is the most significant advantage of MPM over competing methods). With that said, if you think this API suits your need for now, I won't block.
___
*[`multibody/fem/mpm-dev/MPMDriver.cc` line 29 at r6](https://reviewable.io/reviews/yiminlin-tri/drake/16#-N4VK_Pt-NgRp-YMIfoF:-N4VK_Pt-NgRp-YMIfoG:bv7dkjt) ([raw file](https://github.com/yiminlin-tri/drake/blob/847eb160943ee44fb2bfa2f580b2f9840110c5fc/multibody/fem/mpm-dev/MPMDriver.cc#L29)):*
> ```cpp
> }
> 
> void MPMDriver::SetUpDriver(const AnalyticLevelSet& level_set,
> ```

I'm not seeing the need for this function. The grid and the transfer should be set up in the constructor and the IntializeParticles function can be public.
___
*[`multibody/fem/mpm-dev/MPMDriver.cc` line 31 at r6](https://reviewable.io/reviews/yiminlin-tri/drake/16#-N4VKHhO6RQZ7s4l2eMS:-N4VKHhPEZGdCERzudDt:b62lydk) ([raw file](https://github.com/yiminlin-tri/drake/blob/847eb160943ee44fb2bfa2f580b2f9840110c5fc/multibody/fem/mpm-dev/MPMDriver.cc#L31)):*
> ```cpp
> void MPMDriver::SetUpDriver(const AnalyticLevelSet& level_set,
>                             const math::RigidTransform<double>& pose) {
>     MPMDriver::InitializeParticles(level_set, pose);
> ```

nit, is this scope specifier needed?
___
*[`multibody/fem/mpm-dev/MPMDriver.cc` line 51 at r6](https://reviewable.io/reviews/yiminlin-tri/drake/16#-N4VL9JK2DfMeblhOVnu:-N4VL9JL-xpj5aH5HNLX:bpa1p2b) ([raw file](https://github.com/yiminlin-tri/drake/blob/847eb160943ee44fb2bfa2f580b2f9840110c5fc/multibody/fem/mpm-dev/MPMDriver.cc#L51)):*
> ```cpp
>             dt = endtime - dt;
>         }
>         AdvanceOneTimeStep();
> ```

There should be some CFL condition check here: If a particle's velocity is large enough that it can skip a cell in a time step, we should abort.
___
*[`multibody/fem/mpm-dev/MPMDriver.cc` line 69 at r6](https://reviewable.io/reviews/yiminlin-tri/drake/16#-N4VN-jx0dioS_5_zW4e:-N4VN-jx0dioS_5_zW4f:bo3sqt5) ([raw file](https://github.com/yiminlin-tri/drake/blob/847eb160943ee44fb2bfa2f580b2f9840110c5fc/multibody/fem/mpm-dev/MPMDriver.cc#L69)):*
> ```cpp
>     // Distances between generated particles are at at least sample_r apart, and
>     // there are at least min_num_particles_per_cell particles per cell.
>     // r = argmax(⌊h/r⌋)^3, in other words, if we pick particles located at
> ```

This doesn't make sense to me. Could you clarify the criterion for choosing `sample_r`?



_Code quote:_
```cpp
r = argmax(⌊h/r⌋)^3
```
___
*[`multibody/fem/mpm-dev/MPMDriver.cc` line 101 at r6](https://reviewable.io/reviews/yiminlin-tri/drake/16#-N4VKwtC6_0vo0MuXZOC:-N4VKwtC6_0vo0MuXZOD:b-sl6ixu) ([raw file](https://github.com/yiminlin-tri/drake/blob/847eb160943ee44fb2bfa2f580b2f9840110c5fc/multibody/fem/mpm-dev/MPMDriver.cc#L101)):*
> ```cpp
> 
>     // Make an empty particles class
>     particles_ = Particles();
> ```

BTW, not needed since `particles_` is already default constructed in the constructor of `MPMDriver`.
___
*[`multibody/fem/mpm-dev/MPMParameters.h` line 17 at r6](https://reviewable.io/reviews/yiminlin-tri/drake/16#-N4VOnxICVG2cUXt1woM:-N4VOnxICVG2cUXt1woN:byd9wlv) ([raw file](https://github.com/yiminlin-tri/drake/blob/847eb160943ee44fb2bfa2f580b2f9840110c5fc/multibody/fem/mpm-dev/MPMParameters.h#L17)):*
> ```objc
> 
> // A class holding the parameters used in MPMDriver
> class MPMParameters {
> ```

Designing a single parameter class the implication that one can only have one set of parameters. For parameters that are global, this is fine. For example, it is desirable to have one and only one gravitational constant, one dt, and one end time. For parameters that describe an object or a boundary condition, this is not so desirable. For example, we are restricted to simulating a single type of object with a single E, nu, density, initial velocity. It also restricts us to simulating with a single frictional coefficient for all boundaries. This, for example, would prevent us from setting up a demo where two blob of materials with opposing initial velocities bumping into each other.
___
*[`multibody/fem/mpm-dev/MPMParameters.h` line 24 at r6](https://reviewable.io/reviews/yiminlin-tri/drake/16#-N4VO1fG8zoe2AVeLAoM:-N4VO1fG8zoe2AVeLAoN:b-q5m85w) ([raw file](https://github.com/yiminlin-tri/drake/blob/847eb160943ee44fb2bfa2f580b2f9840110c5fc/multibody/fem/mpm-dev/MPMParameters.h#L24)):*
> ```objc
>         double nu;                           // Poisson's ratio
>         // Boundary condition parameters
>         double mu;                           // Friction coefficient
> ```

This seems like a misfit to me. I can see that we may get away with a homogeneous material (and thus a single E and nu for everything), but it seems like the a single frictional coefficient won't cut it for the dough rolling demo. We may want different frictional coefficient for the spatula and the workspace table for example.

This is all the more confusing considering there's another friction coefficient parameter already in `BoundaryCondition` class.
___
*[`multibody/fem/mpm-dev/MPMTransfer.cc` line 245 at r6](https://reviewable.io/reviews/yiminlin-tri/drake/16#-N4U_LLD-jO3X4eHuVsP:-N4VPyvl9zy5EBpgLOxV:b-rzxmy3) ([raw file](https://github.com/yiminlin-tri/drake/blob/847eb160943ee44fb2bfa2f580b2f9840110c5fc/multibody/fem/mpm-dev/MPMTransfer.cc#L245)):*
<details><summary><i>Previously, yiminlin-tri wrote…</i></summary><blockquote>

Otherwise Segfault (grid_index may lie out of range, so Reduce3DIndex will gives index that is out of bound.)
</blockquote></details>

I believe we have went over this in prev [...]

2022-06-14 04:51 UTC, yiminlin-tri reviewed
Sure, thanks for the detailed comments, I appreciate it! :thumbsup: I agree, the current API is only suitable to simulating one object, and more works need to be done even for the demo we are aiming for. I will work on it tomorrow. Thanks! 

> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/16#-:-N4VWHmr2w90vlJ_Y93-:b-kol4g9)* status: all files reviewed, 8 unresolved discussions (waiting on @yiminlin-tri)



<!-- Sent from Reviewable.io -->

2022-06-14 21:58 UTC, yiminlin-tri reviewed
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/16)* status: all files reviewed, 7 unresolved discussions (waiting on @xuchenhan-tri)

___
*[`multibody/fem/mpm-dev/MPMDriver.cc` line 29 at r6](https://reviewable.io/reviews/yiminlin-tri/drake/16#-N4VK_Pt-NgRp-YMIfoF:-N4Y2RdGEvLLUNOkKjqU:b-896fix) ([raw file](https://github.com/yiminlin-tri/drake/blob/847eb160943ee44fb2bfa2f580b2f9840110c5fc/multibody/fem/mpm-dev/MPMDriver.cc#L29)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I'm not seeing the need for this function. The grid and the transfer should be set up in the constructor and the IntializeParticles function can be public.
</blockquote></details>

Done.
___
*[`multibody/fem/mpm-dev/MPMDriver.cc` line 51 at r6](https://reviewable.io/reviews/yiminlin-tri/drake/16#-N4VL9JK2DfMeblhOVnu:-N4Z9l6L1N1sSTyZ166B:b-896fix) ([raw file](https://github.com/yiminlin-tri/drake/blob/847eb160943ee44fb2bfa2f580b2f9840110c5fc/multibody/fem/mpm-dev/MPMDriver.cc#L51)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

There should be some CFL condition check here: If a particle's velocity is large enough that it can skip a cell in a time step, we should abort.
</blockquote></details>

Done.
___
*[`multibody/fem/mpm-dev/MPMDriver.cc` line 69 at r6](https://reviewable.io/reviews/yiminlin-tri/drake/16#-N4VN-jx0dioS_5_zW4e:-N4Y2tBFBQVS1RhdYYYL:b-cvm4b3) ([raw file](https://github.com/yiminlin-tri/drake/blob/847eb160943ee44fb2bfa2f580b2f9840110c5fc/multibody/fem/mpm-dev/MPMDriver.cc#L69)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

This doesn't make sense to me. Could you clarify the criterion for choosing `sample_r`?
</blockquote></details>

Oops, the documentation is incorrect, it should be r = argmax [(⌊h/r⌋)^3 >= min_num_particles_per_cell. 
The idea is that we do an uniform sampling in the cell, just like picking the grid point, with grid size r. (⌊h/r⌋)^3 is then the number of particles we can sample. This is an upper bound on the number of sampled particles of Poisson disk sampling.
___
*[`multibody/fem/mpm-dev/MPMParameters.h` line 17 at r6](https://reviewable.io/reviews/yiminlin-tri/drake/16#-N4VOnxICVG2cUXt1woM:-N4Z34NR1QWlzRr9tVn-:b-896fix) ([raw file](https://github.com/yiminlin-tri/drake/blob/847eb160943ee44fb2bfa2f580b2f9840110c5fc/multibody/fem/mpm-dev/MPMParameters.h#L17)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Designing a single parameter class the implication that one can only have one set of parameters. For parameters that are global, this is fine. For example, it is desirable to have one and only one gravitational constant, one dt, and one end time. For parameters that describe an object or a boundary condition, this is not so desirable. For example, we are restricted to simulating a single type of object with a single E, nu, density, initial velocity. It also restricts us to simulating with a single frictional coefficient for all boundaries. This, for example, would prevent us from setting up a demo where two blob of materials with opposing initial velocities bumping into each other.
</blockquote></details>

Done.
___
*[`multibody/fem/mpm-dev/MPMParameters.h` line 24 at r6](https://reviewable.io/reviews/yiminlin-tri/drake/16#-N4VO1fG8zoe2AVeLAoM:-N4Z3LMI80kwfxy4gcD7:b-896fix) ([raw file](https://github.com/yiminlin-tri/drake/blob/847eb160943ee44fb2bfa2f580b2f9840110c5fc/multibody/fem/mpm-dev/MPMParameters.h#L24)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

This seems like a misfit to me. I can see that we may get away with a homogeneous material (and thus a single E and nu for everything), but it seems like the a single frictional coefficient won't cut it for the dough rolling demo. We may want different frictional coefficient for the spatula and the workspace table for example.

This is all the more confusing considering there's another friction coefficient parameter already in `BoundaryCondition` class.
</blockquote></details>

Done.
___
*[`multibody/fem/mpm-dev/MPMTransfer.cc` line 245 at r6](https://reviewable.io/reviews/yiminlin-tri/drake/16#-N4U_LLD-jO3X4eHuVsP:-N4ZCgGr3dNbZKjW3DkA:b-896fix) ([raw file](https://github.com/yiminlin-tri/drake/blob/847eb160943ee44fb2bfa2f580b2f9840110c5fc/multibody/fem/mpm-dev/MPMTransfer.cc#L245)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I believe we have went over this in previous PRs. When things go out of bound, do not silently skip the grid node. It will give incorrect results that are extremely hard to debug. We should have a central location that checks if particles are going out of bound.

If you somehow triggered this segfault, it means that we missed this in our out-of-bound check. We should fix that instead of covering it up with another bug.
</blockquote></details>

Done.
___
*[`multibody/fem/mpm-dev/main.cpp` line 47 at r6](https://reviewable.io/reviews/yiminlin-tri/drake/16#-N4VQkgu0C6vgAWJrqSL:-N4Z3bnf5a0QA_IwxD7C:b-896fix) ([raw file](https://github.com/yiminlin-tri/drake/blob/847eb160943ee44fb2bfa2f580b2f9840110c5fc/multibody/fem/mpm-dev/main.cpp#L47)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

It seems like this is writing 1000 frames per second? Did you find a good way to play them back in real time?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-06-14 22:37 UTC, xuchenhan-tri requested changes
Looking good! One major concern in this revision: the particles from different objects are not talking to each other! See below.

> Reviewed 6 of 6 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/16#-:-N4ZM6H-0DHc6XFPFpqd:b-egdkg4)* status: all files reviewed, 2 unresolved discussions (waiting on @yiminlin-tri)

___
*[`multibody/fem/mpm-dev/MPMDriver.cc` line 69 at r6](https://reviewable.io/reviews/yiminlin-tri/drake/16#-N4VN-jx0dioS_5_zW4e:-N4ZLtgj2xgjI4a_R9oH:b-qon1vo) ([raw file](https://github.com/yiminlin-tri/drake/blob/847eb160943ee44fb2bfa2f580b2f9840110c5fc/multibody/fem/mpm-dev/MPMDriver.cc#L69)):*
<details><summary><i>Previously, yiminlin-tri wrote…</i></summary><blockquote>

Oops, the documentation is incorrect, it should be r = argmax [(⌊h/r⌋)^3 >= min_num_particles_per_cell. 
The idea is that we do an uniform sampling in the cell, just like picking the grid point, with grid size r. (⌊h/r⌋)^3 is then the number of particles we can sample. This is an upper bound on the number of sampled particles of Poisson disk sampling.
</blockquote></details>

Got it. Thanks for the explanation.
___
*[`multibody/fem/mpm-dev/MPMDriver.cc` line 12 at r7](https://reviewable.io/reviews/yiminlin-tri/drake/16#-N4ZLiOl-wbc3tntj3OM:-N4ZLiOl-wbc3tntj3ON:b-eqdouw) ([raw file](https://github.com/yiminlin-tri/drake/blob/dd643822c7e64187f32edda850551aafb947e3e7/multibody/fem/mpm-dev/MPMDriver.cc#L12)):*
> ```cpp
>                                       param.solver_param.h,
>                                       param.solver_param.bottom_corner),
>                                 mpm_transfer_(),
> ```

BTW, you don't need this if you just want to invoke the default constructor.
___
*[`multibody/fem/mpm-dev/MPMDriver.cc` line 148 at r7](https://reviewable.io/reviews/yiminlin-tri/drake/16#-N4ZHkMlAZzygK6J3C3F:-N4ZHkMlAZzygK6J3C3G:b-j72uge) ([raw file](https://github.com/yiminlin-tri/drake/blob/dd643822c7e64187f32edda850551aafb947e3e7/multibody/fem/mpm-dev/MPMDriver.cc#L148)):*
> ```cpp
> 
>     // For each object (group of particles)
>     for (size_t i = 0; i < particles_vec_.size(); ++i) {
> ```

I don't think we want to advance the particles this way. There should be exactly one grid and all the particles should be talking to that unique grid. 

It seems like the effect of this code is that each particle would talk to its own copy of the grid. In that case, particles belonging to distinct objects will have no way of knowing the presence of each other.

I think we should have a single Particle object and a single Grid object. Adding multiple objects can be achieved via multiple groups of calls to `Particles::AddParticle()`
___
*[`multibody/fem/mpm-dev/MPMTransfer.cc` line 44 at r7](https://reviewable.io/reviews/yiminlin-tri/drake/16#-N4ZJP20B3kBBkzXk4gN:-N4ZJP20B3kBBkzXk4gO:bkvr13i) ([raw file](https://github.com/yiminlin-tri/drake/blob/dd643822c7e64187f32edda850551aafb947e3e7/multibody/fem/mpm-dev/MPMTransfer.cc#L44)):*
> ```cpp
>         // Put sums of local scratch pads to grid if the current batch is
>         // nonempty
>         if (p_start != p_end) {
> ```

nit, this logic can be moved up to as soon as we detect `batch_sizes_[batch_index_flat] == 0` at the top of the loop.
___
*[`multibody/fem/mpm-dev/main.cpp` line 78 at r7](https://reviewable.io/reviews/yiminlin-tri/drake/16#-N4ZL2ky6nRrX_0RuZDl:-N4ZL2ky6nRrX_0RuZDm:b4dizo7) ([raw file](https://github.com/yiminlin-tri/drake/blob/dd643822c7e64187f32edda850551aafb947e3e7/multibody/fem/mpm-dev/main.cpp#L78)):*
> ```cpp
>     driver->InitializeParticles(level_set_box, pose_box, m_param_box);
>     driver->InitializeParticles(level_set_sphere, pose_sphere, m_param_sphere);
>     driver->DoTimeStepping();
> ```

Nice changes. It'd make an interesting demo if we release two sets of particles from a two inclined planes and let them collide in the valley. 
```
\ O        O /
  \        /
    \    /
      \/
```


<!-- Sent from Reviewable.io -->

2022-06-14 22:54 UTC, yiminlin-tri reviewed
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/16)* status: all files reviewed, 1 unresolved discussion (waiting on @xuchenhan-tri)

___
*[`multibody/fem/mpm-dev/MPMDriver.cc` line 148 at r7](https://reviewable.io/reviews/yiminlin-tri/drake/16#-N4ZHkMlAZzygK6J3C3F:-N4ZODro1uegAOhTZQsY:b-9v3z5p) ([raw file](https://github.com/yiminlin-tri/drake/blob/dd643822c7e64187f32edda850551aafb947e3e7/multibody/fem/mpm-dev/MPMDriver.cc#L148)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I don't think we want to advance the particles this way. There should be exactly one grid and all the particles should be talking to that unique grid. 

It seems like the effect of this code is that each particle would talk to its own copy of the grid. In that case, particles belonging to distinct objects will have no way of knowing the presence of each other.

I think we should have a single Particle object and a single Grid object. Adding multiple objects can be achieved via multiple groups of calls to `Particles::AddParticle()`
</blockquote></details>

Got it. Then I think it will make sense to assign an id to each particle in the Particles class to keep track of which object they are in? Since particles may have different material properties. (We called SortParticles so we cannot keep track of the particles outside of Particles class). 
___
*[`multibody/fem/mpm-dev/main.cpp` line 78 at r7](https://reviewable.io/reviews/yiminlin-tri/drake/16#-N4ZL2ky6nRrX_0RuZDl:-N4ZPa7QBEzpfdpLye3J:b1gpepd) ([raw file](https://github.com/yiminlin-tri/drake/blob/dd643822c7e64187f32edda850551aafb947e3e7/multibody/fem/mpm-dev/main.cpp#L78)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Nice changes. It'd make an interesting demo if we release two sets of particles from a two inclined planes and let them collide in the valley. 
```
\ O        O /
  \        /
    \    /
      \/
```
</blockquote></details>

Sounds good. Since we don't have any collision handling, I assume two sets of particles will merge together in our case?


<!-- Sent from Reviewable.io -->

2022-06-14 22:59 UTC, xuchenhan-tri requested changes
> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/16)* status: all files reviewed, 1 unresolved discussion (waiting on @yiminlin-tri)

___
*[`multibody/fem/mpm-dev/MPMDriver.cc` line 148 at r7](https://reviewable.io/reviews/yiminlin-tri/drake/16#-N4ZHkMlAZzygK6J3C3F:-N4ZQJs4279CaaWhEBU6:btwdi7f) ([raw file](https://github.com/yiminlin-tri/drake/blob/dd643822c7e64187f32edda850551aafb947e3e7/multibody/fem/mpm-dev/MPMDriver.cc#L148)):*
<details><summary><i>Previously, yiminlin-tri wrote…</i></summary><blockquote>

Got it. Then I think it will make sense to assign an id to each particle in the Particles class to keep track of which object they are in? Since particles may have different material properties. (We called SortParticles so we cannot keep track of the particles outside of Particles class). 
</blockquote></details>

I think the easiest way around that is to give each particle its own constitutive model. It'd be relatively cheap too, just two doubles per particle.
___
*[`multibody/fem/mpm-dev/main.cpp` line 78 at r7](https://reviewable.io/reviews/yiminlin-tri/drake/16#-N4ZL2ky6nRrX_0RuZDl:-N4ZR-ZI9aiJbBnkzI0o:b-yg36kx) ([raw file](https://github.com/yiminlin-tri/drake/blob/dd643822c7e64187f32edda850551aafb947e3e7/multibody/fem/mpm-dev/main.cpp#L78)):*
<details><summary><i>Previously, yiminlin-tri wrote…</i></summary><blockquote>

Sounds good. Since we don't have any collision handling, I assume two sets of particles will merge together in our case?
</blockquote></details>

No, MPM has a "built-in" collision handle mechanism -- The particles will feel each other though the shared grid. The compression will induce a separating force.


<!-- Sent from Reviewable.io -->

2022-06-15 00:41 UTC, yiminlin-tri reviewed
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/16)* status: 4 of 13 files reviewed, 1 unresolved discussion (waiting on @xuchenhan-tri)

___
*[`multibody/fem/mpm-dev/MPMDriver.cc` line 148 at r7](https://reviewable.io/reviews/yiminlin-tri/drake/16#-N4ZHkMlAZzygK6J3C3F:-N4ZRbW-42Ts6wd0ee7g:b-fyf3my) ([raw file](https://github.com/yiminlin-tri/drake/blob/dd643822c7e64187f32edda850551aafb947e3e7/multibody/fem/mpm-dev/MPMDriver.cc#L148)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I think the easiest way around that is to give each particle its own constitutive model. It'd be relatively cheap too, just two doubles per particle.
</blockquote></details>

Yes, makes a lot of sense. Thanks for the suggestion!
___
*[`multibody/fem/mpm-dev/main.cpp` line 78 at r7](https://reviewable.io/reviews/yiminlin-tri/drake/16#-N4ZL2ky6nRrX_0RuZDl:-N4ZljrfDNorziHTX7CH:b3mllya) ([raw file](https://github.com/yiminlin-tri/drake/blob/dd643822c7e64187f32edda850551aafb947e3e7/multibody/fem/mpm-dev/main.cpp#L78)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

No, MPM has a "built-in" collision handle mechanism -- The particles will feel each other though the shared grid. The compression will induce a separating force.
</blockquote></details>

Gotcha. I saw it, and I shared the gif via Slack.


<!-- Sent from Reviewable.io -->

2022-06-15 01:32 UTC, xuchenhan-tri requested changes
<img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/> with two nits. Thanks for your patience!

> Reviewed 9 of 9 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/16#-:-N4ZzG4v6PCnDB-hwlHV:b37evwq)* status: all files reviewed, 2 unresolved discussions (waiting on @yiminlin-tri)

___
*[`multibody/fem/mpm-dev/MPMDriver.cc` line 93 at r9](https://reviewable.io/reviews/yiminlin-tri/drake/16#-N4Zyc6V7E9L9qE1_VHK:-N4Zyc6W9OhJxtQPxKE8:bods5kp) ([raw file](https://github.com/yiminlin-tri/drake/blob/a940422f4cc260d14d71843218188fbf1cf8417d/multibody/fem/mpm-dev/MPMDriver.cc#L93)):*
> ```cpp
>     for (int p = 0; p < num_particles; ++p) {
>         const Vector3<double>& xp = particles_positions[p];
>         particles_.AddParticle(xp, init_v, init_m, reference_volume_p,
> ```

nit, We should document the default constitutive model being added in the header where `Particles::AddParticle` is declared.
___
*[`multibody/fem/mpm-dev/MPMDriver.cc` line 117 at r9](https://reviewable.io/reviews/yiminlin-tri/drake/16#-N4ZyEob5HvNNasXPRiH:-N4ZyEob5HvNNasXPRiI:bqcw8mp) ([raw file](https://github.com/yiminlin-tri/drake/blob/a940422f4cc260d14d71843218188fbf1cf8417d/multibody/fem/mpm-dev/MPMDriver.cc#L117)):*
> ```cpp
>             throw std::runtime_error("CFL condition violation");
>         }
>         ++p;
> ```

nit is this unused?


<!-- Sent from Reviewable.io -->

2022-06-15 01:40 UTC, yiminlin-tri reviewed
Not at all. Thanks for reviewing the code carefully! :thumbsup: 

> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/16#-:-N4_-Sd24cl5jAgyBRbj:b-1z48iw)* status: 11 of 13 files reviewed, all discussions resolved (waiting on @xuchenhan-tri)



<!-- Sent from Reviewable.io -->

2022-06-15 01:41 UTC, xuchenhan-tri approved these changes
> Reviewed 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/16)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yiminlin-tri)



<!-- Sent from Reviewable.io -->

2022-06-15 01:42 UTC, merged