Analytic level set class
yiminlin-tri/drake pull request #18
Opened 2022-06-09 01:32 UTC by yiminlin-tri

2022-06-09 01:33 UTC, yiminlin-tri reviewed
+@xuchenhan-tri Thanks!

> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/18#-:-N454ypB8LteCPr95Ulo:b6w1hxi)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @xuchenhan-tri)



<!-- Sent from Reviewable.io -->

2022-06-09 02:06 UTC, yiminlin-tri reviewed
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/18)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @xuchenhan-tri)

___
*[`multibody/fem/mpm-dev/AnalyticLevelSet.h` line 18 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/18#-N45CRZC8-gRjXSEBXdq:-N45CRZC8-gRjXSEBXdr:bbw1963) ([raw file](https://github.com/yiminlin-tri/drake/blob/dbd8ca9e2f2f8c5e92050569edb7b61569ff9031/multibody/fem/mpm-dev/AnalyticLevelSet.h#L18)):*
> ```objc
> 
>     // Return true if the position is in the interiror of the level set.
>     virtual bool InInterior(const Vector3<double>& position) const = 0;
> ```

I also need to add a routine to determine the bounding box of the geometry (for poisson_disk_sampling), will work on it tomorrow


<!-- Sent from Reviewable.io -->

2022-06-09 16:30 UTC, xuchen-han requested changes
Review done. I have some thoughts on design. PTAL.

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/18#-:-N48IFqy5q5UHdPyxAfR:b-m060su)* status: all files reviewed, 2 unresolved discussions (waiting on @xuchenhan-tri and @yiminlin-tri)

___
*[`multibody/fem/mpm-dev/AnalyticLevelSet.h` line 13 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/18#-N48Fsg--kN1cd3pb-Aq:-N48Fsg--kN1cd3pb-Ar:b-kusf3y) ([raw file](https://github.com/yiminlin-tri/drake/blob/dbd8ca9e2f2f8c5e92050569edb7b61569ff9031/multibody/fem/mpm-dev/AnalyticLevelSet.h#L13)):*
> ```objc
> 
> // A base class providing the interface of primitive geometries' level set.
> class AnalyticLevelSet {
> ```

BTW, consider providing a `normal(const Vector3& position)` function to the analytic level sets. In that case, we can use them as boundary conditions (in addition to posed half space that we already support. 

The use case I have in mind is a cylindrical rolling pin. 
___
*[`multibody/fem/mpm-dev/AnalyticLevelSet.h` line 15 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/18#-N48GClr4sWKmu8cO2Sq:-N48GClr4sWKmu8cO2Sr:b-5uf5qh) ([raw file](https://github.com/yiminlin-tri/drake/blob/dbd8ca9e2f2f8c5e92050569edb7b61569ff9031/multibody/fem/mpm-dev/AnalyticLevelSet.h#L15)):*
> ```objc
> class AnalyticLevelSet {
>  public:
>     AnalyticLevelSet(const Vector3<double>& center, double volume);
> ```

Seems to me like the  center` parameter don't belong to the constructor. The definition of center for an arbitrary analytic level set is vague. (How do you define the center if the shape is not symmetrical for example?)
___
*[`multibody/fem/mpm-dev/AnalyticLevelSet.h` line 18 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/18#-N45CRZC8-gRjXSEBXdq:-N48Gkzs-7p828tGVY_6:b-ynxvim) ([raw file](https://github.com/yiminlin-tri/drake/blob/dbd8ca9e2f2f8c5e92050569edb7b61569ff9031/multibody/fem/mpm-dev/AnalyticLevelSet.h#L18)):*
<details><summary><i>Previously, yiminlin-tri wrote…</i></summary><blockquote>

I also need to add a routine to determine the bounding box of the geometry (for poisson_disk_sampling), will work on it tomorrow
</blockquote></details>

Always putting the geometry in reference configuration makes the bounding box easy. For example, rotation changes the bounding box of a box.
___
*[`multibody/fem/mpm-dev/AnalyticLevelSet.h` line 35 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/18#-N48GxIW43o-iafXcw1J:-N48GxIW43o-iafXcw1K:b-jaleuy) ([raw file](https://github.com/yiminlin-tri/drake/blob/dbd8ca9e2f2f8c5e92050569edb7b61569ff9031/multibody/fem/mpm-dev/AnalyticLevelSet.h#L35)):*
> ```objc
>     SphereLevelSet(const Vector3<double>& center, double radius);
> 
>     bool InInterior(const Vector3<double>& position) const;
> ```

BTW, use the `final` keyword to denote that this function overrides a virtual function and cannot be further inherited.
___
*[`multibody/fem/mpm-dev/AnalyticLevelSet.h` line 47 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/18#-N48FUUr8IWqf_A_MuNN:-N48FUUr8IWqf_A_MuNO:bqhte0z) ([raw file](https://github.com/yiminlin-tri/drake/blob/dbd8ca9e2f2f8c5e92050569edb7b61569ff9031/multibody/fem/mpm-dev/AnalyticLevelSet.h#L47)):*
> ```objc
>  public:
>     BoxLevelSet(const Vector3<double>& center, const Vector3<double>& xscale,
>                 const math::RotationMatrix<double>& rotation);
> ```

BTW, IMO, the code would be cleaner if we keep all level sets in the reference configuration, and handle the rotation/translation outside of this class. This gives us more flexibility to move the level sets around. (Again, the use case I have in mind is the boundary condition of a rolling pin).

In that case, we don't need to provide the "center" argument either. However, that means that we'd need to map the position back to the reference configuration before doing the isInside query.


<!-- Sent from Reviewable.io -->

2022-06-09 17:11 UTC, yiminlin-tri reviewed
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/18)* status: all files reviewed, 2 unresolved discussions (waiting on @xuchenhan-tri and @yiminlin-tri)

___
*[`multibody/fem/mpm-dev/AnalyticLevelSet.h` line 47 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/18#-N48FUUr8IWqf_A_MuNN:-N48NoJ6B5x_yH3RXnLY:b-x6qr0o) ([raw file](https://github.com/yiminlin-tri/drake/blob/dbd8ca9e2f2f8c5e92050569edb7b61569ff9031/multibody/fem/mpm-dev/AnalyticLevelSet.h#L47)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, IMO, the code would be cleaner if we keep all level sets in the reference configuration, and handle the rotation/translation outside of this class. This gives us more flexibility to move the level sets around. (Again, the use case I have in mind is the boundary condition of a rolling pin).

In that case, we don't need to provide the "center" argument either. However, that means that we'd need to map the position back to the reference configuration before doing the isInside query.
</blockquote></details>

Yes, makes sense. But how about the scaling? (size of the box, radius of the sphere) I guess it makes more sense to also separate it from this class. 

If I understand correctly, we then can apply a sequence of operations, e.g. translation, rotation, translation and rotation to an object. Then I am curious how we can possibly encapsulate these transformations in a class? Or it is users' responsibility to transfrom the position back to reference configuration and call queries like isInside, get_bounding_box? Especially for get_bounding_box, it is a none trivial routine for boxes, then shall we define a new class TransformedGeometry to include translation, rotation and analytic level set information?


<!-- Sent from Reviewable.io -->

2022-06-09 17:20 UTC, xuchenhan-tri reviewed
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/18)* status: all files reviewed, 2 unresolved discussions (waiting on @yiminlin-tri)

___
*[`multibody/fem/mpm-dev/AnalyticLevelSet.h` line 47 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/18#-N48FUUr8IWqf_A_MuNN:-N48SRJ7EAS6nVTx4LAp:bybzp6x) ([raw file](https://github.com/yiminlin-tri/drake/blob/dbd8ca9e2f2f8c5e92050569edb7b61569ff9031/multibody/fem/mpm-dev/AnalyticLevelSet.h#L47)):*
> Yes, makes sense. But how about the scaling? (size of the box, radius of the sphere) I guess it makes more sense to also separate it from this class.

By reference configuration I didn't mean the "unit" box/sphere etc. I meant the (scaled) box/sphere "centered" at origin. Concretely, that means getting rid of the `center` parameter and the `rotation` parameter.

> If I understand correctly, we then can apply a sequence of operations, e.g. translation, rotation, translation and rotation to an object. Then I am curious how we can possibly encapsulate these transformations in a class?

An arbitrary sequence of translation and rotation can be concatenated into a **single** RigidTransform. 

I see two use cases for the level set class
1. in initialization of particles
2. in boundary conditions.

For 1, the rigid transform can be passed in as a parameter. for example,
`void SampleInAnalyticLevelSets(const LevelSet& ls, const RigidTransform& pose, double density);`

For 2, the rigid transform can be stored in the BoundaryCondition class along with the level set. 
 


<!-- Sent from Reviewable.io -->

2022-06-09 17:25 UTC, yiminlin-tri reviewed
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/18)* status: all files reviewed, 2 unresolved discussions (waiting on @yiminlin-tri)

___
*[`multibody/fem/mpm-dev/AnalyticLevelSet.h` line 47 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/18#-N48FUUr8IWqf_A_MuNN:-N48UKnsDgsqF-1PpK6y:b6hgoe9) ([raw file](https://github.com/yiminlin-tri/drake/blob/dbd8ca9e2f2f8c5e92050569edb7b61569ff9031/multibody/fem/mpm-dev/AnalyticLevelSet.h#L47)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

> Yes, makes sense. But how about the scaling? (size of the box, radius of the sphere) I guess it makes more sense to also separate it from this class.

By reference configuration I didn't mean the "unit" box/sphere etc. I meant the (scaled) box/sphere "centered" at origin. Concretely, that means getting rid of the `center` parameter and the `rotation` parameter.

> If I understand correctly, we then can apply a sequence of operations, e.g. translation, rotation, translation and rotation to an object. Then I am curious how we can possibly encapsulate these transformations in a class?

An arbitrary sequence of translation and rotation can be concatenated into a **single** RigidTransform. 

I see two use cases for the level set class
1. in initialization of particles
2. in boundary conditions.

For 1, the rigid transform can be passed in as a parameter. for example,
`void SampleInAnalyticLevelSets(const LevelSet& ls, const RigidTransform& pose, double density);`

For 2, the rigid transform can be stored in the BoundaryCondition class along with the level set. 
 
</blockquote></details>

Thanks! :thumbsup:  This is very helpful. I also saw I can take the inverse of RigidTransform easily, I will work on the new class design then.


<!-- Sent from Reviewable.io -->

2022-06-09 21:20 UTC, yiminlin-tri reviewed
Revised. And added Cylinder for moving BC. Thanks!

> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/18#-:-N49KZ0Y5bkkQbxyEg-a:b-61j0ry)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @xuchenhan-tri)

___
*[`multibody/fem/mpm-dev/AnalyticLevelSet.h` line 15 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/18#-N48GClr4sWKmu8cO2Sq:-N48ncWrDMlIsC4HQWk0:b-896fix) ([raw file](https://github.com/yiminlin-tri/drake/blob/dbd8ca9e2f2f8c5e92050569edb7b61569ff9031/multibody/fem/mpm-dev/AnalyticLevelSet.h#L15)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Seems to me like the  center` parameter don't belong to the constructor. The definition of center for an arbitrary analytic level set is vague. (How do you define the center if the shape is not symmetrical for example?)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-06-09 22:01 UTC, xuchenhan-tri requested changes
I made another pass -- we want the normals at least in the interior of the level sets, not just at the boundary.

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/18#-:-N49Tvwr8N3DrBD7zxUG:b-l6t7q6)* status: all files reviewed, 4 unresolved discussions (waiting on @yiminlin-tri)

___
*[`multibody/fem/mpm-dev/AnalyticLevelSet.h` line 27 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/18#-N49QEy-4Ps8kyzIegzW:-N49QEy-4Ps8kyzIegzX:b-n2l4tq) ([raw file](https://github.com/yiminlin-tri/drake/blob/6a873cb1848b1c248796414d6a54ae937d195763/multibody/fem/mpm-dev/AnalyticLevelSet.h#L27)):*
> ```objc
> 
>     // Return the outward unit normal of the analytic level set,
>     // return 0 if the position is in the interior or outside of the object
> ```

This is surprising to me -- I believe we still want the normal at least in the interior of the geometry.

Remember the intended use case is to provide normals in boundary conditions, and we need to enforce the BC in the interior of the collision geometry.

We should also think about what to return at singularities with that application in mind.
___
*[`multibody/fem/mpm-dev/AnalyticLevelSet.h` line 65 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/18#-N49TMbo9ZhzV6TzgZKi:-N49TMbo9ZhzV6TzgZKj:bek2qsr) ([raw file](https://github.com/yiminlin-tri/drake/blob/6a873cb1848b1c248796414d6a54ae937d195763/multibody/fem/mpm-dev/AnalyticLevelSet.h#L65)):*
> ```objc
> class BoxLevelSet : public AnalyticLevelSet {
>  public:
>     explicit BoxLevelSet(const Vector3<double>& xscale);
> ```

@pre Each entry in `xscale` is positive.
___
*[`multibody/fem/mpm-dev/AnalyticLevelSet.cc` line 24 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/18#-N49RLlT-PWXdMep4Uvi:-N49RLlT-PWXdMep4Uvj:b-pznyi0) ([raw file](https://github.com/yiminlin-tri/drake/blob/6a873cb1848b1c248796414d6a54ae937d195763/multibody/fem/mpm-dev/AnalyticLevelSet.cc#L24)):*
> ```cpp
>                                     {{-radius*Vector3<double>::Ones(),
>                                        radius*Vector3<double>::Ones()}}),
>                     radius_(radius) {}
> ```

DRAKE_DEMAND(radius > 0);
___
*[`multibody/fem/mpm-dev/AnalyticLevelSet.cc` line 31 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/18#-N49RXxbA3pQnVEphHz7:-N49RXxbA3pQnVEphHz8:b-gw2itz) ([raw file](https://github.com/yiminlin-tri/drake/blob/6a873cb1848b1c248796414d6a54ae937d195763/multibody/fem/mpm-dev/AnalyticLevelSet.cc#L31)):*
> ```cpp
> 
> Vector3<double> SphereLevelSet::Normal(const Vector3<double>& position) const {
>     if (position.norm() == radius_) {
> ```

This should probably be 
```
if (position.norm() == 0) {
return Vec3::Zero();
}
return position.normalized();
```
instead.


<!-- Sent from Reviewable.io -->

2022-06-09 22:06 UTC, yiminlin-tri reviewed
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/18)* status: all files reviewed, 4 unresolved discussions (waiting on @xuchenhan-tri and @yiminlin-tri)

___
*[`multibody/fem/mpm-dev/AnalyticLevelSet.h` line 27 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/18#-N49QEy-4Ps8kyzIegzW:-N49Uf-l-TTGJxXZlY2i:b-pg84hf) ([raw file](https://github.com/yiminlin-tri/drake/blob/6a873cb1848b1c248796414d6a54ae937d195763/multibody/fem/mpm-dev/AnalyticLevelSet.h#L27)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

This is surprising to me -- I believe we still want the normal at least in the interior of the geometry.

Remember the intended use case is to provide normals in boundary conditions, and we need to enforce the BC in the interior of the collision geometry.

We should also think about what to return at singularities with that application in mind.
</blockquote></details>

Sure - but what defines a "normal" in the interior of the geometry? For sphere and cylinder it is possible to construct an artificial one. But I am not too sure about the "interior normal" of the box. Do you have any advice on this?


<!-- Sent from Reviewable.io -->

2022-06-09 22:10 UTC, xuchenhan-tri requested changes
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/18)* status: all files reviewed, 4 unresolved discussions (waiting on @yiminlin-tri)

___
*[`multibody/fem/mpm-dev/AnalyticLevelSet.h` line 27 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/18#-N49QEy-4Ps8kyzIegzW:-N49VYac8L5YSMEcNQdI:bg6lmoe) ([raw file](https://github.com/yiminlin-tri/drake/blob/6a873cb1848b1c248796414d6a54ae937d195763/multibody/fem/mpm-dev/AnalyticLevelSet.h#L27)):*
<details><summary><i>Previously, yiminlin-tri wrote…</i></summary><blockquote>

Sure - but what defines a "normal" in the interior of the geometry? For sphere and cylinder it is possible to construct an artificial one. But I am not too sure about the "interior normal" of the box. Do you have any advice on this?
</blockquote></details>

Again, I'd think in terms of why we need  `normal()` -- for the normal direction of the contact for BC. To me, it makes sense to define it as the gradient of signed distance function to the level set. WDYT?


<!-- Sent from Reviewable.io -->

2022-06-09 22:12 UTC, yiminlin-tri commented
*[`multibody/fem/mpm-dev/AnalyticLevelSet.h` line 27 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/18#-N49QEy-4Ps8kyzIegzW:-N49W0Io3ovSk2Xjk29N:b-bsdgfb) ([raw file](https://github.com/yiminlin-tri/drake/blob/6a873cb1848b1c248796414d6a54ae937d195763/multibody/fem/mpm-dev/AnalyticLevelSet.h#L27)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Again, I'd think in terms of why we need  `normal()` -- for the normal direction of the contact for BC. To me, it makes sense to define it as the gradient of signed distance function to the level set. WDYT?
</blockquote></details>

OK, I can see the natural extension by viewing the box as 6 cones. I am not too experienced in the collision handling though. I imagine we define these interior normal so we can push the particles inside the object along these artificial interior normals?


<!-- Sent from Reviewable.io -->

2022-06-09 22:16 UTC, xuchenhan-tri requested changes
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/18)* status: all files reviewed, 4 unresolved discussions (waiting on @yiminlin-tri)

___
*[`multibody/fem/mpm-dev/AnalyticLevelSet.h` line 27 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/18#-N49QEy-4Ps8kyzIegzW:-N49XCZW01Wrpr1Aet7O:b-593e4v) ([raw file](https://github.com/yiminlin-tri/drake/blob/6a873cb1848b1c248796414d6a54ae937d195763/multibody/fem/mpm-dev/AnalyticLevelSet.h#L27)):*
<details><summary><i>Previously, yiminlin-tri wrote…</i></summary><blockquote>

OK, I can see the natural extension by viewing the box as 6 cones. I am not too experienced in the collision handling though. I imagine we define these interior normal so we can push the particles inside the object along these artificial interior normals?
</blockquote></details>

We are pushing the particles **out of** the object. 

We normally want to apply the BC in the entire interior of the collision objects. No grid node will ever fall exactly on the boundary of the collision object.


<!-- Sent from Reviewable.io -->

2022-06-09 22:28 UTC, yiminlin-tri commented
*[`multibody/fem/mpm-dev/AnalyticLevelSet.h` line 27 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/18#-N49QEy-4Ps8kyzIegzW:-N49_CIMBNjJtNichUwx:bs7sx39) ([raw file](https://github.com/yiminlin-tri/drake/blob/6a873cb1848b1c248796414d6a54ae937d195763/multibody/fem/mpm-dev/AnalyticLevelSet.h#L27)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

We are pushing the particles **out of** the object. 

We normally want to apply the BC in the entire interior of the collision objects. No grid node will ever fall exactly on the boundary of the collision object.
</blockquote></details>

Yes, I got what you mean. Thanks!


<!-- Sent from Reviewable.io -->

2022-06-09 23:29 UTC, yiminlin-tri reviewed
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/18)* status: all files reviewed, 4 unresolved discussions (waiting on @pre and @xuchenhan-tri)

___
*[`multibody/fem/mpm-dev/AnalyticLevelSet.h` line 65 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/18#-N49TMbo9ZhzV6TzgZKi:-N49VXtt6RA8LB5YUYAK:b-896fix) ([raw file](https://github.com/yiminlin-tri/drake/blob/6a873cb1848b1c248796414d6a54ae937d195763/multibody/fem/mpm-dev/AnalyticLevelSet.h#L65)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

@pre Each entry in `xscale` is positive.
</blockquote></details>

Done.
___
*[`multibody/fem/mpm-dev/AnalyticLevelSet.cc` line 24 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/18#-N49RLlT-PWXdMep4Uvi:-N49ViMq9Inkjr5csuf3:b-896fix) ([raw file](https://github.com/yiminlin-tri/drake/blob/6a873cb1848b1c248796414d6a54ae937d195763/multibody/fem/mpm-dev/AnalyticLevelSet.cc#L24)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

DRAKE_DEMAND(radius > 0);
</blockquote></details>

Done.
___
*[`multibody/fem/mpm-dev/AnalyticLevelSet.cc` line 31 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/18#-N49RXxbA3pQnVEphHz7:-N49X6Jk4a4RraTH47lm:b-896fix) ([raw file](https://github.com/yiminlin-tri/drake/blob/6a873cb1848b1c248796414d6a54ae937d195763/multibody/fem/mpm-dev/AnalyticLevelSet.cc#L31)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

This should probably be 
```
if (position.norm() == 0) {
return Vec3::Zero();
}
return position.normalized();
```
instead.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-06-10 00:27 UTC, xuchenhan-tri requested changes
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/18)* status: all files reviewed, 5 unresolved discussions (waiting on @yiminlin-tri)

___
*[`multibody/fem/mpm-dev/AnalyticLevelSet.h` line 27 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/18#-N49QEy-4Ps8kyzIegzW:-N49xggb5GMjCjhDKVbh:b122cno) ([raw file](https://github.com/yiminlin-tri/drake/blob/6a873cb1848b1c248796414d6a54ae937d195763/multibody/fem/mpm-dev/AnalyticLevelSet.h#L27)):*
<details><summary><i>Previously, yiminlin-tri wrote…</i></summary><blockquote>

Yes, I got what you mean. Thanks!
</blockquote></details>

The documentation should state what happens outside of the levelset and at singularities.
Perhaps it's better to throw outside and try to provide a reasonable value at singularities (like you do with boxes)? WDYT?
___
*[`multibody/fem/mpm-dev/AnalyticLevelSet.h` line 74 at r3](https://reviewable.io/reviews/yiminlin-tri/drake/18#-N49xqpS7ffheAISPgP0:-N49xqpS7ffheAISPgP1:b-duhnnv) ([raw file](https://github.com/yiminlin-tri/drake/blob/7d8481a69e4eea772ee4c0d0c20e98cd8616379b/multibody/fem/mpm-dev/AnalyticLevelSet.h#L74)):*
> ```objc
> // each face of the box. For any point inside the box, we define its
> // interior normal as the outward normal of the closest face normal relative to
> // other faces. This is equivalently the face of the pyramid this point is in.
> ```

I think this description is not accurate. Decomposition according to medial-axis doesn't always give 6 pyramids. It only applies when the box is a cube. See https://github.com/RobotLocomotion/drake/blob/master/geometry/proximity/make_box_mesh.cc for discussion of the various cases. 
___
*[`multibody/fem/mpm-dev/AnalyticLevelSet.h` line 99 at r3](https://reviewable.io/reviews/yiminlin-tri/drake/18#-N49yime6AjxnJyiz-pw:-N49yime6AjxnJyiz-px:b-h5o8gd) ([raw file](https://github.com/yiminlin-tri/drake/blob/7d8481a69e4eea772ee4c0d0c20e98cd8616379b/multibody/fem/mpm-dev/AnalyticLevelSet.h#L99)):*
> ```objc
> // parallel to z-axis. The level set can be parametetrized as [rcosθ, rsinθ, z],
> // where r is the radius given, and z ∈ [-height, height].
> // For all interior points, the normal is defined as the vector from its
> ```

BTW, I'm not sure ignoring the lid is a good idea. But since it should be ok for the rolling pin demo, I won't block.
___
*[`multibody/fem/mpm-dev/AnalyticLevelSet.cc` line 33 at r3](https://reviewable.io/reviews/yiminlin-tri/drake/18#-N49zS929Mz8CsJ5T9bx:-N49zS929Mz8CsJ5T9by:b-fjjo8j) ([raw file](https://github.com/yiminlin-tri/drake/blob/7d8481a69e4eea772ee4c0d0c20e98cd8616379b/multibody/fem/mpm-dev/AnalyticLevelSet.cc#L33)):*
> ```cpp
> 
> Vector3<double> SphereLevelSet::Normal(const Vector3<double>& position) const {
>     if (position.norm() == 0 || !InInterior(position)) {
> ```

This is inconsistent with what you do with boxes and cylinders (where a continuation attempt is made when the signdistancefield is non-differentiatiable. Perhaps we could do that here as well? i.e. return something like (1,0,0).
___
*[`multibody/fem/mpm-dev/AnalyticLevelSet.cc` line 56 at r3](https://reviewable.io/reviews/yiminlin-tri/drake/18#-N49wVt88gu086FFU_MJ:-N49wVt88gu086FFU_MK:b-q4csw4) ([raw file](https://github.com/yiminlin-tri/drake/blob/7d8481a69e4eea772ee4c0d0c20e98cd8616379b/multibody/fem/mpm-dev/AnalyticLevelSet.cc#L56)):*
> ```cpp
> Vector3<double> BoxLevelSet::Normal(const Vector3<double>& position) const {
>     if (InInterior(position)) {
>         double dist_left   = (position(0) + xscale_(0))/xscale_(0)/2;
> ```

I don't understand why we are dividing by (xscale * 2). Could you explain?
___
*[`multibody/fem/mpm-dev/AnalyticLevelSet.cc` line 77 at r3](https://reviewable.io/reviews/yiminlin-tri/drake/18#-N49xSnt7s2ncB715ail:-N49xSnt7s2ncB715aim:bno0rwv) ([raw file](https://github.com/yiminlin-tri/drake/blob/7d8481a69e4eea772ee4c0d0c20e98cd8616379b/multibody/fem/mpm-dev/AnalyticLevelSet.cc#L77)):*
> ```cpp
>         if (min_dist == dist_top)
>                             { return Vector3<double>{0.0, 0.0, 1.0}; }
>         return Vector3<double>::Zero();
> ```

nit This can be DRAKE_UNREACHABLE();
___
*[`multibody/fem/mpm-dev/AnalyticLevelSet.cc` line 100 at r3](https://reviewable.io/reviews/yiminlin-tri/drake/18#-N4A--258vNXDC2IJxZT:-N4A--258vNXDC2IJxZU:bjihgwg) ([raw file](https://github.com/yiminlin-tri/drake/blob/7d8481a69e4eea772ee4c0d0c20e98cd8616379b/multibody/fem/mpm-dev/AnalyticLevelSet.cc#L100)):*
> ```cpp
>                                                                         const {
>     if (InInterior(position)) {
>         double d_squared = position(0)*position(0) + position(1)*position(1);
> ```

BTW, consider

```
Vector3 projection_xy(position(0), position(1), 0);
if (projection_xy.norm() == 0) return Vector3(1,0,0);
return projection_xy.normalized();
```


<!-- Sent from Reviewable.io -->

2022-06-10 00:50 UTC, yiminlin-tri reviewed
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/18)* status: all files reviewed, 4 unresolved discussions (waiting on @xuchenhan-tri)

___
*[`multibody/fem/mpm-dev/AnalyticLevelSet.h` line 27 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/18#-N49QEy-4Ps8kyzIegzW:-N4A4WHX8mxbFGPV2ZOe:b-896fix) ([raw file](https://github.com/yiminlin-tri/drake/blob/6a873cb1848b1c248796414d6a54ae937d195763/multibody/fem/mpm-dev/AnalyticLevelSet.h#L27)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

The documentation should state what happens outside of the levelset and at singularities.
Perhaps it's better to throw outside and try to provide a reasonable value at singularities (like you do with boxes)? WDYT?
</blockquote></details>

Done.
___
*[`multibody/fem/mpm-dev/AnalyticLevelSet.h` line 74 at r3](https://reviewable.io/reviews/yiminlin-tri/drake/18#-N49xqpS7ffheAISPgP0:-N4A2LRc4eeqEXRvWTVY:b-635p4v) ([raw file](https://github.com/yiminlin-tri/drake/blob/7d8481a69e4eea772ee4c0d0c20e98cd8616379b/multibody/fem/mpm-dev/AnalyticLevelSet.h#L74)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I think this description is not accurate. Decomposition according to medial-axis doesn't always give 6 pyramids. It only applies when the box is a cube. See https://github.com/RobotLocomotion/drake/blob/master/geometry/proximity/make_box_mesh.cc for discussion of the various cases. 
</blockquote></details>

I guess what I mean is the shape formed by connect faces with the origin (0, 0, 0), 
___
*[`multibody/fem/mpm-dev/AnalyticLevelSet.h` line 99 at r3](https://reviewable.io/reviews/yiminlin-tri/drake/18#-N49yime6AjxnJyiz-pw:-N4A3Ds08Kvr5wVrNKxT:blqyobi) ([raw file](https://github.com/yiminlin-tri/drake/blob/7d8481a69e4eea772ee4c0d0c20e98cd8616379b/multibody/fem/mpm-dev/AnalyticLevelSet.h#L99)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, I'm not sure ignoring the lid is a good idea. But since it should be ok for the rolling pin demo, I won't block.
</blockquote></details>

If not ignoring the lid, what is a natural way to define the interior normal?
___
*[`multibody/fem/mpm-dev/AnalyticLevelSet.cc` line 33 at r3](https://reviewable.io/reviews/yiminlin-tri/drake/18#-N49zS929Mz8CsJ5T9bx:-N4A3Sjp0Qkp7EpP7MGe:b-896fix) ([raw file](https://github.com/yiminlin-tri/drake/blob/7d8481a69e4eea772ee4c0d0c20e98cd8616379b/multibody/fem/mpm-dev/AnalyticLevelSet.cc#L33)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

This is inconsistent with what you do with boxes and cylinders (where a continuation attempt is made when the signdistancefield is non-differentiatiable. Perhaps we could do that here as well? i.e. return something like (1,0,0).
</blockquote></details>

Done.
___
*[`multibody/fem/mpm-dev/AnalyticLevelSet.cc` line 56 at r3](https://reviewable.io/reviews/yiminlin-tri/drake/18#-N49wVt88gu086FFU_MJ:-N4A0QILE21LhP9pd_XO:b-xh5153) ([raw file](https://github.com/yiminlin-tri/drake/blob/7d8481a69e4eea772ee4c0d0c20e98cd8616379b/multibody/fem/mpm-dev/AnalyticLevelSet.cc#L56)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I don't understand why we are dividing by (xscale * 2). Could you explain?
</blockquote></details>

Oh, I think I should remove / 2 here - But the main idea is to "normalized" the distance to faces.
e.g.
          top
o ------------------o
|                  x   |          right
|                       |
o-------------------o
x shall have normal (1, 0), since it is relatively closer to the right face than the top face. If we don't normalize, x will have normal (0, 1).


<!-- Sent from Reviewable.io -->

2022-06-10 01:23 UTC, xuchenhan-tri requested changes
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/18)* status: all files reviewed, 2 unresolved discussions (waiting on @yiminlin-tri)

___
*[`multibody/fem/mpm-dev/AnalyticLevelSet.h` line 74 at r3](https://reviewable.io/reviews/yiminlin-tri/drake/18#-N49xqpS7ffheAISPgP0:-N4AC8YNCJYXC9cmhZAg:bum5gnn) ([raw file](https://github.com/yiminlin-tri/drake/blob/7d8481a69e4eea772ee4c0d0c20e98cd8616379b/multibody/fem/mpm-dev/AnalyticLevelSet.h#L74)):*
<details><summary><i>Previously, yiminlin-tri wrote…</i></summary><blockquote>

I guess what I mean is the shape formed by connect faces with the origin (0, 0, 0), 
</blockquote></details>

We shouldn't be connecting faces to (0,0,0) (unless the box is a cube).
___
*[`multibody/fem/mpm-dev/AnalyticLevelSet.h` line 99 at r3](https://reviewable.io/reviews/yiminlin-tri/drake/18#-N49yime6AjxnJyiz-pw:-N4ABUaa-8DyO1qh8PlS:br4ns7q) ([raw file](https://github.com/yiminlin-tri/drake/blob/7d8481a69e4eea772ee4c0d0c20e98cd8616379b/multibody/fem/mpm-dev/AnalyticLevelSet.h#L99)):*
<details><summary><i>Previously, yiminlin-tri wrote…</i></summary><blockquote>

If not ignoring the lid, what is a natural way to define the interior normal?
</blockquote></details>

The normal should be pointing in the direction of the gradient of the sign distance field. 
___
*[`multibody/fem/mpm-dev/AnalyticLevelSet.cc` line 56 at r3](https://reviewable.io/reviews/yiminlin-tri/drake/18#-N49wVt88gu086FFU_MJ:-N4ABSDTECvLIoSIUOyR:bp5jkd6) ([raw file](https://github.com/yiminlin-tri/drake/blob/7d8481a69e4eea772ee4c0d0c20e98cd8616379b/multibody/fem/mpm-dev/AnalyticLevelSet.cc#L56)):*
<details><summary><i>Previously, yiminlin-tri wrote…</i></summary><blockquote>

Oh, I think I should remove / 2 here - But the main idea is to "normalized" the distance to faces.
e.g.
          top
o ------------------o
|                  x   |          right
|                       |
o-------------------o
x shall have normal (1, 0), since it is relatively closer to the right face than the top face. If we don't normalize, x will have normal (0, 1).
</blockquote></details>

The normal should point in the direction of the gradient of the signed distance field (sdf). If you write down the sdf for a rectangular box (where the side lengths are all different) and work out the gradient, I believe it should involve a division of xscale. We can discuss f2f if this is not clear.


<!-- Sent from Reviewable.io -->

2022-06-10 01:42 UTC, yiminlin-tri reviewed
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/18)* status: all files reviewed, 2 unresolved discussions (waiting on @xuchenhan-tri and @yiminlin-tri)

___
*[`multibody/fem/mpm-dev/AnalyticLevelSet.cc` line 56 at r3](https://reviewable.io/reviews/yiminlin-tri/drake/18#-N49wVt88gu086FFU_MJ:-N4A5oNK3WgPa3n6LVbP:b9fxxdk) ([raw file](https://github.com/yiminlin-tri/drake/blob/7d8481a69e4eea772ee4c0d0c20e98cd8616379b/multibody/fem/mpm-dev/AnalyticLevelSet.cc#L56)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

The normal should point in the direction of the gradient of the signed distance field (sdf). If you write down the sdf for a rectangular box (where the side lengths are all different) and work out the gradient, I believe it should involve a division of xscale. We can discuss f2f if this is not clear.
</blockquote></details>

I understand what you mean now, the resulting expression seems not trivial... I will think about it a little bit. Thanks!


<!-- Sent from Reviewable.io -->

2022-06-10 01:44 UTC, xuchenhan-tri requested changes
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/18)* status: all files reviewed, 2 unresolved discussions (waiting on @yiminlin-tri)

___
*[`multibody/fem/mpm-dev/AnalyticLevelSet.cc` line 56 at r3](https://reviewable.io/reviews/yiminlin-tri/drake/18#-N49wVt88gu086FFU_MJ:-N4AH4E68rEzA_LstR5T:blhnyil) ([raw file](https://github.com/yiminlin-tri/drake/blob/7d8481a69e4eea772ee4c0d0c20e98cd8616379b/multibody/fem/mpm-dev/AnalyticLevelSet.cc#L56)):*
<details><summary><i>Previously, yiminlin-tri wrote…</i></summary><blockquote>

I understand what you mean now, the resulting expression seems not trivial... I will think about it a little bit. Thanks!
</blockquote></details>

Hmm, I think removing the division by xscale should be enough, right?


<!-- Sent from Reviewable.io -->

2022-06-13 17:51 UTC, yiminlin-tri reviewed
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/18)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @xuchenhan-tri)

___
*[`multibody/fem/mpm-dev/AnalyticLevelSet.h` line 74 at r3](https://reviewable.io/reviews/yiminlin-tri/drake/18#-N49xqpS7ffheAISPgP0:-N4T89lP-lJe6_G8pihj:b-wsvasg) ([raw file](https://github.com/yiminlin-tri/drake/blob/7d8481a69e4eea772ee4c0d0c20e98cd8616379b/multibody/fem/mpm-dev/AnalyticLevelSet.h#L74)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

We shouldn't be connecting faces to (0,0,0) (unless the box is a cube).
</blockquote></details>

Thanks for the explanation!
___
*[`multibody/fem/mpm-dev/AnalyticLevelSet.cc` line 56 at r3](https://reviewable.io/reviews/yiminlin-tri/drake/18#-N49wVt88gu086FFU_MJ:-N4T8QidDdmEE2gYEfpU:b-v7fd3o) ([raw file](https://github.com/yiminlin-tri/drake/blob/7d8481a69e4eea772ee4c0d0c20e98cd8616379b/multibody/fem/mpm-dev/AnalyticLevelSet.cc#L56)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Hmm, I think removing the division by xscale should be enough, right?
</blockquote></details>

Yes, I just worked on the math, I overcomplicate it.


<!-- Sent from Reviewable.io -->

2022-06-13 18:08 UTC, xuchenhan-tri requested changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> with a few more thoughts. 

> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/18#-:-N4TEIqa8hhwvFus5Qd1:b-avbg63)* status: all files reviewed, 3 unresolved discussions (waiting on @yiminlin-tri)

___
*[`multibody/fem/mpm-dev/AnalyticLevelSet.h` line 27 at r5](https://reviewable.io/reviews/yiminlin-tri/drake/18#-N4TEOU74zUpnCKDLddA:-N4TEOU74zUpnCKDLddB:bve36br) ([raw file](https://github.com/yiminlin-tri/drake/blob/b790c5b140c479f307134e15a69988fd7c4e6b08/multibody/fem/mpm-dev/AnalyticLevelSet.h#L27)):*
> ```objc
> 
>     // Return the outward unit normal of the interior of the analytic level set.
>     // Return zero vector for positions outside of the geometry.
> ```

This is not true. You are returning (1,0,0) for positions outside of the geometry for sphere. 

My recommendation is to throw instead of returning zero when `position` is outside the level set. 

Instead of returning an arbitrary value so that the error shows up in some inscrutable downstream calculations, it is often far more desirable to "fail fast".
___
*[`multibody/fem/mpm-dev/AnalyticLevelSet.cc` line 43 at r5](https://reviewable.io/reviews/yiminlin-tri/drake/18#-N4TDi-W3-m52pTDoK86:-N4TDi-W3-m52pTDoK87:b-fa2wot) ([raw file](https://github.com/yiminlin-tri/drake/blob/b790c5b140c479f307134e15a69988fd7c4e6b08/multibody/fem/mpm-dev/AnalyticLevelSet.cc#L43)):*
> ```cpp
>                                     {{-xscale, xscale}}),
>                     xscale_(xscale) {
>     DRAKE_ASSERT(xscale_(0) >= 0);
> ```

We should assert `xscale_(0) > 0` (according to the documentation of the constructor).
___
*[`multibody/fem/mpm-dev/AnalyticLevelSet.cc` line 88 at r5](https://reviewable.io/reviews/yiminlin-tri/drake/18#-N4TDtsO8PRZtnKWeel6:-N4TDtsO8PRZtnKWeel7:bttfbr9) ([raw file](https://github.com/yiminlin-tri/drake/blob/b790c5b140c479f307134e15a69988fd7c4e6b08/multibody/fem/mpm-dev/AnalyticLevelSet.cc#L88)):*
> ```cpp
>                                               { radius,  radius,  height}}}),
>                                             height_(height), radius_(radius) {
>     DRAKE_DEMAND(radius > 0);
> ```

Also DRAKE_DEMAND(height>0)?

Also, it's a good habit to document the requirement/precondition we impose in the documentation of the header. 


<!-- Sent from Reviewable.io -->

2022-06-13 18:59 UTC, yiminlin-tri reviewed
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/18)* status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @xuchenhan-tri)

___
*[`multibody/fem/mpm-dev/AnalyticLevelSet.h` line 27 at r5](https://reviewable.io/reviews/yiminlin-tri/drake/18#-N4TEOU74zUpnCKDLddA:-N4TNEm4Dy9Azek9eVhV:b-896fix) ([raw file](https://github.com/yiminlin-tri/drake/blob/b790c5b140c479f307134e15a69988fd7c4e6b08/multibody/fem/mpm-dev/AnalyticLevelSet.h#L27)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

This is not true. You are returning (1,0,0) for positions outside of the geometry for sphere. 

My recommendation is to throw instead of returning zero when `position` is outside the level set. 

Instead of returning an arbitrary value so that the error shows up in some inscrutable downstream calculations, it is often far more desirable to "fail fast".
</blockquote></details>

Done.
___
*[`multibody/fem/mpm-dev/AnalyticLevelSet.cc` line 43 at r5](https://reviewable.io/reviews/yiminlin-tri/drake/18#-N4TDi-W3-m52pTDoK86:-N4TPTiN5O9prZhZNC1q:b-896fix) ([raw file](https://github.com/yiminlin-tri/drake/blob/b790c5b140c479f307134e15a69988fd7c4e6b08/multibody/fem/mpm-dev/AnalyticLevelSet.cc#L43)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

We should assert `xscale_(0) > 0` (according to the documentation of the constructor).
</blockquote></details>

Done.
___
*[`multibody/fem/mpm-dev/AnalyticLevelSet.cc` line 88 at r5](https://reviewable.io/reviews/yiminlin-tri/drake/18#-N4TDtsO8PRZtnKWeel6:-N4TQAJC3eGH1XJ2v994:b-896fix) ([raw file](https://github.com/yiminlin-tri/drake/blob/b790c5b140c479f307134e15a69988fd7c4e6b08/multibody/fem/mpm-dev/AnalyticLevelSet.cc#L88)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Also DRAKE_DEMAND(height>0)?

Also, it's a good habit to document the requirement/precondition we impose in the documentation of the header. 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-06-13 19:08 UTC, xuchenhan-tri approved these changes
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/18)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yiminlin-tri)



<!-- Sent from Reviewable.io -->

2022-06-13 19:09 UTC, merged