[mpm-dev] Moving Cylindrical Boundary Condition
yiminlin-tri/drake pull request #19
Opened 2022-06-16 00:01 UTC by yiminlin-tri

2022-06-16 00:03 UTC, yiminlin-tri reviewed
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/19)* status: 0 of 10 files reviewed, 1 unresolved discussion

___
*[`multibody/fem/mpm-dev/BoundaryCondition.cc` line 95 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/19#-N4doazT86lhZAsZ2bFq:-N4doazT86lhZAsZ2bFr:b-vqvzl0) ([raw file](https://github.com/yiminlin-tri/drake/blob/8389c061362ba739a0142257ae8e0206e43ae422/multibody/fem/mpm-dev/BoundaryCondition.cc#L95)):*
> ```cpp
>                             moving_cyl_boundary.pose.rotation().inverse()
>                            *(*velocity-moving_cyl_boundary.velocity);
>             // Normal and tangential components of the reference frame velocity
> ```

Refactor with above


<!-- Sent from Reviewable.io -->

2022-06-16 00:20 UTC, yiminlin-tri reviewed
+@xuchenhan-tri Thanks!

> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/19#-:-N4dsJFq0jbei2tuVPDL:b6w1hxi)* status: 0 of 10 files reviewed, all discussions resolved (waiting on @xuchenhan-tri)



<!-- Sent from Reviewable.io -->

2022-06-16 01:02 UTC, xuchenhan-tri requested changes
> Reviewed 5 of 10 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/19)* status: 7 of 10 files reviewed, 6 unresolved discussions (waiting on @xuchenhan-tri and @yiminlin-tri)

*[a discussion](https://reviewable.io/reviews/yiminlin-tri/drake/19#-N4ds5lS9qXzyxsUNjdF:-N4ds5lS9qXzyxsUNjdG:bwf0uja) (no related file):*
I made a quick pass through the non-testing code. A couple of thoughts.

1. We shouldn't be passing the current time `t` around, all the way to the driver. Instead, we should keep the state of the collision objects locally.
2. I see that we are spamming public functions in the boundary conditions a little bit. I think we can clean that up nicely. See below.

___
___
*[`multibody/fem/mpm-dev/BoundaryCondition.h` line 24 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/19#-N4dthCABZc68hxZPSgn:-N4dthCABZc68hxZPSgo:b-6jfoea) ([raw file](https://github.com/yiminlin-tri/drake/blob/21e401ae7c40a083dad4ecb8afdf46bed6275232/multibody/fem/mpm-dev/BoundaryCondition.h#L24)):*
> ```objc
> // ================================================================ wall
> //                                           (inside of halfspace, dist < 0)
> class BoundaryCondition {
> ```

Now that we are supporting moving bcs, perhaps we should update the name as well? What about `KinematicCollisionObjects`. It emphasizes 
1. the motion is kinematically prescribed, and 
2. plurality.
___
*[`multibody/fem/mpm-dev/BoundaryCondition.h` line 34 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/19#-N4du6uh0WgwKsQcyzBx:-N4du6uh0WgwKsQcyzBy:bsav2vx) ([raw file](https://github.com/yiminlin-tri/drake/blob/21e401ae7c40a083dad4ecb8afdf46bed6275232/multibody/fem/mpm-dev/BoundaryCondition.h#L34)):*
> ```objc
>     // described through the cylinder level set and pose. We assume the cylinder
>     // is moving with constant velocity in the physical (canonical) frame.
>     struct MovingCylindricalBoundary {
> ```

With more than one type of bc/collision object, it think it makes sense to reorganize some functionalities into common functions It would help clean up the API of BoundaryCondition/KinematicCollisionObjects. 

Here's what I have in mind, see if you like it:

```
// Renamed from BoundaryCondition, stored in the driver.
class KinematicCollisionObjects {
public:
  // Add a new collision object.
  void AddCollisionObject(std::unique_ptr<CollisionObject> obj);

  // Retrieve a collision object by index.
  const CollisionObject& get_collision_object(int index) const;

  // Advance the state of all collision objects by dt.
  void AdvanceOneTimeStep(double dt);

  // Apply boundary conditions for all collision objects.
  void ApplyBoundaryConditions(const Vector3<double>& position, Vector3<double>* velocity) const;
};

//  Consolidate WallBoundary and MovingCylindricalBoundary into a single class
class CollisionObject {
public:
  struct CollisionObjectState {
    math::RigidTransformd pose;
    // This lets us add in rotation as well for rolling pin.
    math::SpatialVelocityd spatial_velocity;
  };

  // Construct a new collision object with level set and prescribed initial_state
  CollisionObject(std::unique_ptr<AnalyticLevelSet> level_set, CollisionObjectState initial_state, double friction_coeff);

  // Advance the state of this collision object by dt.
  AdvanceOneTimeStep(double dt);
  
  // Apply the bc prescribed by this object.
  void ApplyBoundaryCondition(const Vector3<double>& position, Vector3<double>* velocity) const;
};
```
This gives you flexibility to add new shapes as the become necessary and reduces some repetitive pattern in BoundaryCondition.h/cc that's tarting to emerge.

This of course would require some modification on the WallBoundary since we don't have a level set for half space. But we can either add it (should be easy) or just use large boxes for walls instead.
___
*[`multibody/fem/mpm-dev/BoundaryCondition.cc` line 72 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/19#-N4dzWFu6b6vf5BdP1Fg:-N4dzWFu6b6vf5BdP1Fh:b-5s7hyg) ([raw file](https://github.com/yiminlin-tri/drake/blob/21e401ae7c40a083dad4ecb8afdf46bed6275232/multibody/fem/mpm-dev/BoundaryCondition.cc#L72)):*
> ```cpp
>     for (const auto& moving_cyl_boundary : moving_cylindrical_boundaries_) {
>         // particle's position in cylinder's reference frame
>         Vector3<double> x_cyl = moving_cyl_boundary.pose.inverse()
> ```

Having an initial pose and manual updating the current pose in the function is cumbersome. We should have a separate function that keeps track of the current state of the collision object. See proposal above.
___
*[`multibody/fem/mpm-dev/BoundaryCondition.cc` line 89 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/19#-N4e08hpCG4KgueVdU5J:-N4e08hpCG4KgueVdU5K:b-5a90ui) ([raw file](https://github.com/yiminlin-tri/drake/blob/21e401ae7c40a083dad4ecb8afdf46bed6275232/multibody/fem/mpm-dev/BoundaryCondition.cc#L89)):*
> ```cpp
> }
> 
> void BoundaryCondition::UpdateVelocityCoulumbFriction(const Vector3<double>& n,
> ```

nit can this function be static?
___
*[`multibody/fem/mpm-dev/MPMDriver.h` line 45 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/19#-N4e0EuO1TOXxwtXuKop:-N4e0EuO1TOXxwtXuKoq:be16f0i) ([raw file](https://github.com/yiminlin-tri/drake/blob/21e401ae7c40a083dad4ecb8afdf46bed6275232/multibody/fem/mpm-dev/MPMDriver.h#L45)):*
> ```objc
> 
>     // Initialize the boundary condition by the boundaries information
>     void InitializeBoundaryConditions(
> ```

With the proposal above, this can be simplified to 

``` void InitializeBoundaryConditions(std::vector<std::unique_ptr<CollisionObject>> bcs);```

or perhaps even better -- adding objects one at a time:

``` void AddCollisionObject(std::unique_ptr<CollisionObject> object);```
___
*[`multibody/fem/mpm-dev/MPMDriver.h` line 75 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/19#-N4dsWVCA7swzWesGHj2:-N4dsWVCA7swzWesGHj3:b-g0o2wm) ([raw file](https://github.com/yiminlin-tri/drake/blob/21e401ae7c40a083dad4ecb8afdf46bed6275232/multibody/fem/mpm-dev/MPMDriver.h#L75)):*
> ```objc
>     // transfer, grid velocities update, a G2P transfer, and particles'
>     // velocities update.
>     void AdvanceOneTimeStep(double t, double dt);
> ```

It's ok to pass `dt` when advancing a time step, but we definitely don't want to pass the current time `t`. We should be able to advance to the next time step based solely on the state from the previous time step. I.e. x_n+1 is a function of x_n, v_n, ... etc, but not a function of t explicitly. 

I think you are keeping track of `t` to obtain the state of the boundary condition. I think the proper way to get that information is to store the states of the boundary condition inside the boundary conditions class. 


<!-- Sent from Reviewable.io -->

2022-06-16 16:45 UTC, yiminlin-tri commented
*[`multibody/fem/mpm-dev/BoundaryCondition.h` line 34 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/19#-N4du6uh0WgwKsQcyzBx:-N4hN9YH8SZYATf4x0jT:bhm98ce) ([raw file](https://github.com/yiminlin-tri/drake/blob/21e401ae7c40a083dad4ecb8afdf46bed6275232/multibody/fem/mpm-dev/BoundaryCondition.h#L34)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

With more than one type of bc/collision object, it think it makes sense to reorganize some functionalities into common functions It would help clean up the API of BoundaryCondition/KinematicCollisionObjects. 

Here's what I have in mind, see if you like it:

```
// Renamed from BoundaryCondition, stored in the driver.
class KinematicCollisionObjects {
public:
  // Add a new collision object.
  void AddCollisionObject(std::unique_ptr<CollisionObject> obj);

  // Retrieve a collision object by index.
  const CollisionObject& get_collision_object(int index) const;

  // Advance the state of all collision objects by dt.
  void AdvanceOneTimeStep(double dt);

  // Apply boundary conditions for all collision objects.
  void ApplyBoundaryConditions(const Vector3<double>& position, Vector3<double>* velocity) const;
};

//  Consolidate WallBoundary and MovingCylindricalBoundary into a single class
class CollisionObject {
public:
  struct CollisionObjectState {
    math::RigidTransformd pose;
    // This lets us add in rotation as well for rolling pin.
    math::SpatialVelocityd spatial_velocity;
  };

  // Construct a new collision object with level set and prescribed initial_state
  CollisionObject(std::unique_ptr<AnalyticLevelSet> level_set, CollisionObjectState initial_state, double friction_coeff);

  // Advance the state of this collision object by dt.
  AdvanceOneTimeStep(double dt);
  
  // Apply the bc prescribed by this object.
  void ApplyBoundaryCondition(const Vector3<double>& position, Vector3<double>* velocity) const;
};
```
This gives you flexibility to add new shapes as the become necessary and reduces some repetitive pattern in BoundaryCondition.h/cc that's tarting to emerge.

This of course would require some modification on the WallBoundary since we don't have a level set for half space. But we can either add it (should be easy) or just use large boxes for walls instead.
</blockquote></details>

Thanks! The API looks very clean. Seems to me KinematicCollisionObjects is an "array of struct", is it a good idea to encapsulate CollisionObject into KinematicCollisionObjects? i.e. we modify the routine AddCollisionObject by pass in
```(std::unique_ptr<AnalyticLevelSet> level_set, CollisionObjectState initial_state, double friction_coeff)```


<!-- Sent from Reviewable.io -->

2022-06-16 17:13 UTC, xuchenhan-tri requested changes
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/19)* status: 7 of 10 files reviewed, 6 unresolved discussions (waiting on @xuchenhan-tri and @yiminlin-tri)

___
*[`multibody/fem/mpm-dev/BoundaryCondition.h` line 34 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/19#-N4du6uh0WgwKsQcyzBx:-N4hVH9Y8JLFpF4H69Hb:b1b6d10) ([raw file](https://github.com/yiminlin-tri/drake/blob/21e401ae7c40a083dad4ecb8afdf46bed6275232/multibody/fem/mpm-dev/BoundaryCondition.h#L34)):*
<details><summary><i>Previously, yiminlin-tri wrote…</i></summary><blockquote>

Thanks! The API looks very clean. Seems to me KinematicCollisionObjects is an "array of struct", is it a good idea to encapsulate CollisionObject into KinematicCollisionObjects? i.e. we modify the routine AddCollisionObject by pass in
```(std::unique_ptr<AnalyticLevelSet> level_set, CollisionObjectState initial_state, double friction_coeff)```
</blockquote></details>

I think either is fine. Your call.


<!-- Sent from Reviewable.io -->

2022-06-23 03:29 UTC, yiminlin-tri reviewed
Some major updates: The visualization looks incorrect. I am working on adding a new test case. I will discuss f2f with you tomorrow. Thanks!

> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/19#-:-N5DaUs04Za6boQQwtV5:b39nxtq)* status: 0 of 18 files reviewed, 5 unresolved discussions (waiting on @xuchenhan-tri)

*[a discussion](https://reviewable.io/reviews/yiminlin-tri/drake/19#-N4ds5lS9qXzyxsUNjdF:-N5D_onR07GJt70k518N:b-896fix) (no related file):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I made a quick pass through the non-testing code. A couple of thoughts.

1. We shouldn't be passing the current time `t` around, all the way to the driver. Instead, we should keep the state of the collision objects locally.
2. I see that we are spamming public functions in the boundary conditions a little bit. I think we can clean that up nicely. See below.
</blockquote></details>

Done.

___
___
*[`multibody/fem/mpm-dev/BoundaryCondition.h` line 24 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/19#-N4dthCABZc68hxZPSgn:-N5D_pZv17NanZ5WfWBt:b-896fix) ([raw file](https://github.com/yiminlin-tri/drake/blob/21e401ae7c40a083dad4ecb8afdf46bed6275232/multibody/fem/mpm-dev/BoundaryCondition.h#L24)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Now that we are supporting moving bcs, perhaps we should update the name as well? What about `KinematicCollisionObjects`. It emphasizes 
1. the motion is kinematically prescribed, and 
2. plurality.
</blockquote></details>

Done.
___
*[`multibody/fem/mpm-dev/BoundaryCondition.h` line 34 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/19#-N4du6uh0WgwKsQcyzBx:-N5D_qbs9eZzdwsm-vsX:b-896fix) ([raw file](https://github.com/yiminlin-tri/drake/blob/21e401ae7c40a083dad4ecb8afdf46bed6275232/multibody/fem/mpm-dev/BoundaryCondition.h#L34)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I think either is fine. Your call.
</blockquote></details>

Done.
___
*[`multibody/fem/mpm-dev/BoundaryCondition.cc` line 72 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/19#-N4dzWFu6b6vf5BdP1Fg:-N5D_rjTD27Q4NLkEXtY:b-896fix) ([raw file](https://github.com/yiminlin-tri/drake/blob/21e401ae7c40a083dad4ecb8afdf46bed6275232/multibody/fem/mpm-dev/BoundaryCondition.cc#L72)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Having an initial pose and manual updating the current pose in the function is cumbersome. We should have a separate function that keeps track of the current state of the collision object. See proposal above.
</blockquote></details>

Done.
___
*[`multibody/fem/mpm-dev/BoundaryCondition.cc` line 89 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/19#-N4e08hpCG4KgueVdU5J:-N5DaMgq3Pf043UWGmSj:b-pypt0e) ([raw file](https://github.com/yiminlin-tri/drake/blob/21e401ae7c40a083dad4ecb8afdf46bed6275232/multibody/fem/mpm-dev/BoundaryCondition.cc#L89)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit can this function be static?
</blockquote></details>

Seems like we need to drop const
___
*[`multibody/fem/mpm-dev/MPMDriver.h` line 75 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/19#-N4dsWVCA7swzWesGHj2:-N5DaQsyDUUS4IhchFgR:b-896fix) ([raw file](https://github.com/yiminlin-tri/drake/blob/21e401ae7c40a083dad4ecb8afdf46bed6275232/multibody/fem/mpm-dev/MPMDriver.h#L75)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

It's ok to pass `dt` when advancing a time step, but we definitely don't want to pass the current time `t`. We should be able to advance to the next time step based solely on the state from the previous time step. I.e. x_n+1 is a function of x_n, v_n, ... etc, but not a function of t explicitly. 

I think you are keeping track of `t` to obtain the state of the boundary condition. I think the proper way to get that information is to store the states of the boundary condition inside the boundary conditions class. 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-06-23 17:27 UTC, xuchenhan-tri requested changes
I made a pass through the non-test files. Looking good!

> Reviewed 13 of 18 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/19#-:-N5GaclZ45Do2AbJJ0bY:bpacw81)* status: 14 of 18 files reviewed, 9 unresolved discussions (waiting on @xuchenhan-tri and @yiminlin-tri)

___
*[`multibody/fem/mpm-dev/AnalyticLevelSet.h` line 48 at r5](https://reviewable.io/reviews/yiminlin-tri/drake/19#-N5GXv_oCg4rNKPPvRnB:-N5GXv_oCg4rNKPPvRnC:b2ni8l0) ([raw file](https://github.com/yiminlin-tri/drake/blob/be0d6b91383a83122f527417e203bf1506bcee11/multibody/fem/mpm-dev/AnalyticLevelSet.h#L48)):*
> ```objc
> };  // class AnalyticLevelSet
> 
> // An analytic level set class for half space with normal normal_ and center
> ```

nit



_Suggestion:_
```objc
// An analytic level set class for half space with the given `normal` and center
```
___
*[`multibody/fem/mpm-dev/AnalyticLevelSet.cc` line 26 at r5](https://reviewable.io/reviews/yiminlin-tri/drake/19#-N5GLiEhEEnwbX38RIL2:-N5GLiEhEEnwbX38RIL3:b-ozlq6m) ([raw file](https://github.com/yiminlin-tri/drake/blob/be0d6b91383a83122f527417e203bf1506bcee11/multibody/fem/mpm-dev/AnalyticLevelSet.cc#L26)):*
> ```cpp
>                                     std::numeric_limits<double>::infinity()
>                                     *Vector3<double>::Ones()}}),
>                 normal_(normal.normalized()) {
> ```

nit, this would get called before the DRAKE_DEMAND below and possibly cause a divide by zero.
___
*[`multibody/fem/mpm-dev/AnalyticLevelSet.cc` line 39 at r5](https://reviewable.io/reviews/yiminlin-tri/drake/19#-N5GLtNa4fhung0iF11F:-N5GLtNa4fhung0iF11G:bjr5i5x) ([raw file](https://github.com/yiminlin-tri/drake/blob/be0d6b91383a83122f527417e203bf1506bcee11/multibody/fem/mpm-dev/AnalyticLevelSet.cc#L39)):*
> ```cpp
>         return normal_;
>     } else {
>         throw std::logic_error("Normal outside of the level set is unavaiable");
> ```

nit s/unavaiable/unavailable.
___
*[`multibody/fem/mpm-dev/BoundaryCondition.cc` line 89 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/19#-N4e08hpCG4KgueVdU5J:-N5GXdOe-eiqWBRUbnRg:bak2wnb) ([raw file](https://github.com/yiminlin-tri/drake/blob/21e401ae7c40a083dad4ecb8afdf46bed6275232/multibody/fem/mpm-dev/BoundaryCondition.cc#L89)):*
<details><summary><i>Previously, yiminlin-tri wrote…</i></summary><blockquote>

Seems like we need to drop const
</blockquote></details>

Yes. static is one better than const. const says that the function doesn't modify the object. static says that the function operates independent of the object.
___
*[`multibody/fem/mpm-dev/CollisionObject.h` line 46 at r5](https://reviewable.io/reviews/yiminlin-tri/drake/19#-N5GXT2gDMisG5IJXJgY:-N5GXT2h-JKEW_u2jPJ1:b-x3wbs1) ([raw file](https://github.com/yiminlin-tri/drake/blob/be0d6b91383a83122f527417e203bf1506bcee11/multibody/fem/mpm-dev/CollisionObject.h#L46)):*
> ```objc
>     // Coulumb friction law states the amount of friction imposed is at most
>     // μ ‖j‖, where \mu is the friction coefficient of the wall.
>     // If ‖vₜ‖ <= μ‖vₙ‖,   v_new = 0.0
> ```

We should clarify in the doc that velocity is not modified if the normal component is non-negative.
___
*[`multibody/fem/mpm-dev/CollisionObject.h` line 49 at r5](https://reviewable.io/reviews/yiminlin-tri/drake/19#-N5GXQGK-0-ecFlFzXBP:-N5GXQGK-0-ecFlFzXBQ:b-xcq4vh) ([raw file](https://github.com/yiminlin-tri/drake/blob/be0d6b91383a83122f527417e203bf1506bcee11/multibody/fem/mpm-dev/CollisionObject.h#L49)):*
> ```objc
>     // Otherwise    ,   v_new = vₜ - μ‖vₙ‖t, t - tangential direction
>     // Then we overwrite the passed in velocity with v_new.
>     // For a grid point locates on multiple boundaries, we impose each
> ```

This comment needs an update.



_Code quote:_
```objc
    // For a grid point locates on multiple boundaries, we impose each
    // boundary condition, ordered as in boundaries_, to this grid point.
```
___
*[`multibody/fem/mpm-dev/CollisionObject.cc` line 9 at r5](https://reviewable.io/reviews/yiminlin-tri/drake/19#-N5GNAlT0KFspXV9yhIh:-N5GNAlU9u0OuB3DMuwO:bs9a167) ([raw file](https://github.com/yiminlin-tri/drake/blob/be0d6b91383a83122f527417e203bf1506bcee11/multibody/fem/mpm-dev/CollisionObject.cc#L9)):*
> ```cpp
> CollisionObject::CollisionObject(std::unique_ptr<AnalyticLevelSet> level_set,
>                     CollisionObject::CollisionObjectState initial_state,
>                     double friction_coeff): state_(initial_state),
> ```

btw you can move the `initial_state` into `state_`
___
*[`multibody/fem/mpm-dev/CollisionObject.cc` line 20 at r5](https://reviewable.io/reviews/yiminlin-tri/drake/19#-N5GSzrhCtX5cakF8hgl:-N5GSzrhCtX5cakF8hgm:b-4mhr08) ([raw file](https://github.com/yiminlin-tri/drake/blob/be0d6b91383a83122f527417e203bf1506bcee11/multibody/fem/mpm-dev/CollisionObject.cc#L20)):*
> ```cpp
>                                 omega(2),       0.0, -omega(0),
>                                -omega(1),  omega(0),       0.0;
>     Vector3<double> translation_new = state_.pose.translation()
> ```

BTW, I'd move this to the top above the line `//Angular velocity` to avoid the interruption in the flow of reading.
___
*[`multibody/fem/mpm-dev/CollisionObject.cc` line 58 at r5](https://reviewable.io/reviews/yiminlin-tri/drake/19#-N5GTpVY9iwJUPyq-4F4:-N5GTpVY9iwJUPyq-4F5:b-5n93ca) ([raw file](https://github.com/yiminlin-tri/drake/blob/be0d6b91383a83122f527417e203bf1506bcee11/multibody/fem/mpm-dev/CollisionObject.cc#L58)):*
> ```cpp
> 
>     // Express the relative velocity in the collision object's frame R.
>     Vector3<double> v_RqQ_R = X_WR.rotation().inverse() * v_RqQ_W;
> ```

nit, we could cache `X_WR.rotation().inverse()` since we reuse it in the lines below.
___
*[`multibody/fem/mpm-dev/CollisionObject.cc` line 63 at r5](https://reviewable.io/reviews/yiminlin-tri/drake/19#-N5GTzjxBWJ_Pz4DkAJy:-N5GTzjxBWJ_Pz4DkAJz:b-nlkows) ([raw file](https://github.com/yiminlin-tri/drake/blob/be0d6b91383a83122f527417e203bf1506bcee11/multibody/fem/mpm-dev/CollisionObject.cc#L63)):*
> ```cpp
>     const Vector3<double> p_RoRq_R = X_WR.rotation().inverse() * p_RoRq_W;
> 
>     if (!level_set_->InInterior(p_RoRq_R)) return;
> ```

nit, this check should be moved up as much as possible to avoid unnecessary computations.
___
*[`multibody/fem/mpm-dev/CollisionObject.cc` line 84 at r5](https://reviewable.io/reviews/yiminlin-tri/drake/19#-N5GQcdZ8Ou3kkGX1tR0:-N5GQcdZ8Ou3kkGX1tR1:b-ydl0yt) ([raw file](https://github.com/yiminlin-tri/drake/blob/be0d6b91383a83122f527417e203bf1506bcee11/multibody/fem/mpm-dev/CollisionObject.cc#L84)):*
> ```cpp
>     // Limit the amount of friction to at most eliminating the
>     // tangential velocity
>     if (vt_norm <= friction_coeff_*vn_norm) {
> ```

Per f2f, we should only modify this velocity if the `vn_norm < 0`.
___
*[`multibody/fem/mpm-dev/KinematicCollisionObjects.cc` line 15 at r5](https://reviewable.io/reviews/yiminlin-tri/drake/19#-N5GS6Re182BEwX5usaL:-N5GS6Re182BEwX5usaM:b-tgawso) ([raw file](https://github.com/yiminlin-tri/drake/blob/be0d6b91383a83122f527417e203bf1506bcee11/multibody/fem/mpm-dev/KinematicCollisionObjects.cc#L15)):*
> ```cpp
>     collision_objects_.emplace_back(
>                         std::make_unique<CollisionObject>(std::move(level_set),
>                                                           state,
> ```

btw, you can move the `state` here as well.
___
*[`multibody/fem/mpm-dev/KinematicCollisionObjects.cc` line 24 at r5](https://reviewable.io/reviews/yiminlin-tri/drake/19#-N5GRqikEpxFF_nEGktM:-N5GRqikEpxFF_nEGktN:b8zjjrj) ([raw file](https://github.com/yiminlin-tri/drake/blob/be0d6b91383a83122f527417e203bf1506bcee11/multibody/fem/mpm-dev/KinematicCollisionObjects.cc#L24)):*
> ```cpp
> 
> void KinematicCollisionObjects::AdvanceOneTimeStep(double dt) {
>     for (const auto& obj : collision_objects_) {
> ```

nit, this `const` is a bit misleading. We should probably remove it. After all, advancing one time step is a non [...]

2022-06-23 20:37 UTC, yiminlin-tri reviewed
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/19)* status: 14 of 18 files reviewed, 3 unresolved discussions (waiting on @xuchenhan-tri)

___
*[`multibody/fem/mpm-dev/BoundaryCondition.cc` line 89 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/19#-N4e08hpCG4KgueVdU5J:-N5H-KLl8N1BWuzEvwVl:bjxhvrq) ([raw file](https://github.com/yiminlin-tri/drake/blob/21e401ae7c40a083dad4ecb8afdf46bed6275232/multibody/fem/mpm-dev/BoundaryCondition.cc#L89)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Yes. static is one better than const. const says that the function doesn't modify the object. static says that the function operates independent of the object.
</blockquote></details>

We used friction_coeff_ in the routine, maybe we keep const here instead of using static + pass in friction_coeff as an argument?
___
*[`multibody/fem/mpm-dev/CollisionObject.h` line 46 at r5](https://reviewable.io/reviews/yiminlin-tri/drake/19#-N5GXT2gDMisG5IJXJgY:-N5H9wHeCEYUeLQ3oRQD:b-896fix) ([raw file](https://github.com/yiminlin-tri/drake/blob/be0d6b91383a83122f527417e203bf1506bcee11/multibody/fem/mpm-dev/CollisionObject.h#L46)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

We should clarify in the doc that velocity is not modified if the normal component is non-negative.
</blockquote></details>

Done.
___
*[`multibody/fem/mpm-dev/CollisionObject.h` line 49 at r5](https://reviewable.io/reviews/yiminlin-tri/drake/19#-N5GXQGK-0-ecFlFzXBP:-N5H9xXK-apyRSPRiC49:b-896fix) ([raw file](https://github.com/yiminlin-tri/drake/blob/be0d6b91383a83122f527417e203bf1506bcee11/multibody/fem/mpm-dev/CollisionObject.h#L49)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

This comment needs an update.
</blockquote></details>

Done.
___
*[`multibody/fem/mpm-dev/CollisionObject.cc` line 84 at r5](https://reviewable.io/reviews/yiminlin-tri/drake/19#-N5GQcdZ8Ou3kkGX1tR0:-N5HDrPy-DbSnS7aapfk:b-896fix) ([raw file](https://github.com/yiminlin-tri/drake/blob/be0d6b91383a83122f527417e203bf1506bcee11/multibody/fem/mpm-dev/CollisionObject.cc#L84)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Per f2f, we should only modify this velocity if the `vn_norm < 0`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-06-23 22:38 UTC, xuchenhan-tri reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

A general comment on testing strategy. I'm sensing a little repetition that might have cost you some development time:

You have a set of tests that verifies the functionalities of the various level sets (half space, box, sphere etc). Then you have a set of tests to cover the functions in CollisionObjects. With those tests, we have coverage on these low level functionalities. 

For classes that depend on these classes, like Grid and KinematicCollisionObjects, we only need to test the code that exercises these low level functions are _invoking_ these functions correctly. We don't need to test the low level functionalities again. 

For example, in the tests for Grid, it seems a little redundant to test with all the different shapes since we are only testing the `EnforceBoundaryCondition` function. To test that, we just need some sort of verification that `ApplyBoundaryConditions` is invoked on all grid nodes. We don't need to verify the _implementation_ of `ApplyBoundaryConditions` is correct. That's already covered in a separate unit test. Just the fact that they are called is good enough!

> Reviewed 2 of 18 files at r4, 9 of 9 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/19#-:-N5Hf2PS17FVHo76LK5r:bon1f5h)* status: all files reviewed, 1 unresolved discussion (waiting on @yiminlin-tri)

___
*[`multibody/fem/mpm-dev/BoundaryCondition.cc` line 89 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/19#-N4e08hpCG4KgueVdU5J:-N5Hew_o52N_W5eVLIUv:b-ratyyx) ([raw file](https://github.com/yiminlin-tri/drake/blob/21e401ae7c40a083dad4ecb8afdf46bed6275232/multibody/fem/mpm-dev/BoundaryCondition.cc#L89)):*
<details><summary><i>Previously, yiminlin-tri wrote…</i></summary><blockquote>

We used friction_coeff_ in the routine, maybe we keep const here instead of using static + pass in friction_coeff as an argument?
</blockquote></details>

I see. Retracted.
___
*[`multibody/fem/mpm-dev/test/CollisionObject_test.cc` line 146 at r6](https://reviewable.io/reviews/yiminlin-tri/drake/19#-N5HeEKi4VApmJwx8drr:-N5HeEKi4VApmJwx8drs:bs0hm19) ([raw file](https://github.com/yiminlin-tri/drake/blob/16839cecb76609bc22bcbd253b5ca358acf69d7e/multibody/fem/mpm-dev/test/CollisionObject_test.cc#L146)):*
> ```cpp
>     }
> 
>     void TestWallBC() {
> ```

nit, missing a test on advancing collision objects with non-zero angular velocity. We can, for example, replace the cylinder test with a sphere test (which has non-zero angular velocity)


<!-- Sent from Reviewable.io -->

2022-06-23 23:43 UTC, yiminlin-tri reviewed
Thanks for the suggestions! Yes, I agree, I spent a lot of time writing the tests, and they are indeed repetitive. I will restructure my tests a little bit better next time. :thumbsup: 

> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/19#-:-N5Hwba34deWVfyDVaBk:bndfj4a)* status: 17 of 18 files reviewed, all discussions resolved (waiting on @xuchenhan-tri)



<!-- Sent from Reviewable.io -->

2022-06-24 00:09 UTC, xuchenhan-tri approved these changes
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/19)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yiminlin-tri)



<!-- Sent from Reviewable.io -->

2022-06-24 00:10 UTC, xuchenhan-tri requested changes
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/19)* status: all files reviewed, 1 unresolved discussion (waiting on @yiminlin-tri)

___
*[`multibody/fem/mpm-dev/test/CollisionObject_test.cc` line 313 at r7](https://reviewable.io/reviews/yiminlin-tri/drake/19#-N5I1nG4AU5NXl-F0mcu:-N5I1nG4AU5NXl-F0mcv:b-ko6gz3) ([raw file](https://github.com/yiminlin-tri/drake/blob/a4ce4e97bbe381b8c1adb94c7f65a38c2205e947/multibody/fem/mpm-dev/test/CollisionObject_test.cc#L313)):*
> ```cpp
> namespace {
> 
> TEST_F(CollisionObjectTest, TestAdvanceOneTimeStep) {
> ```

Per f2f, we'll add another test for pose update with non-zero angular velocity.


<!-- Sent from Reviewable.io -->

2022-06-24 00:57 UTC, yiminlin-tri reviewed
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/19)* status: 17 of 18 files reviewed, 1 unresolved discussion (waiting on @xuchenhan-tri)

___
*[`multibody/fem/mpm-dev/test/CollisionObject_test.cc` line 313 at r7](https://reviewable.io/reviews/yiminlin-tri/drake/19#-N5I1nG4AU5NXl-F0mcu:-N5IC_QJ3zA9mi0nOSX0:b-896fix) ([raw file](https://github.com/yiminlin-tri/drake/blob/a4ce4e97bbe381b8c1adb94c7f65a38c2205e947/multibody/fem/mpm-dev/test/CollisionObject_test.cc#L313)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Per f2f, we'll add another test for pose update with non-zero angular velocity.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-06-24 01:12 UTC, xuchenhan-tri approved these changes
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/19)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yiminlin-tri)



<!-- Sent from Reviewable.io -->

2022-06-24 01:12 UTC, merged