[mpm-dev] Von-Mises plasticity
yiminlin-tri/drake pull request #24
Opened 2022-07-06 20:06 UTC by yiminlin-tri

2022-07-07 21:24 UTC, yiminlin-tri reviewed
+@xuchenhan-tri Thanks!

> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/24#-:-N6PY9wV8buAOAT1s4uP:b6w1hxi)* status: 0 of 14 files reviewed, 1 unresolved discussion (waiting on @xuchenhan-tri)

___
*[`multibody/fem/mpm-dev/main.cpp` line 95 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/24#-N6PXfcM8AiMREt1ktY6:-N6PXfcM8AiMREt1ktY7:b-wlkque) ([raw file](https://github.com/yiminlin-tri/drake/blob/ef06f7516745c54b10f2ac234c60a1cd2e53a80f/multibody/fem/mpm-dev/main.cpp#L95)):*
> ```cpp
>     double E = 8e4;
>     double nu = 0.49;
>     // TODO(yiminlin.tri): Had to pass in Hencky Model so that plasticity
> ```

The current plasticity model only works for Hencky strain constitutive model. Shall we replace all ConstitutiveModel to SaintVenantKirchhoffWithHenckyModel for now?


<!-- Sent from Reviewable.io -->

2022-07-11 18:19 UTC, xuchenhan-tri requested changes
I made a pass through the non-test files. PTAL.

> Reviewed 10 of 14 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/24#-:-N6iU9GR7Wm_LAte7zCG:b-4hbf53)* status: 11 of 14 files reviewed, 13 unresolved discussions (waiting on @xuchenhan-tri and @yiminlin-tri)

*[a discussion](https://reviewable.io/reviews/yiminlin-tri/drake/24#-N6iAoC8CLPCdzORoLAh:-N6iAoC8CLPCdzORoLAi:b-88lt1l) (no related file):*
Question, do we use F^P at all anywhere in the algorithm? Since like it's enough to only keep track of F^E.

___
___
*[`multibody/fem/mpm-dev/ConstitutiveModel.h` line 23 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/24#-N6iTcgbAPOK9KOuA5yB:-N6iTcgbAPOK9KOuA5yC:bwciozs) ([raw file](https://github.com/yiminlin-tri/drake/blob/20343c10503b1765165d792cbb66701b264d9d20/multibody/fem/mpm-dev/ConstitutiveModel.h#L23)):*
> ```objc
>     virtual std::unique_ptr<ConstitutiveModel> Clone() const = 0;
> 
>     double get_mu() const;
> ```

nit, need a comment on what mu and lamda are. (second and first lame parameter). Then you can remove the note on the data member.
___
*[`multibody/fem/mpm-dev/main.cpp` line 95 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/24#-N6PXfcM8AiMREt1ktY6:-N6iRyju41ggRhg0vD-8:bv10rww) ([raw file](https://github.com/yiminlin-tri/drake/blob/ef06f7516745c54b10f2ac234c60a1cd2e53a80f/multibody/fem/mpm-dev/main.cpp#L95)):*
<details><summary><i>Previously, yiminlin-tri wrote…</i></summary><blockquote>

The current plasticity model only works for Hencky strain constitutive model. Shall we replace all ConstitutiveModel to SaintVenantKirchhoffWithHenckyModel for now?
</blockquote></details>

I can see several ways around it.

1. Instead of having the plasticity model takes in `mu` as an argument, have it take in the entire constitutive model. From there, you can either
a. dynamic cast the constitutive model to see if it's the model you are expecting (usually a bad practice according to [GSG](https://drake.mit.edu/styleguide/cppguide.html#Run-Time_Type_Information__RTTI_), but is ok for a prototype like this), or 
b. use a [visitor pattern](https://refactoring.guru/design-patterns/visitor/cpp/example#:~:text=Visitor%20%2F%20C%2B%2B-,Visitor%20in%20C%2B%2B,article%20Visitor%20and%20Double%20Dispatch.).
2. Instead of having elasticity and plasticity as separate classes, you can merge them and have the base class be Elastoplastic models and the derived classes be FixedCorotatedElasticModel and StvkHenckyWithVonMisesModel. Having something like this may help with reducing the number of svds we perform as I noted in the thread below.
___
*[`multibody/fem/mpm-dev/Particles.cc` line 200 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/24#-N6i5X3wAokmm77aq8sD:-N6i5X3x3rsZmx7y9JX-:boiydzp) ([raw file](https://github.com/yiminlin-tri/drake/blob/20343c10503b1765165d792cbb66701b264d9d20/multibody/fem/mpm-dev/Particles.cc#L200)):*
> ```cpp
>         masses_sorted[p]                        = masses_[p_new];
>         reference_volumes_sorted[p]             = reference_volumes_[p_new];
>         elastic_deformation_gradients_sorted[p] =
> ```

We are sorting all the attributes that particles have. Is that necessary? Or can we get away with only sorting the attributes that get transferred to the grid/pad (e.g. mass, velocities etc).
___
*[`multibody/fem/mpm-dev/VonMisesPlasticityModel.h` line 17 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/24#-N6i6PO_CemoESO0ppWM:-N6i6POa9H6MpSQxTBT7:b2dfxfe) ([raw file](https://github.com/yiminlin-tri/drake/blob/20343c10503b1765165d792cbb66701b264d9d20/multibody/fem/mpm-dev/VonMisesPlasticityModel.h#L17)):*
> ```objc
> // The return mapping algorithm can be found in Box 7.1.
> // Assume the constitutive model we are using is the Saint-Venant Kirchhoff
> // constitutive model with Hencky strain. A Von Mises plasticity model composed
> ```

I believe the associate flow rule and the existence of a yield surface is independent of the von-Mises model. The von-Mises model only defines the functional form of the yield surface.
___
*[`multibody/fem/mpm-dev/VonMisesPlasticityModel.h` line 28 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/24#-N6i751V7KMgbsHAEdnx:-N6i751V7KMgbsHAEdny:bp2kxzl) ([raw file](https://github.com/yiminlin-tri/drake/blob/20343c10503b1765165d792cbb66701b264d9d20/multibody/fem/mpm-dev/VonMisesPlasticityModel.h#L28)):*
> ```objc
> //      ln(Σⁿ⁺¹) - ln(Σ) = -Δγ νⁿ⁺¹
> // We first outline the general procedure of applying plasticity
> // 1. Update the elastic stress Fᴱ in the G2P update, we call it the trial
> ```

A few steps are skipped in this outline.

1. F^E is not a stress. It's the elastic deformation gradient which is a *strain* measure. The stress measure we commonly use are FirstPiola P, Kirchhoff tau, and Cauchy σ. The strain measure we have encountered so far: deformation gradient F, Left Cauchy-Green C=F^T * F, right Cauchy-Green b = F*F^T, and Hencky ε = 1/2ln(b).
2. When we project the stress, we are projecting tau, the Kirchhoff stress, not the elastic deformation gradient F^E. It is only the special structure of St.Venant Hencky constitutive model which has the special property of `τ' = 2με'` that allows us to equivalently project F^E. Therefore, we shouldn't describe this as the "general procedure of applying plasticity".
___
*[`multibody/fem/mpm-dev/VonMisesPlasticityModel.h` line 38 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/24#-N6i963YBwN9exqGkwJe:-N6i963YBwN9exqGkwJf:bv40nt3) ([raw file](https://github.com/yiminlin-tri/drake/blob/20343c10503b1765165d792cbb66701b264d9d20/multibody/fem/mpm-dev/VonMisesPlasticityModel.h#L38)):*
> ```objc
> // the Kirchhoff stress  τ = U (2μln(Σ)+λtr(ln(Σ))I) Uᵀ
> // the deviatoric component of Kirchhoff stress is
> //                  dev(τ) = τ - 1/3*tr(τ)I = U (2μln(Σ)+2μ/3tr(ln(Σ))I) Uᵀ
> ```

nit, it's hard to tell whether `tr(ln(Σ))` is in the numerator or the denominator. 
___
*[`multibody/fem/mpm-dev/VonMisesPlasticityModel.h` line 50 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/24#-N6i9PUl8p92MHvW_7Df:-N6i9PUl8p92MHvW_7Dg:b8rjmsa) ([raw file](https://github.com/yiminlin-tri/drake/blob/20343c10503b1765165d792cbb66701b264d9d20/multibody/fem/mpm-dev/VonMisesPlasticityModel.h#L50)):*
> ```objc
> //                 k: f(τⁿ⁺¹) = 0 on the yield surface
> // Solving for k gives us the prjected states. The above derivation leads to the
> // same algorithm described in (BW Box 7.1), without hardening.
> ```

Describe what without hardening means in terms of how the formula is affected.
___
*[`multibody/fem/mpm-dev/VonMisesPlasticityModel.h` line 53 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/24#-N6i9goW-9kSjPF_O-te:-N6i9goW-9kSjPF_O-tf:b-nk0me2) ([raw file](https://github.com/yiminlin-tri/drake/blob/20343c10503b1765165d792cbb66701b264d9d20/multibody/fem/mpm-dev/VonMisesPlasticityModel.h#L53)):*
> ```objc
> class VonMisesPlasticityModel {
>  public:
>     // tau_c: maximum allowed tensile strength
> ```

nit, describe what the unit is and the precondition (non-negative). Also, would it be better to call tau_c `yield_stress` instead?
___
*[`multibody/fem/mpm-dev/VonMisesPlasticityModel.cc` line 19 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/24#-N6iLhcP3X2vHQjtN7bj:-N6iLhcP3X2vHQjtN7bk:b-x181j3) ([raw file](https://github.com/yiminlin-tri/drake/blob/20343c10503b1765165d792cbb66701b264d9d20/multibody/fem/mpm-dev/VonMisesPlasticityModel.cc#L19)):*
> ```cpp
>     const Matrix3<double>& V = svd.matrixV();
>     Vector3<double> sigma    = svd.singularValues();
>     // Singular values of the trial strain ε: σ(ε)
> ```

nit, it's a bit confusing to use σ and ε together. Let's remove all mentions of σ and use ε all the way to denote the hencky strain in its principal frame (aka the singular values).

Also, comment that hencky strain 1/2 * ln(ε^2) which can be simplified to ln(ε) since we are working in principal frame.
 [...]

2022-07-12 18:18 UTC, yiminlin-tri reviewed
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/24)* status: 11 of 14 files reviewed, 8 unresolved discussions (waiting on @xuchenhan-tri)

*[a discussion](https://reviewable.io/reviews/yiminlin-tri/drake/24#-N6iAoC8CLPCdzORoLAh:-N6ighttCraaFzbCNOeW:b1avuh6) (no related file):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Question, do we use F^P at all anywhere in the algorithm? Since like it's enough to only keep track of F^E.
</blockquote></details>

I got what you mean, yes I agree, we didn't use plastic deformation gradient in other calculation except updating itself and in the test. I will go on and remove it.

___
___
*[`multibody/fem/mpm-dev/Particles.cc` line 200 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/24#-N6i5X3wAokmm77aq8sD:-N6nJubx8G8lqcQ0TW_l:b-cor0yl) ([raw file](https://github.com/yiminlin-tri/drake/blob/20343c10503b1765165d792cbb66701b264d9d20/multibody/fem/mpm-dev/Particles.cc#L200)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

We are sorting all the attributes that particles have. Is that necessary? Or can we get away with only sorting the attributes that get transferred to the grid/pad (e.g. mass, velocities etc).
</blockquote></details>

We need to sort: 
position, velocities, masses, B matrix for P2G momentum transfer
reference volumes, kirchhoff stress for P2G force transfer
elastic deformation gradient for G2P deformation gradient update
elastoplastic model for update Kirchhoff stress.
So every fields need to be sorted. What do you think?
___
*[`multibody/fem/mpm-dev/VonMisesPlasticityModel.h` line 17 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/24#-N6i6PO_CemoESO0ppWM:-N6k864480QCajdUd-Kd:b-896fix) ([raw file](https://github.com/yiminlin-tri/drake/blob/20343c10503b1765165d792cbb66701b264d9d20/multibody/fem/mpm-dev/VonMisesPlasticityModel.h#L17)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I believe the associate flow rule and the existence of a yield surface is independent of the von-Mises model. The von-Mises model only defines the functional form of the yield surface.
</blockquote></details>

Done.
___
*[`multibody/fem/mpm-dev/VonMisesPlasticityModel.h` line 28 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/24#-N6i751V7KMgbsHAEdnx:-N6k9Wbr4fn0ULU-64GP:b-x25ar8) ([raw file](https://github.com/yiminlin-tri/drake/blob/20343c10503b1765165d792cbb66701b264d9d20/multibody/fem/mpm-dev/VonMisesPlasticityModel.h#L28)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

A few steps are skipped in this outline.

1. F^E is not a stress. It's the elastic deformation gradient which is a *strain* measure. The stress measure we commonly use are FirstPiola P, Kirchhoff tau, and Cauchy σ. The strain measure we have encountered so far: deformation gradient F, Left Cauchy-Green C=F^T * F, right Cauchy-Green b = F*F^T, and Hencky ε = 1/2ln(b).
2. When we project the stress, we are projecting tau, the Kirchhoff stress, not the elastic deformation gradient F^E. It is only the special structure of St.Venant Hencky constitutive model which has the special property of `τ' = 2με'` that allows us to equivalently project F^E. Therefore, we shouldn't describe this as the "general procedure of applying plasticity".
</blockquote></details>

Thanks for the explanation! Done.
___
*[`multibody/fem/mpm-dev/VonMisesPlasticityModel.h` line 50 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/24#-N6i9PUl8p92MHvW_7Df:-N6n6qhtB6pbYl3Pi49D:b-896fix) ([raw file](https://github.com/yiminlin-tri/drake/blob/20343c10503b1765165d792cbb66701b264d9d20/multibody/fem/mpm-dev/VonMisesPlasticityModel.h#L50)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Describe what without hardening means in terms of how the formula is affected.
</blockquote></details>

Done.
___
*[`multibody/fem/mpm-dev/VonMisesPlasticityModel.cc` line 44 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/24#-N6iOx0D6Gm67_EXLWir:-N6n_2A5Cu3ihA1RpxX5:b-896fix) ([raw file](https://github.com/yiminlin-tri/drake/blob/20343c10503b1765165d792cbb66701b264d9d20/multibody/fem/mpm-dev/VonMisesPlasticityModel.cc#L44)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Could we document how we arrived at the formula for `Δγ`? It's immediately clear to me that the exact same argument in B&W applies since we are using a different constitutive model.
</blockquote></details>

Done.
___
*[`multibody/fem/mpm-dev/VonMisesPlasticityModel.cc` line 54 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/24#-N6iPt9W5Ti9_dS35KnB:-N6k7hi-D85RZ1CnjF9Q:b-896fix) ([raw file](https://github.com/yiminlin-tri/drake/blob/20343c10503b1765165d792cbb66701b264d9d20/multibody/fem/mpm-dev/VonMisesPlasticityModel.cc#L54)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

It's a shame that we have U,V here already, but we will calculate it all over again in the next time step when we evaluate the constitutive relationship again. Can we somehow save this and reuse the svd in the next time step?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-12 22:04 UTC, xuchenhan-tri requested changes
> Reviewed 19 of 20 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/24)* status: 20 of 21 files reviewed, 16 unresolved discussions (waiting on @xuchenhan-tri and @yiminlin-tri)

___
*[`multibody/fem/mpm-dev/Particles.h` line 93 at r3](https://reviewable.io/reviews/yiminlin-tri/drake/24#-N6nm6O4ESIT8Uj4MTUG:-N6nm6O4ESIT8Uj4MTUH:b-fgl9y6) ([raw file](https://github.com/yiminlin-tri/drake/blob/236ed4a626d109b027441a0b4c8e7c678f10a9bb/multibody/fem/mpm-dev/Particles.h#L93)):*
> ```objc
>                      std::unique_ptr<ElastoPlasticModel> elastoplastic_model);
> 
>     // Assume the elastic deformation gradient is updated in the G2P transfer,
> ```

nit, I think the following is more clear if that's what you intend.



_Suggestion:_
```objc
// Assume the elastic deformation gradients are in their trial state (Fₑ = Fₑᵗʳⁱᵃˡ), calculate
// the resulting stress and project it back to the yield surface if necessary. Store the projected
// Kirchhoff stress as well as the corresponding elastic deformation gradient in `this`.
```
___
*[`multibody/fem/mpm-dev/Particles.cc` line 200 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/24#-N6i5X3wAokmm77aq8sD:-N6o0wnp-ex2RsVqbmwW:bq4vrhj) ([raw file](https://github.com/yiminlin-tri/drake/blob/20343c10503b1765165d792cbb66701b264d9d20/multibody/fem/mpm-dev/Particles.cc#L200)):*
<details><summary><i>Previously, yiminlin-tri wrote…</i></summary><blockquote>

We need to sort: 
position, velocities, masses, B matrix for P2G momentum transfer
reference volumes, kirchhoff stress for P2G force transfer
elastic deformation gradient for G2P deformation gradient update
elastoplastic model for update Kirchhoff stress.
So every fields need to be sorted. What do you think?
</blockquote></details>

Yeah you are right. Retracted.
___
*[`multibody/fem/mpm-dev/StvkHenckyWithVonMisesModel.h` line 27 at r3](https://reviewable.io/reviews/yiminlin-tri/drake/24#-N6oLDOk6tuUv_iOU5Fc:-N6oLDOk6tuUv_iOU5Fd:b-acizvd) ([raw file](https://github.com/yiminlin-tri/drake/blob/236ed4a626d109b027441a0b4c8e7c678f10a9bb/multibody/fem/mpm-dev/StvkHenckyWithVonMisesModel.h#L27)):*
> ```objc
> // plastic deformation rate and stress, l_p = dγ/dt df(τ)/dτ, where l_p is the
> // plastic rate of deformation and dγ/dt is called the plastic multiplier.
> // In particular, the Von Mises yield function is (BW 7.20a,b)
> ```

nit, I think it would help the flow of the text by moving any mention of the specific elastic/plastic model to *after* the general treatment of plasticity.
___
*[`multibody/fem/mpm-dev/StvkHenckyWithVonMisesModel.h` line 35 at r3](https://reviewable.io/reviews/yiminlin-tri/drake/24#-N6oKFz46hTGiL5Tca4f:-N6oKFz46hTGiL5Tca4g:be6pegd) ([raw file](https://github.com/yiminlin-tri/drake/blob/236ed4a626d109b027441a0b4c8e7c678f10a9bb/multibody/fem/mpm-dev/StvkHenckyWithVonMisesModel.h#L35)):*
> ```objc
> // 1. Update the elastic deformation gradient Fᴱ in the G2P update, compute the
> //    corresponding Kirchhoff stress τ, and we call it the trial stress.
> // 2. Project the trial stress to the yield surface, proj(τ)
> ```

nit, we only perform step 2 if the stress is outside the yield surface
___
*[`multibody/fem/mpm-dev/StvkHenckyWithVonMisesModel.h` line 37 at r3](https://reviewable.io/reviews/yiminlin-tri/drake/24#-N6oKNKH-RrIHm0GjrZe:-N6oKNKH-RrIHm0GjrZf:bc7gnsi) ([raw file](https://github.com/yiminlin-tri/drake/blob/236ed4a626d109b027441a0b4c8e7c678f10a9bb/multibody/fem/mpm-dev/StvkHenckyWithVonMisesModel.h#L37)):*
> ```objc
> // 2. Project the trial stress to the yield surface, proj(τ)
> // 3. Recover the projected deformation gradient proj(Fᴱ) by proj(τ) through the
> //    constitutive relation
> ```

nit the constitutive relation maps strain to stress. Here, we want the inverse map.



_Suggestion:_
```objc
// 3. Recover the projected deformation gradient proj(Fᴱ) by proj(τ) by inverting the
//    constitutive relation.
```
___
*[`multibody/fem/mpm-dev/StvkHenckyWithVonMisesModel.h` line 56 at r3](https://reviewable.io/reviews/yiminlin-tri/drake/24#-N6oLhj0D4t5s2xTEFL7:-N6oLhj0D4t5s2xTEFL8:b-oln8eu) ([raw file](https://github.com/yiminlin-tri/drake/blob/236ed4a626d109b027441a0b4c8e7c678f10a9bb/multibody/fem/mpm-dev/StvkHenckyWithVonMisesModel.h#L56)):*
> ```objc
> // Solving for k gives us the prjected states. The above derivation leads to the
> // same algorithm described in (BW Box 7.1), without hardening. We assume
> // no hardening in the plastic model, so the yield surface (function) doesn't
> ```

nit, I would go even further and write explicitly that "this is equivalent to the derivation in BW with H=0".
___
*[`multibody/fem/mpm-dev/StvkHenckyWithVonMisesModel.h` line 75 at r3](https://reviewable.io/reviews/yiminlin-tri/drake/24#-N6oMdd2BDJK8hQtUy3D:-N6oMdd2BDJK8hQtUy3E:b-o9fzf4) ([raw file](https://github.com/yiminlin-tri/drake/blob/236ed4a626d109b027441a0b4c8e7c678f10a9bb/multibody/fem/mpm-dev/StvkHenckyWithVonMisesModel.h#L75)):*
> ```objc
>     void CalcKirchhoffStress(const Matrix3<double>& F, Matrix3<double>* tau)
>                                                                     const final;
>     void CalcFirstPiolaKirchhoffStressAndKirchhoffStress(
> ```

Can you remind me why we need this function that computes both P and tau? I don't think we ever use it.
___
*[`multibody/fem/mpm-dev/StvkHenckyWithVonMisesModel.h` line 96 at r3](https://reviewable.io/reviews/yiminlin-tri/drake/24#-N6oNOGZ5wilHUZAiUk5:-N6oNOGZ5wilHUZAiUk6:b-cf4a5u) ([raw file](https://github.com/yiminlin-tri/drake/blob/236ed4a626d109b027441a0b4c8e7c678f10a9bb/multibody/fem/mpm-dev/StvkHenckyWithVonMisesModel.h#L96)):*
> ```objc
>     // Given the left and right singular vectors of the deformation gradient,
>     // the singular values and the trace of the trial Hencky strain ε: σ(ε):
>     // project the elastic deformation gradient to the yield surface. Update
> ```

Here's my attempt at a clarification.



_Suggestion:_
```objc
    // Given the left and right singular vectors of the deformation gradient (U and V),
    // the singular values and the trace of the trial Hencky strain (eps_hat and tr_eps),
    // if the corresponding stress is outside the yield surface, project it back to the
    // yield surface using associative flow rule. Then, invert the constitutive relation
    // and write the elastic deformation gradient corresponding to the projected stress to `FE`.
```
___
*[`multibody/fem/mpm-dev/StvkHenckyWithVonMisesModel.cc` line 19 at r3](https://reviewable.io/reviews/yiminlin-tri/drake/24#-N6oOcMoD_zn5WThMJmE:-N6oOcMoD_zn5WThMJmF:b-xfo05r) ([raw file](https://github.com/yiminlin-tri/drake/blob/236ed4a626d109b027441a0b4c8e7c678f10a9bb/multibody/fem/mpm-dev/StvkHenckyWithVonMisesModel.cc#L19)):*
> ```cpp
> }
> 
> void StvkHenckyWithVonMisesModel::CalcFirstPiolaKirchhoffStress(
> ```

The implementation of P shares a lot of code with that of tau, but the notation is slightly different

log_sigma vs. eps_hat,
sum_log_sigma vs. tr_eps.

We should at least unify these notations. Even better, consider a small refactor to get rid of code duplication (do we even need P?).
___
*[`multibody/fem/mpm-dev/StvkHenckyWithVonMisesModel.cc` line 58 at r3](https://reviewable.io/reviews/yiminlin-tri/drake/24#-N6o25gf9tnGNeKqbbme:-N6o25gf9tnGNeKqbbmf:bzgp96m) ([raw file](https://github.com/yiminlin-tri/drake/blob/236ed4a626d109b027441a0b4c8e7c678f10a9bb/multibody/fem/mpm-dev/StvkHenckyWithVonMisesModel.cc#L58)):*
> ```cpp
> 
> void StvkHenckyWithVonMisesModel::
>                                 CalcFirstPiolaKirchhoffStressAndKirchhoffStress(
> ```

Can we reuse the implementation for `CalcFirstPiolaKirchhoffStress` here?
___
*[`multibody/fem/mpm-dev/StvkHenckyWithVonMisesModel.cc` line 106 at r3](https://reviewable.io/reviews/yiminlin-tri/drake/24#-N6oPi5r1jgRdOblDJjQ:-N6oPi5r1jgRdOblDJjR:b-op6o3n) ([raw file](https://github.com/yiminlin-tri/drake/blob/236ed4a626d109b027441a0b4c8e7c678f10a9bb/multi [...]

2022-07-13 01:22 UTC, yiminlin-tri reviewed
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/24)* status: 20 of 21 files reviewed, 7 unresolved discussions (waiting on @xuchenhan-tri)

___
*[`multibody/fem/mpm-dev/StvkHenckyWithVonMisesModel.h` line 75 at r3](https://reviewable.io/reviews/yiminlin-tri/drake/24#-N6oMdd2BDJK8hQtUy3D:-N6oeVV93cfWYilAHowW:bx4n7ux) ([raw file](https://github.com/yiminlin-tri/drake/blob/236ed4a626d109b027441a0b4c8e7c678f10a9bb/multibody/fem/mpm-dev/StvkHenckyWithVonMisesModel.h#L75)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Can you remind me why we need this function that computes both P and tau? I don't think we ever use it.
</blockquote></details>

Yes, we never used it (We actually never used the first Piola stress). This routine avoids recompute the Polar decomposition in case we need both P and tau. By f2f, we will delete routine calculating P. 
___
*[`multibody/fem/mpm-dev/StvkHenckyWithVonMisesModel.h` line 96 at r3](https://reviewable.io/reviews/yiminlin-tri/drake/24#-N6oNOGZ5wilHUZAiUk5:-N6ogbzw7RoZvKiCHSSs:b-896fix) ([raw file](https://github.com/yiminlin-tri/drake/blob/236ed4a626d109b027441a0b4c8e7c678f10a9bb/multibody/fem/mpm-dev/StvkHenckyWithVonMisesModel.h#L96)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Here's my attempt at a clarification.
</blockquote></details>

Done.
___
*[`multibody/fem/mpm-dev/StvkHenckyWithVonMisesModel.cc` line 19 at r3](https://reviewable.io/reviews/yiminlin-tri/drake/24#-N6oOcMoD_zn5WThMJmE:-N6ogfEy4NaogXhtrMpU:bukj6dd) ([raw file](https://github.com/yiminlin-tri/drake/blob/236ed4a626d109b027441a0b4c8e7c678f10a9bb/multibody/fem/mpm-dev/StvkHenckyWithVonMisesModel.cc#L19)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

The implementation of P shares a lot of code with that of tau, but the notation is slightly different

log_sigma vs. eps_hat,
sum_log_sigma vs. tr_eps.

We should at least unify these notations. Even better, consider a small refactor to get rid of code duplication (do we even need P?).
</blockquote></details>

Yes, I don't think we need P.
___
*[`multibody/fem/mpm-dev/StvkHenckyWithVonMisesModel.cc` line 58 at r3](https://reviewable.io/reviews/yiminlin-tri/drake/24#-N6o25gf9tnGNeKqbbme:-N6oh8KCBu7Ujn9YA2Wq:b-896fix) ([raw file](https://github.com/yiminlin-tri/drake/blob/236ed4a626d109b027441a0b4c8e7c678f10a9bb/multibody/fem/mpm-dev/StvkHenckyWithVonMisesModel.cc#L58)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Can we reuse the implementation for `CalcFirstPiolaKirchhoffStress` here?
</blockquote></details>

Done.
___
*[`multibody/fem/mpm-dev/StvkHenckyWithVonMisesModel.cc` line 106 at r3](https://reviewable.io/reviews/yiminlin-tri/drake/24#-N6oPi5r1jgRdOblDJjQ:-N6p7iOi0rbreN4qiwFd:b-896fix) ([raw file](https://github.com/yiminlin-tri/drake/blob/236ed4a626d109b027441a0b4c8e7c678f10a9bb/multibody/fem/mpm-dev/StvkHenckyWithVonMisesModel.cc#L106)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

This code block shows up over and over again, we should refactor it.

E.g. 

`StrainData CalcStrainData(const Matrix3<double>& FE);`
</blockquote></details>

Done.
___
*[`multibody/fem/mpm-dev/ElastoPlasticModel.h` line 31 at r3](https://reviewable.io/reviews/yiminlin-tri/drake/24#-N6nkXjZ0CU02u5LCw5g:-N6osOK263l1pLQf3pC6:b-896fix) ([raw file](https://github.com/yiminlin-tri/drake/blob/236ed4a626d109b027441a0b4c8e7c678f10a9bb/multibody/fem/mpm-dev/ElastoPlasticModel.h#L31)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

We should emphasize that this is the elastic deformation gradient (i.e Fe instead of F) here and below.
</blockquote></details>

Done.
___
*[`multibody/fem/mpm-dev/ElastoPlasticModel.h` line 45 at r3](https://reviewable.io/reviews/yiminlin-tri/drake/24#-N6nktI72A0ODCnuILzP:-N6p1sBfAiacL2PN0Eeu:b-896fix) ([raw file](https://github.com/yiminlin-tri/drake/blob/236ed4a626d109b027441a0b4c8e7c678f10a9bb/multibody/fem/mpm-dev/ElastoPlasticModel.h#L45)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

This function needs documentation. It's unclear to me what's performed and in what order just by reading this function name. In particular is the calculated kirchhoff stress based on the updated F or not-yet-updated-F?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-13 16:29 UTC, xuchen-han requested changes
checkpoint before I go through the tests. Looking good so far.

> Reviewed 11 of 12 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/24#-:-N6sNpEkC4QLKT9aMAn3:b-7zpeph)* status: 20 of 21 files reviewed, all discussions resolved (waiting on @xuchenhan-tri)



<!-- Sent from Reviewable.io -->

2022-07-13 17:26 UTC, xuchenhan-tri requested changes
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/24)* status: 20 of 21 files reviewed, 3 unresolved discussions (waiting on @xuchenhan-tri and @yiminlin-tri)

___
*[`multibody/fem/mpm-dev/ElastoPlasticModel.h` line 25 at r4](https://reviewable.io/reviews/yiminlin-tri/drake/24#-N6sZSnm9K4QdaypZtyK:-N6sZSnm9K4QdaypZtyL:b92av8k) ([raw file](https://github.com/yiminlin-tri/drake/blob/a37fa1fc58c11ba5b685c06b7e0f466b0e6089bd/multibody/fem/mpm-dev/ElastoPlasticModel.h#L25)):*
> ```objc
>     // Kirchhoff stress density: tau = P Fᴱ^T = dψ/dFᴱ Fᴱ^T, where ψ denotes the
>     // energy density
>     virtual void CalcKirchhoffStress(const Matrix3<double>& FE,
> ```

nit consider whether you need this function as it seems like only `UpdateDeformationGradientAndCalcKirchhoffStress` is ever called.
___
*[`multibody/fem/mpm-dev/ElastoPlasticModel.h` line 32 at r4](https://reviewable.io/reviews/yiminlin-tri/drake/24#-N6sZTdS19J9dz33lm9Y:-N6sZTdS19J9dz33lm9Z:b92av8k) ([raw file](https://github.com/yiminlin-tri/drake/blob/a37fa1fc58c11ba5b685c06b7e0f466b0e6089bd/multibody/fem/mpm-dev/ElastoPlasticModel.h#L32)):*
> ```objc
>     // projection is according to the associative plastic flow rule. If the
>     // model is purely plastic, the elastic deformation gradient is unchanged.
>     virtual void UpdateDeformationGradient(
> ```

nit consider whether you need this function as it seems like only `UpdateDeformationGradientAndCalcKirchhoffStress` is ever called.
___
*[`multibody/fem/mpm-dev/test/ElastoPlasticModel_test.cc` line 229 at r4](https://reviewable.io/reviews/yiminlin-tri/drake/24#-N6s_oDB9AIIiS2JtHZo:-N6s_oDB9AIIiS2JtHZp:b-mp4pd3) ([raw file](https://github.com/yiminlin-tri/drake/blob/a37fa1fc58c11ba5b685c06b7e0f466b0e6089bd/multibody/fem/mpm-dev/test/ElastoPlasticModel_test.cc#L229)):*
> ```cpp
>     tau_dev1 = tau1 - 1.0/3.0*tau1.trace()*Matrix3<double>::Identity();
>     in_yield_surface1 = (std::sqrt(3.0/2.0)*tau_dev1.norm()
>                       <= tau_c1 + TOLERANCE);
> ```

I think we should test that the stress is **on** the yield surface (up to some numerical error), which is stronger than the test that the stress is **inside** the surface.


<!-- Sent from Reviewable.io -->

2022-07-13 17:38 UTC, xuchenhan-tri approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 12 files at r4.
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/24#-:-N6scy172G2jXpIW2zvd:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @yiminlin-tri)



<!-- Sent from Reviewable.io -->

2022-07-13 19:27 UTC, yiminlin-tri reviewed
Thanks! I removed some unused functions, can you take a look?

> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/24#-:-N6t0wFW862ThsC46_d8:bcf2v7q)* status: 15 of 21 files reviewed, 1 unresolved discussion (waiting on @xuchenhan-tri)

___
*[`multibody/fem/mpm-dev/test/ElastoPlasticModel_test.cc` line 229 at r4](https://reviewable.io/reviews/yiminlin-tri/drake/24#-N6s_oDB9AIIiS2JtHZo:-N6sboqC25A3I6h6bQJk:b-896fix) ([raw file](https://github.com/yiminlin-tri/drake/blob/a37fa1fc58c11ba5b685c06b7e0f466b0e6089bd/multibody/fem/mpm-dev/test/ElastoPlasticModel_test.cc#L229)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I think we should test that the stress is **on** the yield surface (up to some numerical error), which is stronger than the test that the stress is **inside** the surface.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-13 20:37 UTC, xuchenhan-tri requested changes
One last tiny thing. Feel free to merge after resolving.

> Reviewed 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/24#-:-N6tGp1q-UWWkN55CDtH:b-8a2a9b)* status: all files reviewed, 2 unresolved discussions (waiting on @yiminlin-tri)

___
*[`multibody/fem/mpm-dev/StvkHenckyWithVonMisesModel.h` line 65 at r5](https://reviewable.io/reviews/yiminlin-tri/drake/24#-N6tGblU-3StX7WqqRn9:-N6tGblU-3StX7WqqRnA:brehkcm) ([raw file](https://github.com/yiminlin-tri/drake/blob/27036f3000b24e50fab92fc94bb575e73439ac07/multibody/fem/mpm-dev/StvkHenckyWithVonMisesModel.h#L65)):*
> ```objc
>     // Yield stress is the minimum stress at which the material undergoes
>     // plastic deformation
>     // @pre yield_stress >= 0
> ```

nit, I realize that we need yield_stress > 0 (not equal to 0), because otherwise we may divide by zero later.
___
*[`multibody/fem/mpm-dev/StvkHenckyWithVonMisesModel.cc` line 126 at r5](https://reviewable.io/reviews/yiminlin-tri/drake/24#-N6tGk7d3njXsubCkb01:-N6tGk7d3njXsubCkb02:bn6jjfc) ([raw file](https://github.com/yiminlin-tri/drake/blob/27036f3000b24e50fab92fc94bb575e73439ac07/multibody/fem/mpm-dev/StvkHenckyWithVonMisesModel.cc#L126)):*
> ```cpp
>         Vector3<double> nu = StvkHenckyWithVonMisesModel::sqrt_32
>                             *trial_stress_data.tau_dev_hat
>                             /trial_stress_data.tau_dev_hat_norm;
> ```

nit if tau_c == 0, this may be dividing by zero.


<!-- Sent from Reviewable.io -->

2022-07-13 20:48 UTC, yiminlin-tri reviewed
> Reviewed 1 of 14 files at r1, 5 of 20 files at r3, 6 of 12 files at r4, 4 of 6 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/24)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yiminlin-tri)



<!-- Sent from Reviewable.io -->

2022-07-13 20:48 UTC, merged