Implementation of sort particles
yiminlin-tri/drake pull request #9
Opened 2022-05-24 23:13 UTC by yiminlin-tri

Sort particles according to batches. Add in some additional routines in the Particle class, need refactors in the future.

2022-05-24 23:13 UTC, yiminlin-tri reviewed
@xuchenhan-tri  Thanks!

> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/9#-:-N2sLFJGEWFWKaZEf8O9:b-emxud)* status: 0 of 8 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-05-25 00:44 UTC, xuchenhan-tri requested changes
I reviewed the transfer class. PTAL at the questions.

> Reviewed 4 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/9#-:-N2sexoJ9GCHxMpzODy-:b-wp2czn)* status: 4 of 8 files reviewed, 5 unresolved discussions (waiting on @xuchenhan-tri and @yiminlin-tri)

___
*[`multibody/fem/mpm-dev/MPMTransfer.h` line 19 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/9#-N2sd54u84HzsXBbKw9t:-N2sby12EU_VezvsP-c4:b-vzi1z) ([raw file](https://github.com/yiminlin-tri/drake/blob/6081627e8a09c5d9d80d21b5820db6242bf97368/multibody/fem/mpm-dev/MPMTransfer.h#L19)):*
> ```objc
> class MPMTransfer {
>  public:
>     explicit MPMTransfer(const Grid& grid, const Particles& particles);
> ```

It's unclear to me why `particles` is needed for the constructor. It seems like it's not really used?
I don't see how the grid is necessary either for that matter.
___
*[`multibody/fem/mpm-dev/MPMTransfer.h` line 55 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/9#-N2scP5HBDTKrETMAB92:-N2scP5HBDTKrETMAB93:b-273627) ([raw file](https://github.com/yiminlin-tri/drake/blob/6081627e8a09c5d9d80d21b5820db6242bf97368/multibody/fem/mpm-dev/MPMTransfer.h#L55)):*
> ```objc
>     void SortParticles(const Grid& grid, Particles* particles);
> 
>     int get_batch_starting_index(int batch_number) const;
> ```

Why do we need this to be public? In my mental picture, the concept of a "batch" should be internal to the transfer class. The user of this class doesn't need to know the implementation details.
___
*[`multibody/fem/mpm-dev/MPMTransfer.h` line 62 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/9#-N2scBsY72kc9GZDP1_y:-N2scBsY72kc9GZDP1_z:b749ba5) ([raw file](https://github.com/yiminlin-tri/drake/blob/6081627e8a09c5d9d80d21b5820db6242bf97368/multibody/fem/mpm-dev/MPMTransfer.h#L62)):*
> ```objc
>     int num_batches_;
>     int num_particles_;
>     std::vector<BSpline> bases_{};
> ```

What do we need `bases_` for?
___
*[`multibody/fem/mpm-dev/MPMTransfer.cc` line 49 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/9#-N2sdeVF8J6K34zObmC9:-N2sdeVF8J6K34zObmCA:b3c2obr) ([raw file](https://github.com/yiminlin-tri/drake/blob/6081627e8a09c5d9d80d21b5820db6242bf97368/multibody/fem/mpm-dev/MPMTransfer.cc#L49)):*
> ```cpp
>     std::stable_sort(sorted_indices.begin(), sorted_indices.end(),
>        [&grid, particles, h](size_t i1, size_t i2) {
>       return grid.Reduce3DIndex(std::round(particles->get_position_x(i1)/h),
> ```

We should have a function that calculates the base node index of a particle.
In addtion, we are computing the base node for (a lot) more times than necessary -- Right now the base node computation happens for each comparison that takes place, whereas we should only compute it once per particle.
___
*[`multibody/fem/mpm-dev/MPMTransfer.cc` line 58 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/9#-N2sdwoC-Z77Siquimsn:-N2sdwoC-Z77Siquimso:b-kqek23) ([raw file](https://github.com/yiminlin-tri/drake/blob/6081627e8a09c5d9d80d21b5820db6242bf97368/multibody/fem/mpm-dev/MPMTransfer.cc#L58)):*
> ```cpp
>     batch_starting_index_[0] = 0;
>     for (int p = 0; p < num_particles; ++p) {
>         positions_sorted[p] =
> ```

Ideally this would be encapsulated in the particle class. i.e. The particle class should provide an API of the sort `void Reorder(const std::vector<int>& new_order)`.


<!-- Sent from Reviewable.io -->

2022-05-25 02:44 UTC, yiminlin-tri reviewed
Replied. Thanks!

> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/9#-:-N2ssz2mDOXpKiC_whMZ:b-n20t3i)* status: 4 of 8 files reviewed, 5 unresolved discussions (waiting on @xuchenhan-tri)

___
*[`multibody/fem/mpm-dev/MPMTransfer.h` line 19 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/9#-N2sd54u84HzsXBbKw9t:-N2sjwELCwji19e2ix_K:b29slju) ([raw file](https://github.com/yiminlin-tri/drake/blob/6081627e8a09c5d9d80d21b5820db6242bf97368/multibody/fem/mpm-dev/MPMTransfer.h#L19)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

It's unclear to me why `particles` is needed for the constructor. It seems like it's not really used?
I don't see how the grid is necessary either for that matter.
</blockquote></details>

grid is used to initialize bases_ (vector of BSpline), particles is used to store int num_particles_. I agree, they are not necessary in this PR, and I just removed. Thanks!
___
*[`multibody/fem/mpm-dev/MPMTransfer.h` line 55 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/9#-N2scP5HBDTKrETMAB92:-N2skyQ4-NMLBQ8JuusJ:b9b2gfq) ([raw file](https://github.com/yiminlin-tri/drake/blob/6081627e8a09c5d9d80d21b5820db6242bf97368/multibody/fem/mpm-dev/MPMTransfer.h#L55)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Why do we need this to be public? In my mental picture, the concept of a "batch" should be internal to the transfer class. The user of this class doesn't need to know the implementation details.
</blockquote></details>

Done. But seems like I still need to put them as public, otherwise I cannot test them. How about I turn them private in future PRs?
___
*[`multibody/fem/mpm-dev/MPMTransfer.h` line 62 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/9#-N2scBsY72kc9GZDP1_y:-N2sl06X-Dhuk9sYhIjS:b5clhyh) ([raw file](https://github.com/yiminlin-tri/drake/blob/6081627e8a09c5d9d80d21b5820db6242bf97368/multibody/fem/mpm-dev/MPMTransfer.h#L62)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

What do we need `bases_` for?
</blockquote></details>

What I want to achieve is to store the vector of BSpline as bases_, and then in the next PR I will evaluate nodal values and gradients of BSpline on particle positions. I will remove it for now and put it back in the next PR. Thanks!
___
*[`multibody/fem/mpm-dev/MPMTransfer.cc` line 49 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/9#-N2sdeVF8J6K34zObmC9:-N2t4Pra8z2Bnem_JWQK:bb6un1j) ([raw file](https://github.com/yiminlin-tri/drake/blob/6081627e8a09c5d9d80d21b5820db6242bf97368/multibody/fem/mpm-dev/MPMTransfer.cc#L49)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

We should have a function that calculates the base node index of a particle.
In addtion, we are computing the base node for (a lot) more times than necessary -- Right now the base node computation happens for each comparison that takes place, whereas we should only compute it once per particle.
</blockquote></details>

Done
___
*[`multibody/fem/mpm-dev/MPMTransfer.cc` line 58 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/9#-N2sdwoC-Z77Siquimsn:-N2st4PCBAABGvqbFF3t:bb6un1j) ([raw file](https://github.com/yiminlin-tri/drake/blob/6081627e8a09c5d9d80d21b5820db6242bf97368/multibody/fem/mpm-dev/MPMTransfer.cc#L58)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Ideally this would be encapsulated in the particle class. i.e. The particle class should provide an API of the sort `void Reorder(const std::vector<int>& new_order)`.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2022-05-25 17:08 UTC, xuchenhan-tri requested changes
I reviewed everything other than the tests now. PTAL.

> Reviewed 4 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/9#-:-N2wB8mG5ajInVnC2ALs:bjqbn78)* status: 6 of 8 files reviewed, 13 unresolved discussions (waiting on @xuchenhan-tri and @yiminlin-tri)

___
*[`multibody/fem/mpm-dev/MPMTransfer.h` line 55 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/9#-N2scP5HBDTKrETMAB92:-N2vzV7X6qgZXexTtX3M:bd069cd) ([raw file](https://github.com/yiminlin-tri/drake/blob/6081627e8a09c5d9d80d21b5820db6242bf97368/multibody/fem/mpm-dev/MPMTransfer.h#L55)):*
<details><summary><i>Previously, yiminlin-tri wrote…</i></summary><blockquote>

Done. But seems like I still need to put them as public, otherwise I cannot test them. How about I turn them private in future PRs?
</blockquote></details>

You can friend the tester so that the tests have access to private members of the class.

See for example [here](https://github.com/RobotLocomotion/drake/blob/eda46d08740272f8bfb6ef1f33482bab389949d3/multibody/fem/volumetric_element.h#L266) and [here](https://github.com/RobotLocomotion/drake/blob/eda46d08740272f8bfb6ef1f33482bab389949d3/multibody/fem/test/volumetric_element_test.cc#L42)
___
*[`multibody/fem/mpm-dev/MPMTransfer.h` line 78 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/9#-N2w37x2-l81OSzkiwed:-N2w37x2-l81OSzkiwee:b1vabks) ([raw file](https://github.com/yiminlin-tri/drake/blob/2488cd4924058695722142383d6f465ee60c4084/multibody/fem/mpm-dev/MPMTransfer.h#L78)):*
> ```objc
>     // Each batch holds 2, 2, 1, 0, 0 particles
>     // batch_starting_index_ is updated every time we called SortParticles()
>     std::vector<int> batch_starting_index_{};
> ```

I don't see why this needs to be a data member when we allocate for `batch_indices` and `sorted_indices` on the fly in `SortParticles`. For consistency, we should either allocate for all of them in the same place -- either on the fly in `SortParticles` or put them in a private struct as internal scratch pad.
___
*[`multibody/fem/mpm-dev/MPMTransfer.cc` line 47 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/9#-N2w41e-80VeCt46izM6:-N2w41e-80VeCt46izM7:b19f2jt) ([raw file](https://github.com/yiminlin-tri/drake/blob/6081627e8a09c5d9d80d21b5820db6242bf97368/multibody/fem/mpm-dev/MPMTransfer.cc#L47)):*
> ```cpp
> 
>     std::iota(sorted_indices.begin(), sorted_indices.end(), 0);
>     std::stable_sort(sorted_indices.begin(), sorted_indices.end(),
> ```

Why do we need the sort to be stable?
___
*[`multibody/fem/mpm-dev/MPMTransfer.cc` line 49 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/9#-N2sdeVF8J6K34zObmC9:-N2w0DQQ38Dn9rmlPBqb:b-aw5wna) ([raw file](https://github.com/yiminlin-tri/drake/blob/6081627e8a09c5d9d80d21b5820db6242bf97368/multibody/fem/mpm-dev/MPMTransfer.cc#L49)):*
<details><summary><i>Previously, yiminlin-tri wrote…</i></summary><blockquote>

Done
</blockquote></details>

I think we are still doing `Reduce3DIndex` more times than necessary?
___
*[`multibody/fem/mpm-dev/MPMTransfer.cc` line 15 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/9#-N2w6-UJ4uvAR9xNGNCA:-N2w6-UJ4uvAR9xNGNCB:b-9d79xn) ([raw file](https://github.com/yiminlin-tri/drake/blob/2488cd4924058695722142383d6f465ee60c4084/multibody/fem/mpm-dev/MPMTransfer.cc#L15)):*
> ```cpp
>     int idx_batch_curr = 0;
>     int num_batches = grid.get_num_gridpt();
>     double h = grid.get_h();
> ```

nit unnecessary temp?
___
*[`multibody/fem/mpm-dev/MPMTransfer.cc` line 17 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/9#-N2w5myCBTqwIzyu1BSJ:-N2w5myCBTqwIzyu1BSK:bp2jkm3) ([raw file](https://github.com/yiminlin-tri/drake/blob/2488cd4924058695722142383d6f465ee60c4084/multibody/fem/mpm-dev/MPMTransfer.cc#L17)):*
> ```cpp
>     double h = grid.get_h();
>     int num_particles = particles->get_num_particles();
>     std::vector<size_t> sorted_indices(num_particles);
> ```

nit `sorted_indices` and `batch_indices` could use a comment to describe what they do.
___
*[`multibody/fem/mpm-dev/MPMTransfer.cc` line 18 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/9#-N2w4_1J8giqtlSVdF6N:-N2w4_1J8giqtlSVdF6O:b-9d79xn) ([raw file](https://github.com/yiminlin-tri/drake/blob/2488cd4924058695722142383d6f465ee60c4084/multibody/fem/mpm-dev/MPMTransfer.cc#L18)):*
> ```cpp
>     int num_particles = particles->get_num_particles();
>     std::vector<size_t> sorted_indices(num_particles);
>     Vector3<double> xp;
> ```

nit unnecessary temp?
___
*[`multibody/fem/mpm-dev/MPMTransfer.cc` line 26 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/9#-N2w1qaw4Y7G3HlC0JjJ:-N2w1qaw4Y7G3HlC0JjK:b-wg8ahq) ([raw file](https://github.com/yiminlin-tri/drake/blob/2488cd4924058695722142383d6f465ee60c4084/multibody/fem/mpm-dev/MPMTransfer.cc#L26)):*
> ```cpp
>     for (int p = 0; p < num_particles; ++p) {
>         batch_indices[p] = Vector3<int>(
>                                 std::round(particles->get_position_x(p)/h),
> ```

nit this should use `CalcBatchIndex()`
___
*[`multibody/fem/mpm-dev/MPMTransfer.cc` line 42 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/9#-N2w8NsVCpZhEbd0yx34:-N2w6b1uCB_yvOvYxcWp:b-38q8tv) ([raw file](https://github.com/yiminlin-tri/drake/blob/2488cd4924058695722142383d6f465ee60c4084/multibody/fem/mpm-dev/MPMTransfer.cc#L42)):*
> ```cpp
>     particles->Reorder(sorted_indices);
> 
>     // Construct starting indices of batches
> ```

It seems like this subroutine can be made cleaner by doing a single loop over grid nodes. We already know the number of particles associated with each grid node from the calculation above.
___
*[`multibody/fem/mpm-dev/MPMTransfer.cc` line 48 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/9#-N2w7LiX8IRrqFoyYy-S:-N2w7LiX8IRrqFoyYy-T:b-xxdzo1) ([raw file](https://github.com/yiminlin-tri/drake/blob/2488cd4924058695722142383d6f465ee60c4084/multibody/fem/mpm-dev/MPMTransfer.cc#L48)):*
> ```cpp
>         idx_batch_prev = idx_batch_curr;
>         xp = particles->get_position(p);
>         idx_batch_curr = grid.Reduce3DIndex(batch_indices[p_new](0),
> ```

We already calculated this in `batch_indices`, right?
___
*[`multibody/fem/mpm-dev/MPMTransfer.cc` line 64 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/9#-N2w9Dad3hNyv6RRQ38M:-N2w9Dad3hNyv6RRQ38N:b-7dhcbw) ([raw file](https://github.com/yiminlin-tri/drake/blob/2488cd4924058695722142383d6f465ee60c4084/multibody/fem/mpm-dev/MPMTransfer.cc#L64)):*
> ```cpp
> }
> 
> int MPMTransfer::get_batch_starting_index(int batch_number) const {
> ```

I don't think we need this getter anymore since it will be private anyway.
___
*[`multibody/fem/mpm-dev/MPMTransfer.cc` line 68 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/9#-N2w9HdIApxn_yHbskRO:-N2w9HdIApxn_yHbskRP:buzc58k) ([raw file](https://github.com/yiminlin-tri/drake/blob/2488cd4924058695722142383d6f465ee60c4084/multibody/fem/mpm-dev/MPMTransfer.cc#L68)):*
> ```cpp
> }
> 
> int MPMTransfer::get_num_particles_in_batch(int batch_number, int num_batches,
> ```

unused?
___
*[`multibody/fem/mpm-dev/Particles.cc` line 138 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/9#-N2wAnnb0ohADCqADfeP:-N2wAnnb0ohADCqADfeQ:b-m4xii0) ([raw file](https://github.com/yiminlin-tri/drake/blob/2488cd4924058695722142383d6f465ee60c4084/multibody/fem/mpm-dev/Particles.cc#L138)):*
> ```cpp
> }
> 
> void Particles::Reorder(const std::vector<size_t>& new_order) {
> ```

BTW I think you can do the reordering in place, but probably not worth the trouble.
___
*[`multibody/fem/mpm-dev/Particles.cc` line 155 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/9#-N2wAszbCBEJHpyXIEH9:-N2wAszcD80Lr75Oc4-Z:b-zgg2by) ([raw file](https://github.com/yiminlin-tri/drake/blob/2488cd4924058695722142383d6f465ee60c4084/multibody/fem/mpm-dev/Particles.cc#L155)):*
> ```cpp
>         kirchhoff_stresses_sorted[p]    = kirchhoff_stresses_[p_new];
>     }
>     positions_             = positions_sorted;
> ```

You can swap positions_ [...]

2022-05-25 23:10 UTC, yiminlin-tri reviewed
Replied. Thanks!

> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/9#-:-N2xTfuj1nQRHJBpU8YB:b-n20t3i)* status: 2 of 8 files reviewed, 9 unresolved discussions (waiting on @xuchenhan-tri)

___
*[`multibody/fem/mpm-dev/MPMTransfer.h` line 55 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/9#-N2scP5HBDTKrETMAB92:-N2xSTXf8e8nASqyfDkD:bb6un1j) ([raw file](https://github.com/yiminlin-tri/drake/blob/6081627e8a09c5d9d80d21b5820db6242bf97368/multibody/fem/mpm-dev/MPMTransfer.h#L55)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

You can friend the tester so that the tests have access to private members of the class.

See for example [here](https://github.com/RobotLocomotion/drake/blob/eda46d08740272f8bfb6ef1f33482bab389949d3/multibody/fem/volumetric_element.h#L266) and [here](https://github.com/RobotLocomotion/drake/blob/eda46d08740272f8bfb6ef1f33482bab389949d3/multibody/fem/test/volumetric_element_test.cc#L42)
</blockquote></details>

Done
___
*[`multibody/fem/mpm-dev/MPMTransfer.h` line 78 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/9#-N2w37x2-l81OSzkiwed:-N2xSWRN3M6PQv4TUaOJ:bb6un1j) ([raw file](https://github.com/yiminlin-tri/drake/blob/2488cd4924058695722142383d6f465ee60c4084/multibody/fem/mpm-dev/MPMTransfer.h#L78)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I don't see why this needs to be a data member when we allocate for `batch_indices` and `sorted_indices` on the fly in `SortParticles`. For consistency, we should either allocate for all of them in the same place -- either on the fly in `SortParticles` or put them in a private struct as internal scratch pad.
</blockquote></details>

Done
___
*[`multibody/fem/mpm-dev/MPMTransfer.cc` line 47 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/9#-N2w41e-80VeCt46izM6:-N2wGZeP00RMLEsux5gP:b9aopp5) ([raw file](https://github.com/yiminlin-tri/drake/blob/6081627e8a09c5d9d80d21b5820db6242bf97368/multibody/fem/mpm-dev/MPMTransfer.cc#L47)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Why do we need the sort to be stable?
</blockquote></details>

Done. Not necessary - Changed to sort. Thanks!
___
*[`multibody/fem/mpm-dev/MPMTransfer.cc` line 49 at r1](https://reviewable.io/reviews/yiminlin-tri/drake/9#-N2sdeVF8J6K34zObmC9:-N2wQMXN4vVVGXbWFKMA:bb6un1j) ([raw file](https://github.com/yiminlin-tri/drake/blob/6081627e8a09c5d9d80d21b5820db6242bf97368/multibody/fem/mpm-dev/MPMTransfer.cc#L49)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I think we are still doing `Reduce3DIndex` more times than necessary?
</blockquote></details>

Done
___
*[`multibody/fem/mpm-dev/MPMTransfer.cc` line 15 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/9#-N2w6-UJ4uvAR9xNGNCA:-N2wQIYv7bN7cC3zI9BL:bb6un1j) ([raw file](https://github.com/yiminlin-tri/drake/blob/2488cd4924058695722142383d6f465ee60c4084/multibody/fem/mpm-dev/MPMTransfer.cc#L15)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit unnecessary temp?
</blockquote></details>

Done
___
*[`multibody/fem/mpm-dev/MPMTransfer.cc` line 17 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/9#-N2w5myCBTqwIzyu1BSJ:-N2xTRLq0PpSQGRZo3yd:bb6un1j) ([raw file](https://github.com/yiminlin-tri/drake/blob/2488cd4924058695722142383d6f465ee60c4084/multibody/fem/mpm-dev/MPMTransfer.cc#L17)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit `sorted_indices` and `batch_indices` could use a comment to describe what they do.
</blockquote></details>

Done
___
*[`multibody/fem/mpm-dev/MPMTransfer.cc` line 18 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/9#-N2w4_1J8giqtlSVdF6N:-N2wEWyT4Q-j-hMp2YWB:bb6un1j) ([raw file](https://github.com/yiminlin-tri/drake/blob/2488cd4924058695722142383d6f465ee60c4084/multibody/fem/mpm-dev/MPMTransfer.cc#L18)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit unnecessary temp?
</blockquote></details>

Done
___
*[`multibody/fem/mpm-dev/MPMTransfer.cc` line 26 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/9#-N2w1qaw4Y7G3HlC0JjJ:-N2wGV_l1i2VGK-cEzkO:bb6un1j) ([raw file](https://github.com/yiminlin-tri/drake/blob/2488cd4924058695722142383d6f465ee60c4084/multibody/fem/mpm-dev/MPMTransfer.cc#L26)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit this should use `CalcBatchIndex()`
</blockquote></details>

Done
___
*[`multibody/fem/mpm-dev/MPMTransfer.cc` line 42 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/9#-N2w8NsVCpZhEbd0yx34:-N2xTTy08zErIl0NQodz:bb6un1j) ([raw file](https://github.com/yiminlin-tri/drake/blob/2488cd4924058695722142383d6f465ee60c4084/multibody/fem/mpm-dev/MPMTransfer.cc#L42)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

It seems like this subroutine can be made cleaner by doing a single loop over grid nodes. We already know the number of particles associated with each grid node from the calculation above.
</blockquote></details>

Done
___
*[`multibody/fem/mpm-dev/MPMTransfer.cc` line 48 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/9#-N2w7LiX8IRrqFoyYy-S:-N2wNGyc4gxEt_eLed75:bfhobu) ([raw file](https://github.com/yiminlin-tri/drake/blob/2488cd4924058695722142383d6f465ee60c4084/multibody/fem/mpm-dev/MPMTransfer.cc#L48)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

We already calculated this in `batch_indices`, right?
</blockquote></details>

Done. Yes, and fixed. Thanks.
___
*[`multibody/fem/mpm-dev/MPMTransfer.cc` line 64 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/9#-N2w9Dad3hNyv6RRQ38M:-N2xTeo5-HOS5AUtm7YX:bb6un1j) ([raw file](https://github.com/yiminlin-tri/drake/blob/2488cd4924058695722142383d6f465ee60c4084/multibody/fem/mpm-dev/MPMTransfer.cc#L64)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I don't think we need this getter anymore since it will be private anyway.
</blockquote></details>

Done
___
*[`multibody/fem/mpm-dev/MPMTransfer.cc` line 68 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/9#-N2w9HdIApxn_yHbskRO:-N2wR97q9REvSQrg5_U_:b-896fix) ([raw file](https://github.com/yiminlin-tri/drake/blob/2488cd4924058695722142383d6f465ee60c4084/multibody/fem/mpm-dev/MPMTransfer.cc#L68)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

unused?
</blockquote></details>

Done.
___
*[`multibody/fem/mpm-dev/Particles.cc` line 138 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/9#-N2wAnnb0ohADCqADfeP:-N2wNXj0AtehNqq0xkKE:b-j2thm2) ([raw file](https://github.com/yiminlin-tri/drake/blob/2488cd4924058695722142383d6f465ee60c4084/multibody/fem/mpm-dev/Particles.cc#L138)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW I think you can do the reordering in place, but probably not worth the trouble.
</blockquote></details>

Done. Yes, we can identify the cyclic permutations... I will leave it here for now and put a TODO. In case the sorting is inefficient I will come back to it later.
___
*[`multibody/fem/mpm-dev/Particles.cc` line 155 at r2](https://reviewable.io/reviews/yiminlin-tri/drake/9#-N2wAszbCBEJHpyXIEH9:-N2wOch36x5e2LHyVMVp:b-b57n4p) ([raw file](https://github.com/yiminlin-tri/drake/blob/2488cd4924058695722142383d6f465ee60c4084/multibody/fem/mpm-dev/Particles.cc#L155)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

You can swap positions_ and positions_sorted which is O(1).

https://www.cplusplus.com/reference/vector/vector/swap/
</blockquote></details>

Done. Thanks! This is very helpful.


<!-- Sent from Reviewable.io -->

2022-05-25 23:43 UTC, xuchenhan-tri requested changes
Reviewed the tests. We are in the home stretch.

> Reviewed 1 of 8 files at r1, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/9#-:-N2xa_se4afmMnMaCcu_:b-rgwuoy)* status: all files reviewed, 7 unresolved discussions (waiting on @yiminlin-tri)

___
*[`multibody/fem/mpm-dev/MPMTransfer.cc` line 25 at r3](https://reviewable.io/reviews/yiminlin-tri/drake/9#-N2xXNap3te0w7HiE4Le:-N2xXNap3te0w7HiE4Lf:b-ndndsg) ([raw file](https://github.com/yiminlin-tri/drake/blob/96e6cb37d271fa2d4cd14cedb29ad9fb98c22899/multibody/fem/mpm-dev/MPMTransfer.cc#L25)):*
> ```cpp
>         batch_indices[p] = grid.Reduce3DIndex(batch_idx_3D(0), batch_idx_3D(1),
>                                               batch_idx_3D(2));
>         batch_sizes_[batch_indices[p]] = batch_sizes_[batch_indices[p]] + 1;
> ```

nit more customary to write `++batch_sizes_[batch_indices[p]]`
___
*[`multibody/fem/mpm-dev/Particles.cc` line 27 at r3](https://reviewable.io/reviews/yiminlin-tri/drake/9#-N2xXsuh5yr9q0ToaF6k:-N2xXsuh5yr9q0ToaF6l:buzc58k) ([raw file](https://github.com/yiminlin-tri/drake/blob/96e6cb37d271fa2d4cd14cedb29ad9fb98c22899/multibody/fem/mpm-dev/Particles.cc#L27)):*
> ```cpp
> }
> 
> double Particles::get_position_x(int index) const {
> ```

unused?
___
*[`multibody/fem/mpm-dev/Particles.cc` line 138 at r3](https://reviewable.io/reviews/yiminlin-tri/drake/9#-N2xY9nd5oVZL_FPQ01Y:-N2xY9nd5oVZL_FPQ01Z:b-4dr5iu) ([raw file](https://github.com/yiminlin-tri/drake/blob/96e6cb37d271fa2d4cd14cedb29ad9fb98c22899/multibody/fem/mpm-dev/Particles.cc#L138)):*
> ```cpp
> }
> 
> void Particles::Reorder(const std::vector<size_t>& new_order) {
> ```

nit DRAKE_DEMAND(new_order == num_particles_); just to be sure.

Also the name `new_order` is vague, either use a more expressive name or document what mapping is expected. i.e. the p-th particle after the reorder corresponds to the new_order[p]-th particle before the reorder.
___
*[`multibody/fem/mpm-dev/test/MPMTransfer_test.cc` line 18 at r3](https://reviewable.io/reviews/yiminlin-tri/drake/9#-N2xZUoV2PSN1aSD48JD:-N2xZUoV2PSN1aSD48JE:b7b1l37) ([raw file](https://github.com/yiminlin-tri/drake/blob/96e6cb37d271fa2d4cd14cedb29ad9fb98c22899/multibody/fem/mpm-dev/test/MPMTransfer_test.cc#L18)):*
> ```cpp
> 
>     void CheckSort1() {
>         // First, construct a 2x2x2 grid centered at (0.0, 0.0, 0.0), with
> ```

nit, this would be a 3x3x3 grid nad 2x2x2 cells?
___
*[`multibody/fem/mpm-dev/test/MPMTransfer_test.cc` line 104 at r3](https://reviewable.io/reviews/yiminlin-tri/drake/9#-N2x_FoC7BxL9IpmH-7W:-N2x_FoC7BxL9IpmH-7X:b-o4h0xf) ([raw file](https://github.com/yiminlin-tri/drake/blob/96e6cb37d271fa2d4cd14cedb29ad9fb98c22899/multibody/fem/mpm-dev/test/MPMTransfer_test.cc#L104)):*
> ```cpp
> 
>     void CheckSort2() {
>         // A more comprehensive test, where we combine particles in above two
> ```

Seems like an artifact from the refactor, there's only a single case above.
The setup of the test is not clear from this description. Could you elaborate?



_Code quote:_
```cpp
        // A more comprehensive test, where we combine particles in above two
        // cases together:
```
___
*[`multibody/fem/mpm-dev/test/MPMTransfer_test.cc` line 187 at r3](https://reviewable.io/reviews/yiminlin-tri/drake/9#-N2xa-nT2mGGAw7Ffd6z:-N2xa-nUEP2pu40c_vST:b-g1duge) ([raw file](https://github.com/yiminlin-tri/drake/blob/96e6cb37d271fa2d4cd14cedb29ad9fb98c22899/multibody/fem/mpm-dev/test/MPMTransfer_test.cc#L187)):*
> ```cpp
> TEST_F(MPMTransferTest, SortParticlesTest) {
>     CheckSort1();
>     CheckSort2();
> ```

Consider adding a test where not all grid nodes are affected by some particles.
___
*[`multibody/fem/mpm-dev/test/Particles_test.cc` line 189 at r3](https://reviewable.io/reviews/yiminlin-tri/drake/9#-N2xaLbr5eRp1JkH4btC:-N2xaLbr5eRp1JkH4btD:b5sz327) ([raw file](https://github.com/yiminlin-tri/drake/blob/96e6cb37d271fa2d4cd14cedb29ad9fb98c22899/multibody/fem/mpm-dev/test/Particles_test.cc#L189)):*
> ```cpp
>     EXPECT_EQ(particles.get_position_x(1), pos2(0));
>     EXPECT_EQ(particles.get_position_y(1), pos2(1));
>     EXPECT_EQ(particles.get_position_z(1), pos2(2));
> ```

Seems like we are missing a unit test for the Reorder function.


<!-- Sent from Reviewable.io -->

2022-05-26 00:49 UTC, yiminlin-tri reviewed
Updated. Thanks!

> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/9#-:-N2xghk12Lzll9k-xE92:b-n4kr80)* status: all files reviewed, 4 unresolved discussions (waiting on @xuchenhan-tri)

___
*[`multibody/fem/mpm-dev/MPMTransfer.cc` line 25 at r3](https://reviewable.io/reviews/yiminlin-tri/drake/9#-N2xXNap3te0w7HiE4Le:-N2xb7rgCc9VW2sK4lU-:bb6un1j) ([raw file](https://github.com/yiminlin-tri/drake/blob/96e6cb37d271fa2d4cd14cedb29ad9fb98c22899/multibody/fem/mpm-dev/MPMTransfer.cc#L25)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit more customary to write `++batch_sizes_[batch_indices[p]]`
</blockquote></details>

Done
___
*[`multibody/fem/mpm-dev/Particles.cc` line 27 at r3](https://reviewable.io/reviews/yiminlin-tri/drake/9#-N2xXsuh5yr9q0ToaF6k:-N2xbZbQ2lno0uY2RIpB:b-am2rv6) ([raw file](https://github.com/yiminlin-tri/drake/blob/96e6cb37d271fa2d4cd14cedb29ad9fb98c22899/multibody/fem/mpm-dev/Particles.cc#L27)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

unused?
</blockquote></details>

Done. Deleted.
___
*[`multibody/fem/mpm-dev/Particles.cc` line 138 at r3](https://reviewable.io/reviews/yiminlin-tri/drake/9#-N2xY9nd5oVZL_FPQ01Y:-N2xhT6SDz_2fYVKmdMY:bb6un1j) ([raw file](https://github.com/yiminlin-tri/drake/blob/96e6cb37d271fa2d4cd14cedb29ad9fb98c22899/multibody/fem/mpm-dev/Particles.cc#L138)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit DRAKE_DEMAND(new_order == num_particles_); just to be sure.

Also the name `new_order` is vague, either use a more expressive name or document what mapping is expected. i.e. the p-th particle after the reorder corresponds to the new_order[p]-th particle before the reorder.
</blockquote></details>

Done
___
*[`multibody/fem/mpm-dev/test/MPMTransfer_test.cc` line 18 at r3](https://reviewable.io/reviews/yiminlin-tri/drake/9#-N2xZUoV2PSN1aSD48JD:-N2xcav894KA0yO8oteD:bb6un1j) ([raw file](https://github.com/yiminlin-tri/drake/blob/96e6cb37d271fa2d4cd14cedb29ad9fb98c22899/multibody/fem/mpm-dev/test/MPMTransfer_test.cc#L18)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, this would be a 3x3x3 grid nad 2x2x2 cells?
</blockquote></details>

Done
___
*[`multibody/fem/mpm-dev/test/MPMTransfer_test.cc` line 104 at r3](https://reviewable.io/reviews/yiminlin-tri/drake/9#-N2x_FoC7BxL9IpmH-7W:-N2xdHzp26iF96-GkfSv:bb6un1j) ([raw file](https://github.com/yiminlin-tri/drake/blob/96e6cb37d271fa2d4cd14cedb29ad9fb98c22899/multibody/fem/mpm-dev/test/MPMTransfer_test.cc#L104)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Seems like an artifact from the refactor, there's only a single case above.
The setup of the test is not clear from this description. Could you elaborate?
</blockquote></details>

Done
___
*[`multibody/fem/mpm-dev/test/MPMTransfer_test.cc` line 187 at r3](https://reviewable.io/reviews/yiminlin-tri/drake/9#-N2xa-nT2mGGAw7Ffd6z:-N2xgOUW6Hal1haMzbYP:bb6un1j) ([raw file](https://github.com/yiminlin-tri/drake/blob/96e6cb37d271fa2d4cd14cedb29ad9fb98c22899/multibody/fem/mpm-dev/test/MPMTransfer_test.cc#L187)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Consider adding a test where not all grid nodes are affected by some particles.
</blockquote></details>

Done
___
*[`multibody/fem/mpm-dev/test/Particles_test.cc` line 189 at r3](https://reviewable.io/reviews/yiminlin-tri/drake/9#-N2xaLbr5eRp1JkH4btC:-N2xpARK0t6Kc9YtJ9ko:bb6un1j) ([raw file](https://github.com/yiminlin-tri/drake/blob/96e6cb37d271fa2d4cd14cedb29ad9fb98c22899/multibody/fem/mpm-dev/test/Particles_test.cc#L189)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Seems like we are missing a unit test for the Reorder function.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2022-05-26 00:56 UTC, xuchenhan-tri requested changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> with two final nits. Thanks for the patience through the iterations!

> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/9#-:-N2xrFca3-ZHreFd5Nht:b-mxqj5y)* status: all files reviewed, 2 unresolved discussions (waiting on @yiminlin-tri)

___
*[`multibody/fem/mpm-dev/Particles.h` line 59 at r4](https://reviewable.io/reviews/yiminlin-tri/drake/9#-N2xqM1O9DMYODwhFjO5:-N2xqM1P9czIWdq3Aqyb:bzhhjir) ([raw file](https://github.com/yiminlin-tri/drake/blob/3caa17aee00cd18b07c455a8899404d2eed58e30/multibody/fem/mpm-dev/Particles.h#L59)):*
> ```objc
>     // TODO(yiminlin.tri): in place sorting
>     // Permute all states in the Particles with respect to the index set
>     // new_order. e.g. given new_order = [3; 1; 2], and the original
> ```

nit, this 1-based indexing is misleading.

Consider adding the following 

```
@pre new_order is a permutation of [0, ..., new_order.size()-1].
```
___
*[`multibody/fem/mpm-dev/Particles.cc` line 128 at r4](https://reviewable.io/reviews/yiminlin-tri/drake/9#-N2xqgjE5vFJPvQCPKCU:-N2xqgjE5vFJPvQCPKCV:bfg0d2k) ([raw file](https://github.com/yiminlin-tri/drake/blob/3caa17aee00cd18b07c455a8899404d2eed58e30/multibody/fem/mpm-dev/Particles.cc#L128)):*
> ```cpp
> void Particles::Reorder(const std::vector<size_t>& new_order) {
>     size_t num_particles = num_particles_;
>     DRAKE_DEMAND(new_order.size() == num_particles);
> ```

You can roll these two lines into

```DRAKE_DEMAND(static_cast<int>(new_order.size()) == num_particles_);```


<!-- Sent from Reviewable.io -->

2022-05-26 01:33 UTC, yiminlin-tri reviewed
Done. Thanks for the detailed suggestions!

> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/9#-:-N2xzoYBE4WXDu9ikSOj:b-j90iqq)* status: all files reviewed, 1 unresolved discussion (waiting on @xuchenhan-tri)

___
*[`multibody/fem/mpm-dev/Particles.h` line 59 at r4](https://reviewable.io/reviews/yiminlin-tri/drake/9#-N2xqM1O9DMYODwhFjO5:-N2xysAS7DObkkB_iVXk:bb6un1j) ([raw file](https://github.com/yiminlin-tri/drake/blob/3caa17aee00cd18b07c455a8899404d2eed58e30/multibody/fem/mpm-dev/Particles.h#L59)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, this 1-based indexing is misleading.

Consider adding the following 

```
@pre new_order is a permutation of [0, ..., new_order.size()-1].
```
</blockquote></details>

Done
___
*[`multibody/fem/mpm-dev/Particles.cc` line 128 at r4](https://reviewable.io/reviews/yiminlin-tri/drake/9#-N2xqgjE5vFJPvQCPKCU:-N2xznDa0ll4SVdsf-OO:bb6un1j) ([raw file](https://github.com/yiminlin-tri/drake/blob/3caa17aee00cd18b07c455a8899404d2eed58e30/multibody/fem/mpm-dev/Particles.cc#L128)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

You can roll these two lines into

```DRAKE_DEMAND(static_cast<int>(new_order.size()) == num_particles_);```

</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2022-05-26 01:34 UTC, yiminlin-tri reviewed
> Reviewed 2 of 8 files at r1, 1 of 5 files at r3, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/9)* status: all files reviewed, 1 unresolved discussion (waiting on @xuchenhan-tri)



<!-- Sent from Reviewable.io -->

2022-05-26 01:36 UTC, yiminlin-tri reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/9#-:-N2y-A5s47We9wX_9WAG:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @xuchenhan-tri)



<!-- Sent from Reviewable.io -->

2022-05-26 01:41 UTC, yiminlin-tri reviewed
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/9)* status: all files reviewed, 1 unresolved discussion (waiting on @xuchenhan-tri)



<!-- Sent from Reviewable.io -->

2022-05-26 03:06 UTC, xuchenhan-tri approved these changes
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/yiminlin-tri/drake/9)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yiminlin-tri)



<!-- Sent from Reviewable.io -->

2022-05-26 03:06 UTC, merged